wekan/wekan

client/views/activities/templates.html
client/views/cards/events.js
client/views/cards/templates.html
collections/cards.js

This PR adds two new actions for archived cards: “send back to board” and “delete”.
A lot of changes in the git diff view are related to empty spaces at the end of lines, which my text editor is configured to automatically remove on file save. Since I'm unlikely to be the only one with this configuration, I would recommend you sticking with this convention and removing trailing spaces in all files.
Still to do:

Archives actions

---

client/lib/popup.js
client/lib/utils.js
client/styles/main.styl
client/views/activities/templates.html
client/views/boards/events.js
client/views/boards/helpers.js
client/views/boards/rendered.js
client/views/boards/routers.js
client/views/boards/templates.html
client/views/cards/events.js
client/views/cards/helpers.js
client/views/cards/rendered.js
client/views/cards/routers.js
client/views/cards/templates.html
client/views/lists/events.js
client/views/lists/templates.html
client/views/main/events.js
client/views/main/helpers.js
client/views/main/routers.js
client/views/main/templates.html
client/views/modal/events.js
client/views/users/events.js
client/views/users/templates.html
client/views/widgets/events.js
client/views/widgets/helpers.js
client/views/widgets/rendered.js
client/views/widgets/templates.html
i18n/en.i18n.json

* New `Popup` public API that can be used directly in Blaze event maps
* Automatically calculate the popup offset using the event target size
and the window dimensions -- before this commit the offset was
hardcoded in the DOM with the "offset" attribute
#54
* Support localised (translated) popup title
* Fix a bug for the labels popup -- going back was opening the popup
in a wrong position
* Click anywhere to close a popup
#62
* Support sub-popups, this is completly transparent in the API, if we
open a popup B from a popup A that will automatically generate a
"back" button from B to A
* Change the context of data provided by iron-router

Popup reform

---

Dockerfile

Fixes docker builds from https://github.com/libreboard/libreboard/commit/6f8d6e3bd27fbc55c6431ee4b576ba4f586e9e30 onwards.

Update Dockerfile to use new meteor version

---

client/lib/keyboard.js
i18n/en.i18n.json

Hey,
This implements simple keybind that assigns self to current card when spacebar is pressed.
It's a feature that I like dearly so I implemented it as it was missing.
Also fixed a very minor translate typo in finnish translation.

Shortcut: Spacebar assigns self to current card, 'F' toggles filter sidebar

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js

The `removeMemberPopup` was missing the required helper to get the user and board
information and the user profile field is called `fullname` and not `name`.

Fix removeMemberPopup

---

client/components/sidebar/sidebarArchives.js

The archived items should be filtered for the current board or else you
will get a global list of all archived items on all boards.
This fixes #318.

sidebar: Filter archived cards/lists for current board

---

.eslintrc
.gitignore
.travis.yml
client/components/activities/comments.js
models/attachments.js
models/users.js
package.json
sandstorm.js

Enable [ESLint-plugin-Meteor](https://github.com/dferber90/eslint-plugin-meteor).
*This PR is an example for how to properly set up ESLint-plugin-Meteor in a project.*
*That's why I included so many annotations in the source code.*
*Make sure to check out the [Files changed](/wekan/wekan/pull/370/files) tab for details.*
This PR enables the rules of ESLint-plugin-Meteor. They
- validate usage of the Meteor API
- prevent overwrites of collections
- define Meteor globals based on the context of the files are used in (browser, server, package, ..)
- [and much more](https://github.com/dferber90/eslint-plugin-meteor/tree/master/docs/rules)
By adding a `package.json` npm's tools can be used for this project.
New developers now don't need to install ESLint and ESLint-plugin-Meteor globally. …

Add ESLint-plugin-Meteor

---

client/components/boards/boardBody.js

Bug behavior: sometimes dragging lists fails, and console report error sortable() on null. 
According to Meteor doc, ```template.$(selector)``` accepts selector (only?), while ```template.find()``` return DOM element, so ```self.$(self.listsDom)``` often returns null.
jQuery $() accepts selector and also DOM element. 
Tested, drag no more fail.

bugfix: 'template.$()' does not accept dom element, but jQuery can

---

.meteor/versions
client/components/main/layouts.jade
client/components/main/layouts.js
client/components/users/userForm.styl

Currently, before login, the user form always display English. This patch set user form language according to browser language, and allow user to select from the language list that WeKan supports.

add: set user preferred lang and allow select lang for user form

---

client/components/cards/cardDetails.jade
client/components/lists/listBody.js
client/components/main/editor.js
client/components/sidebar/sidebar.js
client/components/sidebar/sidebarFilters.jade
models/boards.js
models/users.js
server/lib/utils.js
server/publications/boards.js

My previous implementation of removeMember() is changing userId to "x". The original purpose is to hide the boards from the user once the membership removed. Now I find it brings severe side-effects: when user removed from board, related cards and activities will cause null.username error. This error has to be corrected, and change it back to keep userId unchanged.
Now make changes to the publication, should be the right approach. Also change wherever should see active members only. And some code optimization.

bugfix: only care active members, also optimize some code

---

README.md
scalingo.json

Scalingo is a PaaS that supports Meteor pretty well, we've done a lot of work to make things work out of the box. Oplog and horizontal scaling are available for further needs. Meteor is a really promising technology and we'd be glad helping this project to grow. So this PR is in the continuity of the heroku deploy button and works the same way to let users deploy their own version of 'wekan' in an instant.
You can test the button (link to fork) here : https://github.com/Zyko0/wekan/tree/one_click

One click deploy to Scalingo

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js

I have moved the input component and controls from `cardDetails` template to a separate template called `editCardTitleForm`. 
Then in `cardDetails.js`, I have created the `onRendered` hook and used the autosize package to expand the textarea by default.
Please review the changes, and if I need to change anything kindly let me know!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/463)

Autosize card title

---

client/components/activities/activities.jade

This is a very small change, but it helps very much to see the exact time of an activity.
The activity time is a good description relative to the current time (like "1 month ago"). But sometimes it is important to know the exact time. Now you only have to point your mouse onto it, and it show the exact time stamp.
I hope this helps others, too.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/468)

added exact time as tooltip to activity time

---

docker-compose.yml

Otherwise we run into the following issue with docker-compose 1.5.2:
$ docker-compose up
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Service 'wekandb' configuration key 'ports' contains an invalid type, it should be an array
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/478)

ports in docker-compose.yml must be an array

---

CHANGELOG.md
client/components/main/editor.js
client/lib/keyboard.js
i18n/ar.i18n.json
i18n/ca.i18n.json
i18n/de.i18n.json
i18n/en.i18n.json
i18n/es.i18n.json
i18n/fi.i18n.json
i18n/fr.i18n.json
i18n/it.i18n.json
i18n/ja.i18n.json
i18n/ko.i18n.json
i18n/pt-BR.i18n.json
i18n/ru.i18n.json
i18n/tr.i18n.json
i18n/zh-CN.i18n.json
meta/t9n-changelog/fr.md

Minor thing, Plural of emoji is either emojis or emoji. 
This may be language dependent, so I can remove it from the other language files, but this is definitely true in US English
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/531)

Plural of Emoji

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
i18n/en.i18n.json

I'm offering these simple commands to move cards to the top / bottom of the whole list.
Issue #476 bothering me very much, but "move to top/bottom of the list" are commands I'm using very often. If they're here, then #476 is not that a big problem anymore (but we will still need a proper fix for that).
Please tell me what are you thinking about adding this function, and review my code. I don't know much about Wekan architecture, meteor or mongodb, but this simplest implementation seems to work good. If this PR has any problems with code style or my approach to making things - please tell me, I'm ready to collaborate and change it based on your requirements.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …

Move cards to top / bottom

---

models/users.js

The ES5 reduce method also needs a initial value. This bug was
introduced in aa974aa54ab6e5b7db7450206d12b44ffb3a0306.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/577)

Fix initials avatar generation

---

server/publications/boards.js

The user document contains hashed passwords and hashed resume tokens.
We should only publish the required bits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/579)

Do not publish the whole user doc of board members

---

client/components/users/userAvatar.jade

I had the impression, that the text inside the avatars is not really centered. Instead of adjusting the x-coordinate it seems easier to change the text-anchor to the middle and center the text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/581)

Center text in the initails avatars

---

client/components/boards/boardHeader.jade

This fixes a wrong title on the multi-selection button in the board header bar and adds the title attribute to all the other buttons as well. Especially on the mini-screen view it is important to have titles on the buttons because we have no texts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/580)

Some small fixes for the buttons in the board header

---

CHANGELOG.md
client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
i18n/en.i18n.json

The public board view was kind of broken:
* The notification settings are only useful if you are logged in. It will use the email address from your profile, that is not there if you do not have a user account.
* If the board is private or if the board does not exists the options should not be visible. The visibility indicator for example will display "undefined". So the header bar should be empty if there is no board available.
* If you are member of a public board and you are currently not signed in, you may want to sign in to take changes if you follow a link to a board/card. So I think it is ok to replace the visibility indicator with a sign-in link for public boards. It does not provide any more value. If you can see the board without being logged in, it will always display "public". …

Some UI enhancements for the public board view 

---

client/components/boards/boardHeader.jade

This bug was introduced in 081b09207f2247d7e38fc28e0f0f9748eecbbcbe.
The indentation of the close icon is missing two spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/591)

UI: Fix small bug with the multi-selection button

---

client/components/main/editor.js

The click event handler for links in the card display are overlapping:
The general event for opening the link in a new window matches on user
mentions, too. But user mentions cannot be opened in a new window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/614)

UI: Fix overlapping click event handler

---

.eslintrc.json
client/components/cards/labels.js
i18n/en.i18n.json
models/boards.js
models/cardComments.js
models/cards.js
models/lists.js
models/unsavedEdits.js
models/users.js

The before-insert collection hook has the serious problem, that it is called different if the insert is initiated on the server or on the client. From the client the hook is called before schema validation and can insert default values from required fields. When inserting from the server the hook is called after the validation of simple schema. So the validation fails, because the insert does not contain all required fields. This is a known bug from collection-hooks but there is not workaround available: matb33/meteor-collection-hooks#167
Because of this limitation, it is better to use a autoValue function in the simple schema.
This PR:
* replaces all before-insert hooks with appropriate autoValue functions
* removes a workaround for creating the welcome board after inserting the user
* …

Replace before.insert with autoValue from SimpleSchema

---

client/config/gecko-fix.js

In the Gecko JavaScript engine the Object prototype has a method
'watch()' and 'unwatch()'. This causes strange error messages displayed,
if 'watch' and 'unwatch' are not translated in the chosen localization.
The i18n module cannot handle, if it gets a function for the
translation.
This is a quick fix that removes the 'watch' and 'unwatch' properties
from the Object prototype.
See also: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/watch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/606)

Fix untranslated watch/unwatch for gecko

---

CHANGELOG.md
client/components/cards/attachments.jade
client/components/cards/attachments.styl
client/components/cards/minicard.jade
client/components/cards/minicard.styl

This basically reverts f039923ac134e4a3cc70a1a7d47c21460676b1c0 and fixes #196 in
a different way (adding quotes). So that we can use the css background
properties to scale the cover images.
We could decide, if we want to add a `background-color: black` or something like that to `.minicard-cover`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/593)

UI: Fix scaling of cover images (Fixes: #548)

---

client/components/main/editor.js

When autocompleting an @-mention of a user, if any users would be filtered out by the currently-entered text, there will be an entry "null" shown in the autocomplete dropdown.  This is caused by null return values not getting filtered out of the possible completions array before being visualized.
This commit filters out falsy autocomplete options before passing them off to the UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/649)

Fix bug where you get a "null" option in @-mention autocomplete

---

models/boards.js

This fixes the current actions (adding an activity) when a user leaves a board. The current check if the member is `$pull`'ed from the members list is wrong, because the user is only set to inactive (`isActive` will be false).
This also adds two new features:
* The removed user will be removed from all cards, lists and the board itself from the watchers list (and the member list of the cards). This fixes #667.
* If the board is not public, the board will be remove from the starred list of the removed user. This fixes the starred count of the board. The user could not see the board before but because the `boardId` was contained in the list, the user counted in the star count.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix remove user actions

---

client/components/lists/list.js

'popup' is not in the predefined hierarchy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/782)

Fix executeUpTo label when dragging cards

---

CHANGELOG.md
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
client/components/sidebar/sidebar.styl

I wanted to have a link to the keyboard shortcuts. The user needs to know that there exists some shortcuts to be able to use it. The <kbd>?</kbd> shortcut is nice, but if the user does not know that is exists, he will not find the help page.
I thought a long time about the position for such link:
- First I thought a new button in the board header would be ok, but that it would require to change the dimensions for the mini layout. The new button would lead to a line break before switching to the mini layout.
- The quick-access header or the member settings popup would be another possibility, but it does not look nice.
Finally, I think the bottom of the sidebar is a good position, because it does not disturb too much but the user is able to find it.
---
This change is [<img …

UI: Add link to keyboard shortcuts

---

client/components/sidebar/sidebar.jade

closes #853 
I changed it so that both attributes are in the same parenthesis bracket. I'm not too familiar with JADE but I _think_ that this is the proper way for it to be done. I built the project again (using the `build for production` instructions) and didn't see a build error so I'm assuming it's fixed.
If there's any special procedure to enable verbose build please let me know @xet7 .
Regards,
-Joel :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/856)

to remove 'multiple attributes' error

---

CHANGELOG.md

hierachy ⟶ hierarchy
Replace a with an
intial → initial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/862)

Fix typos in Changelog

---

models/cards.js

Hi,
This pull request corrects the creation of orphan document following the deletion of card in the collections card_comments / checklists / attachments and gridFS collections.
I will had an issue soon, to explain how to remove orphan documents from mongodb databases.
Bye.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/872)

Bug: orphan documents were created when cards were deleted

---

sandstorm-pkgdef.capnp

As of this writing, the spk is in queue to be published in the app market. You can test it out here: https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h?experimental=true
It might be good if someone who knows about the new admin interface can verify that it's not accidentally accessible from the Sandstorm app. As far as I can tell it's not, but I don't really know where to look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/930)

update sandstorm metadata for appVersion 19 release

---

.gitmodules
.meteor/packages
app.env
package.json

This fixes issue #785 by adding a patched local version of kadira:flow-router to wekan. The flow-router fix is explained in issue #785.
I tested this in three instances, each was newly installed in it's own location. The urls that were tested are as follows: `example.com/wekan`, `brd.example.com/wekan`, `brd.example.com`.
It's important to note that when building or starting the server it is required to execute the following command to export the local package directory for meteor: `source app.env`. All worked as expected.
The patched flow-router repo can be transferred to the wekan namespace upon request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/932)

Fixed: Double slash problem 

---

.travis.yml
Dockerfile

1. Add high available server for getting the gpg keys - suppose it should lead to fewer failures on getting the gpg keys leading to some rare build failures.
2. Add a docker build to the `.travis.yml` - this will help determine if pull requests need further review ***before*** merging into devel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/942)

user high availability key server and update  travis.yml for docker builds

---

Dockerfile

This in theory should be the docker fix for the double slash bug. 
It would be useful if someone could test this to make sure it works - I don't have a docker machine setup to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/945)

Dockerfile fix for local packages

---

client/lib/i18n.js

There is no profile language set in a newly created user account. Wekan uses english as fallback language in this case. If there is no current user, Wekan takes care of the navigator properties. Instead we should always have a look at the navigator language.
If the navigator provides multiple preferred languages, select the most-preferred one.
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/716)

Use navigator language by default instead of english

---

sandstorm.js

Fixes breakage from https://github.com/wekan/wekan/pull/925.
The new isCommentOnly property needs to be set when Sandstorm updates user permissions, because otherwise a schema validation error occurs and users never get added as members of boards.
In this pull request we always set `isCommentOnly` to false. Eventually it might make sense to allow "comment-only" permissions to be used in Sandstorm. Doing so would probably involve adding a `canComment` permission (in the sandstorm-pkgdef.capnp) that defaults to `true`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/976)

fix updateUserPermissions() on Sandstorm

---

.eslintrc.json
package.json
server/logger.js
server/observableChanges.js

hi there,
Related here: #1001 
I create a logging mechanism using winstonjs.
The supported log is console, file, and zulip, up to you if you want more.
Actually, only JSON is supported as output.
Possible output 
```
{"userId":"7gLzSQYeLadyScLb4","type":"card","method":"update","doc":{"_id":"DvwygsfayN2KTSFjt","title":"regezrg","members":[],"labelIds":[],"listId":"kFApw5GrTRSwc86BZ","boardId":"ZeEpvQXNfKG2BDoFD","sort":6,"archived":false,"createdAt":"2017-04-14T13:09:56.617Z","dateLastActivity":"2017-04-19T13:51:30.937Z","userId":"7gLzSQYeLadyScLb4"},"fieldNames":["listId","sort","dateLastActivity"],"modifier":{"$set":{"listId":"th5sg8cYSBzB4Qm3J","sort":6,"dateLastActivity":"2017-04-19T13:57:18.579Z"}},"timestamp":"2017-04-19T13:57:18.581Z","message":"","level":"info"}
```
This one is …

add console, file, and zulip logger on database changes

---

.travis.yml
Dockerfile

- make METEOR_EDGE optional.
- Fix node_gyp bug in docker build - docker build works fine now.
- Cannot fix `npm install` in the host because this
runs in the travis container and that is running
on an old ubuntu precise 12 and I'm not sure if that can be updated to gcc-4.9?
***Temporary measure:***
- remove npm install for now.
- Investigate if newer container can run as host on travis or if gcc-4.9 can
be updated on the host. 
- possibly `run install` or `npm test` against docker container
as alternative. Just need to think about how that can be done..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1016)

make METEOR_EDGE optional. Fix node_gyp bug in docker build.

---

client/lib/escapeActions.js

Please Consider disabling unnecessary link functionality.
Closes #806 
Related #337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1042)

Fix disable a href=“#” link

---

client/components/boards/boardBody.js

Win7 and IE 11 when Click on the scrollbar,  the mouse 'sticks' to the scrollbar and slides the slide whenever you move the mouse. 
On investigation it looks like this is caused by IE 11 not emitting a onmouseup event when you click on the scrollbar.
https://stackoverflow.com/questions/29787519/jquery-mouse-up-event-didnt-work-with-ie-11-scrollbar
This PR improves Detect when over the scrollbar and then simply do nothing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1052)

Fix Drag Board To Scroll

---

client/components/main/layouts.js
client/components/users/userHeader.js

A workaround to show Breton label in available languages list.
This PR fixes #1002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1071)

Add Breton label

---

client/components/main/layouts.styl

The viewer has a minimum height of 18px (at least a single line) so the anchor can still be clickable even there is no text shown.
Fixes #1039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1073)

Edit card description with invalid markdown

---

client/components/cards/checklists.jade
client/components/cards/checklists.js

When finished input of checklist item,  open new checklist item.
Closes #828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1099)

Improve input of checklist

---

Dockerfile

This kind-of fixes #1110, but only if you build your Dockerfile with USE_EDGE=true.  The wekanteam/wekan:latest on Docker Hub still has the double-slash bug.
Note that the changes are: fixed a path from /home/wekan/packages to /home/wekan/.meteor/packages; and commented out the 'api.versionsFrom(...)' code in package.js for both kadira-flow-router and meteor-useraccounts-core.  I know nothing about Meteor so there may be a better way to fix this, but the change got it to where my Dockerfile would build, and now there is no double-slash issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1114)

Fix Docker Build when USE_EDGE=true

---

.eslintrc.json
.meteor/packages
client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
i18n/en.i18n.json
models/activities.js
models/integrations.js
server/notifications/outgoing.js
server/publications/boards.js

Send a JSON string as the body of a POST request
Format: text property only
```
payload={"text": "activity log"}
```
Usage
- Enabled
- Disabled
URL field blank
Sample
Post to Slack
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1119)

Add Feature: Outgoing Webhooks

---

snapcraft.yaml

moving to use version script instead of hardcoded version which needs to be updated every release
With this in place, we might abandon build from wekan-snap repository and instead just promote to stable channel builds based on tagged version.
Version should represent last tag + number of git commit since + last git commit id (e.g. 0.32-10-g57219df)
in case of build from tag, this will end up being only tagged version (e.g. 0.32) so we can clearly distinguish those in store when promoting.
Also when bugs are reported, we have easy way to track version they are on in case of non stable channel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1164)

use version scriptlet instead of hardcoded version

---

models/activities.js
server/notifications/outgoing.js

I am working on a [Gogs](https://github.com/gogits/gogs) <--> Wekan integration, and to maintain the data coherence it is necessary to know the IDs of the elements involved in a given activity.
This PR adds several IDs to the webhook payload and the description of the activity.
I am working on some new activities but I will submit a different PR when that's ready.
Please let me know if changes are needed in order to have this merged upstream.
Thank you for this great tool!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1189)

Add some IDs to webhook body

---

client/components/lists/listBody.js
client/components/main/editor.js
sandstorm.js

In the UI, we use \w to match a username which captures most usernames, but not usernames which include a dot (.). This needs to be explicitly included, and this regex should now capture those situations too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1194)

Usernames should be able to include dots (.)

---

models/settings.js

Fixes #1181
I could have encoded the password directly in `client/components/settings/settingBody.js` but then the field in the admin panel wouldn't be human readable, as it is the case now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1190)

Percent-encode SMTP password to prevent URI malformed errors

---

models/wekanCreator.js

Sandstorm will have an activity of adding a member by default which will have an empty userId. This caused issues when importing exported Sandstorm boards.
This PR is related to #799
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1197)

Make userId optional when importing Wekan boards

---

models/trelloCreator.js
models/wekanCreator.js

This PR is related to #1157 
Now, when importing boards from Trello or Wekan, we import the original board activities in order to have the right dates of the activities. Except, there are two issues :
1. Attachments related activities will be created at the time of the import from Trello and Wekan boards
2. Comments related activities will be created at the time of the import from Trello boards only.
The cause of both issues are as follows, we can't - for now - circumvent hooks of CollectionFS, I opened [an issue](https://github.com/matb33/meteor-collection-hooks/issues/225) in the corresponding repository  and once it is resolved, fixes will be implemented and we'll never have the first issue. As of the second issue, Trello doesn't export comments with their ids which prevented me from …

Import activities from Trello and Wekan

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/boards/boardHeader.styl
i18n/en.i18n.json
models/activities.js
models/integrations.js
server/notifications/outgoing.js

Right now, you could only add one webhook from the UI. I added the ability to save many integrations per board (and show them in the UI).
Also, sometimes you may want to subscribe to only certain activities, such as `act-moveCard`. For this purpose I added a field named `activities` to the schema of Integrations. Default value is `all` which gives backwards compatibility.
Before executing `outgoingWebhooks`, integrations are filtered based on the `activities` field.
- In order to be able to CRUD integrations from the added API, I had to delete the autoValue() for userId, as `this.userId` was `null`. Then you provide explicitly the userId from the request body. Is there other way to do this?
`(Unknown)` refers to the `title`field, which for the moment only can be set from the API
---
This …

Improve integrations

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
models/checklists.js

This pull request partially implements #876. It makes checklist items sortable both within a checklist and across checklists. Checklists themselves cannot be sorted but model support for this was added as well.
The previous implementation of the model of checklists didn't support sortable checklist items so a bigger overhaul was necessary.
Known visual glitches: 
When dragging a checklist item to it's new place and releasing the mouse button, it doesn't persist immediately but reversed back to it's previous position. Less than a second later it is at the new position. Reason for this is the interior behaviour of Blaze. Blaze updates the template based upon database changes. Therefore we cannot modify the DOM with the jQuery UI Sortable widget and must cancel the movement after making the …

Add feature: Reorder checklist items 

---

client/components/cards/cardDetails.jade

This small edit makes sure the title of a card is pre-filled in the title field of the "copy card" dialog.
Fixes in part #1213.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1214)

Card title is now pre-filled in copy card dialog

---

client/components/cards/cardDetails.js

#1218 
Remove the cover from the copied card
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1246)

Fix cover cannot be edited on copied card

---

client/components/cards/labels.jade

Only an board administrator can create a label
To determine whether there is a label making authority
Closes #1229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1261)

Fix Other Users cannot create labels

---

client/components/activities/activities.jade
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/lists/listBody.js

Closes #1269 
I reviewed implementation of trello.
As a result, I switched to using a function same as "Top right corner (your username) => Change Settings => Hide system messages" .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1270)

Improve Slider for Comments only in activity feed (#1247)

---

models/activities.js
models/cardComments.js
server/notifications/outgoing.js

This PR adds to webhook body:
- Comments IDs and content
- Cards title
- Author of the activity
Also:
- The API response in the case of a comment creation is sent before creating the activity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1263)

Webhook parameters and response order.

---

client/components/boards/boardColors.styl
client/components/cards/cardDetails.jade

Closes #1274 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1275)

Fix "Hide system messages" slider doesn't obey Wekan color conventions

---

models/boards.js
models/users.js
server/authentication.js

Add the ability for the admin :
- disabling a login for a user (not himself)
- enabling a login for a user
- transfering the ownership of all user's boards to himself
Request
- https://github.com/wekan/wekan/issues/1285
- https://github.com/wekan/wekan/issues/1220
Possibly fix a bug in models/boards.js line 568
- https://github.com/wekan/wekan/issues/1118
Disable a user (the user is not allowed to login and his login tokens are purged)
```shell
curl -H "Authorization: Bearer t7iYB86mXoLfP_XsMegxF41oKT7iiA9lDYiKVtXcctl" \
-H "Content-type:application/json" \
-X PUT \
http://localhost:3000/api/users/ztKvBTzCqmyJ77on8 \
-d '{ "action": "disableLogin" }'
```
Enable a user
```shell
curl -H "Authorization: Bearer t7iYB86mXoLfP_XsMegxF41oKT7iiA9lDYiKVtXcctl" \
-H "Content-type:application/json" …
```

Add disabling a user and/or transfering ownership

---

client/components/lists/listHeader.jade

This fixes #1310 and required for Edge users to be able to edit the WIP limit. (The up/down buttons appear to be "optional" according to the HTML5 spec, and can't be assumed to be present.)
I also believe I fixed a spelling error in the same section.
This PR is **NOT TESTED**
Also, @amadilsons for opinions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1312)

Permit editing the WIP limit

---

client/components/lists/list.styl
client/components/lists/listBody.js
client/components/lists/listHeader.jade
client/components/lists/listHeader.js
models/cards.js
models/lists.js

Added option for a 'Soft Limit'.
Soft limit option behavior,when active:
- any number of cards can be added or moved to the list, regardless of the WIP limit value;
- the WIP limit may be set to a lower value than the current amount of cards in the list;
- any archived cards can be restored regardless of the WIP limit value.
Basicaly, when this option is set, the program behavior remains pretty much the same as if it was working without WIP limits.
I've tested this feature for all use cases but may have missed something! If so, I would be glad to fix whatever is broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1319)

Feature: WIP Soft Limits #1311

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/minicard.jade

#926 
Added markdown to card-titles, mini-card-titles, checklist-title, and checklist-items.
Also added `shift+enter` listener so that a user can press `shift+enter` while editing the textarea can submit a newline, but can still hit `enter` to submit the form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1334)

Added markdown to titles #926

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
models/cards.js

This feature adds copying and moving cards from one board to another.
However, there is a small **issue**, a board's lists can be shown only when that board is being opened before in the browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1330)

Copy|Move cards from one board to another

---

client/components/cards/minicard.styl

introduced by the markdown viewer in commit 309c1d0 (the markdown viewer uses `<p>` tags which have a margin-bottom)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1347)

remove erroneous minicard title whitespace

---

client/components/cards/cardDetails.js

in firefox there is no global `event` object, therefore we should use the `evt` argument from the event handler (this way it works in both browsers, and other browsers without global `event` object)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1348)

card detail: fix title editing with shift key

---

client/components/cards/cardDate.js
client/components/cards/cardDate.styl

Proposed fix for issue #1414 
I chose two new icons (one for start date, one for due date):
An alternative approach could be:
What do you think? Please let me know what I can improve in my solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1420)

Different icons for start date and due date

---

client/components/lists/list.styl

Partially addresses #476:
Repro:
1. Add cards to the list so that scrolling appears (e.g. if 10 cards are usually visible, add 20)
1. Scroll
1. Try to drag a card to the section of the list not originally visible
Expected: drops normally
Actual:
*unable to drop (placeholder not appearing)
* Debug: .js-minicards scrolls out of the view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1424)

Fix for dragging into scrolled-down list #476

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/sidebar/sidebar.js
client/components/sidebar/sidebarSearches.jade
client/components/sidebar/sidebarSearches.js
client/components/sidebar/sidebarSearches.styl
i18n/en.i18n.json
models/boards.js

This PR adds search feature ( related to #552 )
A new search button is added inside an opened board.
On clicking on it, the search sidebar will open and will show the input where to put the search keyword
and the last added ten cards by default.
After typing the keyword, the user has to press enter to start the search.
The matched cards will appear, and by clicking on them, they will open Inside the board.
To make the search as fast as possible, the keyword is matched against the cards' titles and descriptions and only a maximum of ten matches will be shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1503)

Add new search feature

---

client/components/swimlanes/swimlanes.styl

With Google Chrome `writing-mode: sideways-lr;` is marked as invalid property value and swimlane header is under swimlane menu icon.
After this change both Firefox 58 and Google Chrome 64 have properly rotated swimlane header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1526)

Fix swimlane header rotation on Google Chrome

---

models/boards.js

I decided to refuse to create the label if an other label with the same name already exist. I don't know if it's a good idea to check here but it can be easily removed.
So if I create a new label, i return the label id, if not I return nothing without error (can be changed too).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1630)

Add a new API route to create a new label in a given board

---

snapcraft.yaml

Filtering out 
'lib/node_modules/node-pre-gyp/node_modules/tar/lib/.unpack.js.swp'
which is causing review problem in snap store
Adding stage package to remover snapcraft warning about missing dependency
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1660)

filtering out swap file created at build time, adding stage package

---

client/components/cards/cardDetails.styl

Cards that are longer than the screen height can now scroll on the y-axis in order to be able to see the whole card.
Note: My first pull request, so bear with me if I have done something strange :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1782)

bug fix: #1780 (adding scroll to long cards)

---

client/components/cards/cardDetails.jade
models/cards.js

This adds accidentally erased code to set/get `requestedBy` and `assigendBy` properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1831)

Fix removed setters and getters

---

client/components/lists/listBody.jade
client/components/lists/listBody.js
models/cards.js

This PR is to fix #1835 and also improves linking as follows:
- Link button only shows not-already linked cards
- Link button also shows linked-cards in other boards
- If you link this card, the linkedId is used so as to point to the original card
- Search on the other hand, shows all cards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1849)

Fix and improve linked cards

---

sandstorm-pkgdef.capnp

This is probably not a "whole" fix, but this may be a missing piece.
According to https://docs.sandstorm.io/en/latest/developing/http-apis/ an apiPath of "" disallows any API requests, an apiPath of "/" allows the entire app to be served over the API, and an apiPath of "/api" would just allow the API to use the /api subfolder, which is I believe what we want here.
Perhaps @ertanalytics can help test what difference this change makes, if any. My hope is this may bring us into the sandbox where we only have to deal with making sure Wekan's API accepts users authorized in this manner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1851)

Allow Sandstorm to serve Wekan HTTP API

---

client/components/boards/boardBody.js
client/components/cards/cardDetails.js
client/components/main/editor.js

There was an issue with displaying card by url. 3 issues found:
1. If a user was deleted from the system but he was assigned to board this piece of code fails:
`member.username = Users.findOne(member.userId).username;`
So I've replaced it with a check for user to exist:
```javascript
const u = Users.findOne(member.userId);
if(u){
member.username = u.username;
}
```
2. The scrolling was not working as Parent component was not loaded when `scrollParentContainer` function was called so this function should be called after rendering is finished (I've simply added a timeout to exit the rendering function scope and execute it in separate loop):
```javascript
if (!Utils.isMiniScreen()){
Meteor.setTimeout(() => {
this.scrollParentContainer();
}, 500);
}
```
3. In swimlanes mode with lots of cards …

Card url fixed

---

models/customFields.js

A solution to this issue: https://github.com/wekan/wekan/issues/1872
- Now when deleting a customField, all reference of this one are deleted also on cards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1950)

Patch for customFields when deleting them https://github.com/wekan/wekan/issues/1872

---

Dockerfile
models/boards.js
models/cards.js
models/customFields.js
models/export.js
models/users.js

A small batch of updates to provide a few fixes for the REST API:
- also export the cards created with an older wekan instance (without linked cards) (related to #1873)
- fix the GET customFields API that was failing
- allow to directly overwrite the members of cards and boards with a PUT call (this avoids to do multiple calls to `add` and `remove` users)
- allow to change the swimlane of a card from the API
Note: I signed an Apache like CLA and directly sent to @xet7, as my employer didn't want me to sign the current wekan CLA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1962)

Small api fixes

---

models/cards.js

When using x-www-form-urlencoded, we can't really set the member or label field with just one value or even remove it. Allow to do so by tweaking the input value.
Note: Apache I-CLA signed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1968)

Allow to remove the full list of labels/members through the API

---

client/components/rules/triggers/cardTriggers.js

This fixes commit 44e4df2492b95226f1297e7f556d61b1afaab714.
When the label has a name, not setting `translatedname` results in a blank item in the IFTTT label trigger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2119)

Fix: Translate and add colors to IFTTT Rules dropdown."

---

client/components/boards/boardBody.jade
client/components/boards/boardBody.js
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/cards/minicard.js
client/components/lists/list.styl
client/components/rules/actions/cardActions.jade
client/components/rules/actions/cardActions.js
client/components/rules/rules.styl
client/components/swimlanes/swimlaneHeader.jade
client/components/swimlanes/swimlaneHeader.js
client/components/swimlanes/swimlanes.jade
client/components/swimlanes/swimlanes.js
client/components/swimlanes/swimlanes.styl
i18n/en.i18n.json
models/boards.js
models/cards.js
models/lists.js
models/swimlanes.js

For being able to correctly add the swimlanes after the current swimlane, I had to fix the `sort` field for the `Swimlanes`. While at it, I did the same for the `Lists` `sort` field.
This was a bug I had when I created a bunch of `Lists` and `Swimlanes` from the API: it was not possible to reorder them (`sort` being null).
~~We should probably do the same for the `Cards` inside a list.~~
This is on top of #2121 and should fix #1688 for the swimlanes part.
Note that I couldn't get the `Add Swimlane` as an inlined form, so I used a popup.
There are still 3 open questions IMO:
- I would think instead of having the `plus` sign to add a new swimlane, it would be better to have 2 entries in the hamburger menu: `Insert a Swimlane above` and `Insert a Swimlane below`
- ~~in the small display view …

Color for swimlanes

---

client/components/lists/list.styl
client/components/lists/listHeader.jade
client/components/swimlanes/swimlanes.jade

This time with the bottom border only colorized
And make the background clearer to visually separate the header from the list of cards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2130)

lists-color: only colorize the bottom border

---

client/components/swimlanes/swimlanes.jade
client/components/swimlanes/swimlanes.styl

@xet7 
So I think I got this right now. This reverts most of the UI code to v2.02, but keeps the horizontal header for the swimlanes.
I liked the fact that the swimlane header was not moving when scrolling horizontally, but I guess fixing bugs is more important :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2139)

Horizontal fixes

---

client/components/cards/cardDetails.js

We actually want the vertical scrolling to be fixed at potion `100`  when opening the card details.
I am not sure where the `100` value comes from, but this makes the scrolling happy on the swimlane view and on the lists view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2140)

automatic scroll: fix vertical automatic scrolling when opening a card

---

client/components/main/layouts.jade
client/components/main/layouts.js
client/components/settings/settingBody.jade
client/components/settings/settingBody.js
models/settings.js
server/migrations.js
server/publications/settings.js

Adding 2 configuration options in the admin panel
One for enable/disable the dropdown in the sign-in page to chose the authentication method.
The other for selecting the default authentication method used to perform the registration and log in the user when his first time on the site.
Need i18n for the titles.
The default page:
And the page with the display authentication method set to no:
Following the various problems caused by the removal of this dropdown, I have chosen to make it optional and configurable in the admin panel. I also make some test with, but if you have a problem, don't hesitate to contact me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2153)

Improve authentication

---

client/components/boards/boardBody.js
client/components/swimlanes/swimlanes.styl

Since 7cc185ac "Properly fix horizontal rendering on Chrome and Firefox", the rendering of the new design of the swimlanes was correct, but this commit broke the reordering capability. Having the swimlane header at the same level than the lists of cards makes the whole sortable
pattern fail.
2 solutions:
- revert to only have 1 div per swimlane. But this introduces the firefox bug mentioned in 7cc185ac, so not ideal
- force the sortable pattern to do what we want.
To force the sortable pattern, we need:
- add in the helper a clone of the list of cards (to not just move the header)
- make sure the placeholder never get placed between the header and the list of cards in a swimlane
- fix the finding of the next and previous list of cards.
For all of this to be successful, we need to resize …

Fix swimlanes sorting

---

client/components/main/layouts.jade
client/components/settings/connectionMethod.jade
client/components/settings/connectionMethod.js

There is a little bug when selecting the default authentication method in the admin panel and enable the dropdown. The default authentication method is not selected by default in the dropdown on the sign in page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2191)

Fix authentication dropdown

---

.meteor/packages
.meteor/versions
models/attachments.js
models/checklistItems.js
models/customFields.js
models/integrations.js
server/publications/boards.js

This adds performance improvements including:
- New indexes for queries that were missing an index
- Bulk querying documents to reduce the number of mongo queries when loading a board
- Ensure oplog is being used to query the database by providing a `sort` key when `limit` is used querying the `boards` collection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2214)

Performance Enhancements

---

client/components/activities/activities.jade
client/components/activities/activities.js
i18n/en.i18n.json
models/cards.js

Foreword: I am not entirely sure this is the *correct* thing to do.
My use case is: We have a bunch of cards to track our progress in various projects. On these cards, we do have some custom fields to track the amount of work. We do not want to track the actual time in hours, but we use an abstract relative number.
Among the numbers is the total estimated size of the project. This estimate is subject to being re-evaluated during the project and I want to get the variations of this number. This is useful for projects that gets re-evaluated during a long period of time. We also register how much work has been done during a period of time, and we want to track the efforts towards each project during the period.
So 2 options:
- we dump the db at each milestone, and then compare with the …

Activities: register customFields changes in the activities

---

models/cards.js

Looks like I forgot to use the camelCase notation here, and this leads to an exception while updating a custom field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2244)

customFields: fix leftover from lint

---

server/migrations.js

@xet7 Please tell me if this is sufficient to run the migration once more in newest wekan release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2248)

Rename migration to re run

---

client/components/settings/settingBody.js

Email addresses for invitations are stored case sensitive in mongo,
together with the invitation codes. When someone tries to sign up due to
an invitation, in the sign up form, due to AccountsTemplates defaults,
the email address is lowercased on blur of the textbox. When they then
try to sign in, they get an error about the invitation code not existing.
This makes it impossible to successfully invite people using
non-lowercased email addresses.
This patch lowercases the emails on the client side when inviting them.
Other possibilities would be to lowercase them on the server side before
storing them to mongodb, making a case insensitive search on mongodb, or
making the email input field in the sign up form not lowercase the email
string.
This patch was chosen in favor of the other …

make emails for invitations lowercase, compatible with AccountsTemplates

---

client/components/activities/activities.jade
client/components/activities/activities.js
client/components/cards/cardDetails.js
client/components/lists/list.js
client/components/sidebar/sidebarCustomFields.js
models/boards.js
models/cards.js
models/customFields.js
models/export.js
server/lib/utils.js
server/migrations.js
server/publications/boards.js

This PR:
- Modifies the customFields model to keep an array of boardIds where the customField can be used
- Adds name matching for labels when copying/moving cards between boards
This way, customFields are not lost when copying/moving a card. Particularly useful when templates have customFields or labels with specific names (not tested for templates yet).
Fix #2233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2264)

Migrate customFields model

---

client/components/lists/listBody.jade
client/components/lists/listBody.js

Few bugs/features fixed by this PR:
- #2250 -> the spinner could be shown on startup and never goes away
- the code will now only load extra cards that will be in the current viewport
- when 2 users were interacting on the same board, there was a situation where the spinner could show up on the other user, without being able to load the extra cards
The code is now much simpler, thanks to the `IntersectionObserver`, and all of this for fewer lines of code :)
Note: Apache I-CLA signed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2287)

Fix infinite scroll

---

client/components/settings/peopleBody.jade
client/components/settings/peopleBody.js
client/components/settings/peopleBody.styl
i18n/en.i18n.json
i18n/fr.i18n.json

Can now search users by username, full name or email and using regex to find them.
Display the number of users. All registered users by default else the number of users selected by the search.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2346)

Improve admin panel (peopleBody)

---

packages/wekan-oidc/oidc_server.js

Trying to configure wekan authenticating against LemonLDAP-NG, I used to read about errors like the following:
```
XXX: getUserInfo response:  { sub: 'demoone' }
XXX: userinfo: { sub: 'demoone' }
{"line":"431","file":"oauth.js","message":"Error in OAuth Server: id is not defined","time":{"$date":1556286530412},"level":"warn"}
Exception while invoking method 'login' { stack: 'ReferenceError: id is not defined\n    at Object.handleOauthRequest (packages/wekan-oidc.js:39:68)\n    at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)\n    at middleware (packages/oauth.js:203:5)\n    at packages/oauth.js:176:5',
source: 'method' }
```
Looking at the sources, that error message seems to be right: we have several references to `id`, `uid`, `displayName` or `email`, which are …

fix(oidc): can not log in

---

client/components/settings/peopleBody.jade
client/components/settings/peopleBody.js
client/components/settings/peopleBody.styl
client/components/users/userHeader.jade
client/components/users/userHeader.js
models/users.js

Now admins can remove one user. Users can also delete their account.
Check to ensure that doesn't remove the last admin of wekan.
Delete boards where the user is the last admin of these ones.
Possible need some checks to ensure that all documents in the database related to the user are removed and that feature doesn't generate errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2384)

Delete user feature

---

client/components/boards/boardBody.js
client/components/boards/boardsList.js
client/components/cards/cardDetails.js
client/components/lists/listBody.js
client/components/sidebar/sidebarArchives.jade
client/components/sidebar/sidebarArchives.js
server/publications/boards.js
server/publications/fast-render.js

**Some notes:**
1.  By this change, loading of archived items to client is deferred until the user clicks on Archive. 
2.  An infinite scrolling to Archive may also be added later to make it perfect.
3.  Search will only work for non-archived board elements at first. If the user clicks on Archive, the loading of archived elements will also be triggered. That means search will also work for archived items if the user searches after clicking on archive.
**Test steps:**
1. This step is needed to see the effect of this change. Insert bulk test data to your mongodb with a script like the following. Replace listId, boardId, swimlaneId, userId with the valid values in your mongodb database:
```
for (var i = 1; i <= 1000; i++) {
db.cards.insert( 
{
"title" : "archived card" + "-" +  i,
"members" …
```

Fixed #2338 -> Slow opening of big boards with too many archived items

---

packages/wekan-oidc/oidc_server.js

with this fix, Authentication via OAuth2 with Google is possible.
1.) token endpoint and userinfo-endpoint in Google are different, so you have to check that,
2.) request the scopes of the environment variable "process.env.OAUTH2_REQUEST_PERMISSIONS"
with this small little fix the login with google in oauth2-protocol gets possible :-)
I would be very happy about a master-merge
thank you in advance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2483)

support scopes in oauth

---

client/components/boards/boardBody.js

closes #2529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2540)

dont remove boardoverlay when mouse leaves carddetails

---

client/components/boards/boardsList.styl

As a mobile user, the board size of in the home page too small, so the user is easily to click on archive or copy button by accident. 
Increase the board size to 50% for pixel greater than 360 and lesser than 800 and height to 8rem,
100% for any screen is even smaller. 
which will reduce the accident much more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2542)

Add Features: limit the board list to 2 or 1 for mobile clients

---

client/components/boards/boardsList.js
models/boards.js

Some users don't have permissions to accept their own invites due to the `allow` code for Meteor.users only allowing admins to modify the user record: https://github.com/wekan/wekan/blob/master/models/users.js#L256
This means the user cannot modify their own record from the client-side and will get access denied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2549)

Fix invites

---

packages/wekan-ldap/package.js
packages/wekan-ldap/server/sync.js

This PR contains just my changes against wekan/master. ATM, docker build is broken so I couldn't test it, but it worked on dev. So this code basically does what it is intended to, but still registers as an ugly hack and should be reviewed by an experienced Meteor developer. Specifically, I had to use SyncedCron.SyncedCron to access said package functions due to unknown import intricacies. Therefore I think #2354 should not be closed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2555)

Makes LDAP background sync work.

---

snap-src/bin/config

To make the LDAP authentication work in our installation with group filtering, we had to set `KEY_LDAP_GROUP_FILTER_GROUP_NAME` to `ldap-group-filter-group-name`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2584)

Fixed group filtering bug

---

client/components/main/layouts.styl

attachment ctrl-v window font color became white, so became invisible.
style kbd font color became white after introduced summernote
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2600)

Bugfix: style kbd font color became white after introduced summernote

---

client/components/sidebar/sidebar.js

When the sidebar is not visible there is an error thrown when accessing the scrollHeight, this PR fixes this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2609)

fix error when the sidebar is not visible

---

package.json

I encountered the issue #2652.
I fixed it by running `meteor npm install --save @babel/runtime xss meteor-node-stubs`. This command was shown in the output of meteor command when I wanted to run Wekan on development mode.
I notice that package-lock.json file is ignored by Git. I encourage adding this file to source control in order to be able to install the exact versions of the project's dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2653)

Add missing modules

---

client/components/lists/listBody.js

On the Sandstorm platform sometimes `Meteor.user()` will not login in time, and ignoring checking nullity will make the app stop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2654)

Fix app hang when Meteor.user() is null and list spinner is loaded bug

---

client/components/boards/boardBody.js
client/components/boards/boardBody.styl

This adds basic support of colored calendar events. The color of the calendar event will match the card color.
One remark regarding the styles: there're a lot of *-$COLOR classes around the project. It might make sense to consolidate them in some kind of util function that can create classes for all available colors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2664)

add card color to calendar event (#2651)

---

server/notifications/outgoing.js

Currently, if Wekan fires a webhook, and the server responds with any status code other than "200 OK", wekan treats this as an error. This causes the change that triggered the webhook to be aborted. This is not strictly correct, as per the HTTP spec any 2xx response code should be treated as success.
More concretely, I am trying to implement a webhook handler using [OpenFaaS](https://www.openfaas.com/). If I configure Wekan to fire the webhook using the OpenFaaS [async-function route](https://docs.openfaas.com/reference/async/#how-it-works) OpenFaaS receives the webhook, queues it for processing and responds with `202 Accepted` - which Wekan treats as an error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Treat any 2xx webhook response status code as success

---

models/cards.js

Creating a card via REST API does set the user accessing the API as card member if no `members` property has passed. If no `members` where given the card should have no members assigned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2751)

REST API: fix handling of members property on card creation

---

models/cards.js

This fixes the deletion of all board cards when using the REST API to delete a single board card (wekan#2624).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2778)

REST API: fix deletion of a single board card (closes wekan#2624)

---

docker-compose.yml

I updated the info on the LDAP_BACKGROUND_SYNC_INTERVAl setting in docker-compose.yml to match the following comment by @pshunter in https://github.com/wekan/wekan/issues/2570#issuecomment-515752572
> @xet7 
> No, if LDAP_BACKGROUND_SYNC is set to true, then it checks for LDAP_BACKGROUND_SYNC_INTERVAL. If the latter is unset, then the hardcoded "every 1 hour" rule will be used. If LDAP_BACKGROUND_SYNC_INTERVAL is set, it must be set to something valid. What can be put here is explained there : http://bunkat.github.io/later/parsers.html#text
> For example, you can use "every 1 hour" or "every 20 minute". You can get very creative, like so : "at 10:15 am also at 5:15pm except on Tuesday".
Related to #2354 and #2570.
Someone with access to the wiki should also update this page: …

Fix ldap background sync documentation

---

helm/wekan/requirements.yaml
helm/wekan/templates/_helpers.tpl
helm/wekan/templates/ingress.yaml

Why:
This change addresses the need by:
1. upgrade mongo replica version
2. access mongo via service url
3. change the expose servicePort to numeric 
Signed-off-by: Jiang Yitao <jiangyt.cn@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2867)

fix: k8s templates update for helm

---

client/components/main/header.styl

before:
after:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2891)

Show System Wide Announcement in one line

---

docker-compose.yml
packages/wekan-oidc/oidc_server.js

In reference to: https://github.com/wekan/wekan/issues/1874#issuecomment-475640011
I finally got my dev environment running, applied the change and tested:
Login works, however the profile data is not being applied. Is there some sort of additional logic we need to implement in [oidc_server.js](https://github.com/wekan/wekan/blob/master/packages/wekan-oidc/oidc_server.js) similarly to ldap auth?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2897)

Implemented Nextcloud OAuth2 Hack References Issue #1874

---

i18n/en.i18n.json
models/boards.js

I believe that the ability to search not just titles and descriptions but also, at least, custom fields is a nice quality of life feature to have. So, I implemented that change. (I also think searching comments would be good, but that's for later)
I hope that you'll agree with me. 
Sorry for any possible mistakes, this is my first contribution to an open-source project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2985)

When searching cards in a board, also use custom fields

---

helm/wekan/README.md
helm/wekan/templates/route.yaml
helm/wekan/values.yaml

When I'd like to use the upstream helm chart to deploy Wekan on an Openshift v4x cluster, I need a route definition. So I added one and updated values yaml and documentation accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2996)

Route template added to helm chart

---

client/components/sidebar/sidebarFilters.jade
client/components/sidebar/sidebarFilters.js
client/lib/filter.js
i18n/en.i18n.json

Implements the filtering for assignees requested in https://github.com/wekan/wekan/issues/2995.
Works like the member filter, but filters for assignees instead.
No filter:
Filtering assignee: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2997)

Add filter option for assignee

---

models/users.js

If a board has subtasks and a user is added to it, he will only have access to the main board, and not to the subtask one. He would have to be manually invited to the subtask board.
I think the user should automatically be added to both.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3004)

When adding a user to a board that has subtasks, also add user to the subtask board

---

client/components/notifications/notificationsDrawer.styl

The header of the notification drawer had a margin to the
right side in Google Chrome caused by overflow: scroll on
the #notifications-drawer element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3012)

Fix styling issue in notifications drawer

---

client/components/boards/boardsList.jade
client/components/boards/boardsList.js
client/components/main/header.jade
client/components/main/header.styl
config/router.js
server/publications/boards.js

Added a public boards overview page #252 
Used the same components like the 'home' route with a different board query.
Please have a look on the changed boards publication.
server/publications/boards.js 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3008)

Public boards overview

---

client/components/boards/boardsList.jade
client/components/boards/boardsList.js
models/users.js

Hi, 
Board admins can not clone or archive theirs boards on the main page (Boards List) => Session.get('currentBoard') is empty here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3013)

debug isBoardAdmin on main page

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl
package-lock.json

As seen above, previously the checklist was not mobile friendly. The above gif was created using Chrome's developer tools to simulate the use of Wekan on an iPad. It is nearly impossible to check off an item. If the finger is not in exactly the correct location, instead of the item being checked off when the user taps, the input box to edit the checklist item opens.
This commit fixes that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3019)

Allows for use of checklist on mobile

---

helm/wekan/templates/deployment.yaml
helm/wekan/templates/serviceaccount.yaml
helm/wekan/values.yaml
packages/wekan-oidc/oidc_server.js

Hi,
Since Openshift 4.x userinfo is nested (just like in this [issue](https://github.com/wekan/wekan/issues/1874#issuecomment-475580905)), I couldn't make OAuth work with Openshift. 
userinfo from Openshift:
```
{
"kind": "User",
"apiVersion": "user.openshift.io/v1",
"metadata": {
"name": "testuser",
"selfLink": "/apis/user.openshift.io/v1/users/testuser",
"uid": "dbf9f6a2-547s-11ea-bcb0-0a550a820106",
"resourceVersion": "",
"creationTimestamp": ""
}
}
```
So I had to add `if (userinfo.metadata) userinfo = userinfo.metadata` 
Also updated deploymentconfig template to be able to set environment parameters during deployment and serviceaccounts template to be able to add annotations (which is required to make OAuth work), and updated values file accordingly.
---
This change is [<img …

oidc server is updated to work with OCP OAuth

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js

Clicking on the linked card will now open it (same behaviour as the icon inside the minicard).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3025)

Make linked card clickable

---

models/users.js

In case profile.startDayOfWeek is 0 it's evaluated to false and 1 is returned.
Let's fix this by differentiating between undefined and an actual value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3038)

Fix getStartDayOfWeek function

---

client/components/boards/boardBody.js
client/components/cards/cardDetails.js
client/components/cards/checklists.js
client/components/cards/minicard.jade
client/components/lists/list.js
client/components/lists/listHeader.jade
client/components/main/popup.styl
client/components/swimlanes/swimlanes.js

+ Small layout fix
+ Fix disablement of "sortable" functionality
+ (Hopefully) fix drag-and-drop and scrolling on mobile devices
See https://github.com/wekan/wekan/issues/2947
Screenshots:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3040)

[WIP] Improve mobile devices support

---

client/components/boards/boardsList.js

For now, let's reactivate the touch event fix for the boards list. This fixes https://github.com/wekan/wekan/issues/3049.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3051)

Reactivate the touch event fix for the boards list

---

client/components/main/header.styl

...even for devices with 360px width resolution.
See https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide for mobile screen resolution statistics.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3052)

Make sure that the board header buttons fit into one line

---

client/components/lists/list.styl

Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3056)

Fix list header height when cards count is shown

---

models/users.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3061)

Fix getStartDayOfWeek once again :)

---

client/lib/keyboard.js

Fix shortcuts list and support card shortcuts when hovering a card (e.g. 'SPACE' and 'c'). Any opinions about this change whether it's useful or not?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3066)

Fix shortcuts list and support card shortcuts when hovering a card

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.styl

This PR resolves #2993 issue.
Added clipboard id with white-space:normal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3075)

Add white-space:normal to copy-to-clipboard button in card details

---

client/components/cards/cardDetails.styl
client/components/users/userAvatar.styl

I noticed some profile images (if not a perfect square or circle) were rendered wrongly. With this two lines of css we can fix them. :D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3083)

avatar-image class fix

---

models/cards.js

When I create a card via the API I always have the authorId in members, even if I pass an empty string as member list. Workaround: I can empty the member list by passing an empty string in a PUT request. This pull request proposes to not add the authorId to the member list when creating a card and the member list is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3084)

Create card does not allow an empty member list

---

client/components/lists/listBody.js

when creating a new card in a new board there were and error on console. Result: card was not created. adding this parenthesis it works now.
Just for info. without this change if you want to create a card you need to change view to swimlines and go back to list view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3088)

Swimlanes ID missing in new boards

---

client/components/boards/boardColors.styl
models/boards.js
server/migrations.js

I wanted a theme which changed the color of the board's background aswell as the header. 
The theme uses transparent elements for the swim lanes and cards. The color option "clearblue" is added as an example but any desired color be created using the `setBoardClear(color1,color2)` function in **boardColors.styl**.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3093)

Added clearblue theme

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
client/lib/exportHTML.js
package-lock.json
package.json

For some reason rebasing-on-master closed #3036.
Separating the code seemed to lead to oddities. I may now have it doing what I want re-try putting the callback in lib/exportHtml.js again. (Done)
Moving the export to an iframe might be desirable in-order to preserve the page HTML and avoid many of the effects and need for page reload. TBH, for right now I'm fairly happy with the way it works.
This AM noticed card covers not being exported so added a touch-more code to get that to work. The download for a relatively simple board is now about 1MB without web-fonts, which says much about page load times on boards using lots of large frontend features.
Fixes #3026 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Feature export to html wip

---

client/components/rules/actions/boardActions.js

This is the same default as `Utils.getTriggerActionDesc` has. This commit fixes
https://github.com/wekan/wekan/issues/3107.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3109)

Set '*' as default value for swimlane and list name in card move action

---

models/csvCreator.js
models/exporter.js

Resolves https://github.com/wekan/wekan/issues/395
Added ability to import and export custom fields on the board via CSV/TSV, set the values of the custom fields on a card with data while importing and similarly export the data on the custom fields on cards which have them. Each custom field will have its own column in the csv/tsv, with the header describing the custom field.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3115)

enable exporting and importing custom fields.

---

models/cards.js

The default has to be a numeric value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3122)

Fix default value of `sort`

---

openshift/wekan.yml

* Remove status fields (this is created by Kubernetes at run time)
* The latest MongoDB by [default available with OpenShift is 3.6](https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-rhel7.json#L334)
* Change MongoDB service name to contain wekan to avoid potentially conflicting with other mongodb instances in the same project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3158)

OpenShift template updates

---

client/components/swimlanes/swimlanes.js

This fixes the issues https://github.com/wekan/wekan/issues/3164,
https://github.com/wekan/wekan/issues/3162, and
https://github.com/wekan/wekan/issues/3163. While at it, remove now useless
comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3165)

Fix condition whether a card is in list

---

client/components/activities/activities.js

This fixes the error:
Uncaught TypeError: activitiesComponent.loadNextPage is not a function
at constructor.reachNextPeak (sidebar.js:63)
at constructor.BlazeComponent.callFirstWith (peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:660)
at constructor.scroll (infiniteScrolling.js:28)
at peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:469
at Object.Blaze._withCurrentView (view.js:533)
at peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:468
at Template._withTemplateInstanceFunc (template.js:490)
at Blaze.View.eventMap.<computed> (peerlibrary_blaze-components.js?hash=4049f7e3116e3d9e865392b9546e70dc479b9add:467)
at view.js:879
at Object.Blaze._withCurrentView (view.js:533)
---
This change is [<img …

Fix infinite scrolling for activities

---

client/components/cards/checklists.styl

Remove top and bottom margin for hidden checklist items, otherwise there could
be a gap between unchecked items if multiple hidden/checked items were between
them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3172)

Remove top and bottom margin for hidden checklist items

---

client/components/cards/minicard.styl

Change alignment and spacing of tag labels for cards when "Hide minicard label text" is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3174)

Alignment and spacing of minicard labels

---

models/cards.js
openapi/generate_openapi.py

The script was considering that the operation associated to a jsdoc was declared on the line
just after the end of the jsdoc.
Turns out that adding new lines makes the code clearer, but the python script was then ignoring
some jsdocs.
Change the behaviour to consider that the jsdoc associated with an operation is the last one
declared after the end of the previous operation.
Fixes #3169
Note: I was able to check on the proper generation of the openapi definition, but not on the html generation (got a new setup and couldn't really get the npm part of the generation working).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3171)

openapi: fix jsdoc/operation matching

---

client/components/activities/activities.js

Turns out that the sidebar is not available on mobile device therefore add
guards for this for now. This needs further investigation.
Fixes https://github.com/wekan/wekan/issues/3182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3183)

Fix activities view on mobile devices

---

models/checklistItems.js

With this PR I fix a BUG that prevents any update on isFinished flag of a checklist item via API.
I simply copied the isTrue() function from others API as It should work fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3211)

Checklist Item PUT API: boolean cast on isFinished

---

models/boards.js

If the title of a board is changed the slug will be changed too.
I wanted to change the client URL after an update of the slug but didn't know how to route to the new slug url...
Fixes #200
Fixes #2516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3214)

Change slug on card rename

---

package.json

https://github.com/mongodb/node-mongodb-native/releases
Unfortunately this doesn't bump the transient dependency on `mongodb` of `gridfs-stream`, see: https://github.com/aheckmann/gridfs-stream/pull/150 :confused: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3268)

bump: mongodb -> 3.6.2

---

client/components/cards/cardDetails.jade

this fix also hides the move to another board functionality in the
submenu (only from the worker) so that the worker is still constrained
to a single board.
see issue #3314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3315)

fix: expose moving cards on mobile to workers

---

client/components/cards/cardDetails.js

@xet7 
sorry about the second PR...
My previous change that revealed the move card menu functionality to a worker was broken because the worker didn't have a board select from which to retrieve the `boardId`... this fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3323)

fix: use current boardId when a worker moves a card

---

packages/wekan-oidc/oidc_server.js

FYI, this commit is based on the following:
[wekan-oidc.js.txt](https://github.com/wekan/wekan/files/5471644/wekan-oidc.js.txt)
File above was tested against a 4.46. LemonLDAP-NG as Oauth2 server, certificate signed by a custom CA.
The `OAUTH2_CA_CERT` env var may be set, pointing to a CA file. If unset, the default would be to use NodeJS default trust store.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3325)

fix(oidc): wekan/wekan#3299

---

packages/wekan-ldap/server/sync.js

The periodic sync cron currently only syncs the username and full name from LDAP. With this change. the email address is synced as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3329)

ldap: sync email address

---

client/components/main/editor.js
packages/markdown/src/template-integration.js

Addressing feature: Custom URL Schemes autolinked #3218
Create a custom SafeAttrValue function which can allow non-standard protocols such as thunderlink: cbthunderlink: and aodroplink: to operate correctly without getting the value stripped away. Any other protocols and code remain to be processed by the default safeAttrValue routine.
See https://github.com/leizongmin/js-xss/issues/52#issuecomment-241354114 for documented process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3339)

Custom URL Schemes autolinked #3218 

---

client/components/main/layouts.styl

Hi again,
I'm adding some padding to the bottom of the list (ul & ol), much better, see results below!
Before:
After (result):
I hope you like it as well!
Regards,
Melroy van den Berg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3351)

Missing bottom padding on lists

---

client/components/swimlanes/swimlanes.styl

Please merge this pull request for my mental sanity :)
Now the swimlane header is sticky and is fixed if the page scroll vertically
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3370)

sticky swimlane

---

helm/wekan/Chart.yaml
helm/wekan/templates/deployment.yaml
helm/wekan/values.yaml

As lined out in #3381 this change allows to introduce environment variables from a second (possibly secret) source without lists being replaced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3382)

Helm: Introduce secretEnv for secret value provisioning

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl

Add drag handles for checklist items.
At desktop version with enabled drag handles it works fine at checklist items, but in mobile view i get an javascript error in the file mquandalle_jquery-ui-drag-drop-sort.js
Does anyone have an idea about the error at mobile view? Is it an error at the third-party library or an error at jade / html ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3342)

Drag handle checklistitem

---

client/components/cards/minicard.jade
client/components/cards/minicard.styl

I saw that there is a lot of space after the assignees label on the minicard if an assignee is set.
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3385)

Minicard, reduce space after assignees label

---

models/import.js
models/wekanCreator.js

Fixes the following issues when cloning/importing a board as listed in #3336 :
- Custom fields missing in board and on cards
- Member assignments missing on cards
- Assignee assignments missing on cards
- Subtask/Parent task missing on cards
- Note: this only fixes scenarios that are possible with the current subtask structure:
- Cloning boards within the same instance 
- Importing a backup into the same instance
- Importing boards where parent and child task board are the same
- That means, if you have a separate parent and child task board and you import them, the connection between parent and subtask will be lost. There is no way around this the way the importer and subtasks currently work, because card IDs change once the first board is imported, and there is no (good) way to map once …

Fix issues when duplicating board

---

models/wekanCreator.js

Closes #3388
`createChecklistItems` now skips the import of "dangling" checklist items that belong to an already deleted checklist.
Before it would crash when hitting a parentless checklist item, and therefore all further checklist items would not be imported
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3389)

Fix not all checklist items being imported/cloned

---

models/wekanCreator.js

Fixes missing attachments and comments when importing/cloning a board that contains attachments without mime type (e.g. Java .class files and presumably other binary files).
Fixes the issue described in https://github.com/wekan/wekan/issues/3336#issuecomment-746273612
Note regarding #3336: there might be additional issues with comments that are unrelated to attachments, I will provide a separate PR if reporter @lezioul finds further errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3395)

Treat unknown attachment types as binary on board import/clone

---

client/components/boards/boardColors.styl

Steps to find problem:
1) Switch to Dark theme.
2) Click on Multi-Selection
3) Note that the "Move Selection" and "Move Selection to Archive" buttons are unreadable until you hover over them.
This small change will make the buttons readable while preserving the visual hover behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3401)

Dark theme button background fix

---

client/components/cards/checklists.js

- obsolete since commit c7808c5c03f98eae709e5ef89e8e17af4689cb2e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3405)

Checklist Mini-Screen, appendTo: 'parent' not necessary anymore

---

client/components/cards/checklists.jade
client/components/cards/checklists.styl

- Drag handle is not visible at long checklists, even with:
padding-right: 20px
Depending of all the screen sizes out there this is the most secure
way to get around this and the drag handle is always visible
- first fix was at this commit: a8453657c95a4bde2ae86b4c77e55bb2174adf26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3407)

Checklist-Items, Drag-Drop Handle now at the left side

---

client/components/cards/checklists.js

If the checklistitem is edited, the textarea auto-resize vertically to the user-input at focus and input event
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3408)

Checklist-Items, Autoresize the textarea vertically to fit the user-input

---

client/components/swimlanes/swimlaneHeader.jade
client/components/swimlanes/swimlanes.styl

Suggestion of @xet7 at this comment:
https://github.com/wekan/wekan/issues/3402#issuecomment-751704203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3412)

Swimlane + and = Icons resized for better handling at mobile view

---

models/cards.js

- until now the order is undefined, it's different from card to card,
it's the order in which the custom fields were added to the card.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3417)

Cards, custom fields are displayed in alphabetic order

---

Dockerfile
docker-compose.yml

I've re-written the Dockerfile to use the NodeJS base image and multi-stages to simplify the build-run process as well as removing all of the comments and commented-out old code.
I've done some brief benchmarking of the new Dockerfile compared to the old one (based on v4.79).
```
New build time: 6 minutes 55 seconds
Old build time: 8 minutes 32 seconds
New image size: 515MB
Old image size: 644MB.
```
It would be good to reduce the number of environment variables in the Dockerfile too but I didn't want to risk breaking things.
Closes #2762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3438)

Use multi stage build based on Node images

---

models/boards.js

Custom field definitions are not currently copied when copying a board.
This patch copies the custom field definitions for the new board and updates the cards to use the new definitions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3451)

Copy custom fields to new board

---

client/components/boards/boardsList.js
client/components/lists/listBody.js
models/boards.js
server/publications/boards.js

Fix for issue #2924
* Added logic to copy rules, triggers and actions to `Boards.copy()`
* Created new Meteor method `copyBoard` server-side
* Changed the duplicate board code to call `copyBoard` instead of `cloneBoard`
* Added new method `Boards.copyTitle()` to create unique names for duplicated boards.
NOTE:
* The line `delete this.slug;` was added to `Boards.copy()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3458)

Issue 2924: Rules not copied during board copy

---

client/components/main/globalSearch.js

Fix problem with translated operators not working in the URL (#2074)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3478)

Move call to URL search to onRendered

---

packages/wekan-ldap/server/ldap.js

For example Podman, handling OCI containers, does not seem to have a way to pass multi-line strings via env files (and Docker seems to have the same issue at least outside of `docker-compose`). Thus this change allows `LDAP_CA_CERT` to handle a string with `\n`, because currently only `0x0A` aka `LF` might work. An example for additionally supported format:
```
LDAP_CA_CERT=-----BEGIN CERTIFICATE-----\n...\n...\n...\n-----END CERTIFICATE-----
```
See also: https://github.com/wekan/wekan/issues/3484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3485)

Handle '\n' line breaks in PEM-encoded SSL/TLS certificates

---

packages/wekan-ldap/server/ldap.js

Previous commit 31f89121fecca5a761b05cc3a26d4f237e90b484 happened to fix CVE-2021-3309, but unfortunately breaks `LDAP_REJECT_UNAUTHORIZED=false`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3497)

Repair LDAP_REJECT_UNAUTHORIZED=false (broken by commit 31f8912, fixes #3493)

---

models/cards.js

- last fix didn't work and disabled alphabetic sorting
- also works with linked cards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3521)

Cards, CustomFields sorted alphabetically, fixes #3517

---

client/components/boards/boardArchive.js
client/components/sidebar/sidebarArchives.jade
client/components/sidebar/sidebarArchives.js
i18n/en.i18n.json
models/boards.js
models/cards.js
models/lists.js
models/swimlanes.js

Added sorting to archives. Please review carefully as I don’t read JavaScript, Jade, or Meteor, so I had to rely on try-and-error and pattern reuse.
I particular, I was unable to add the `archivedAt` field to the list of archived boards.  Whatever I tried, I could only display the `title` of the board in the list of archived boards. Another problem is that I could not capitalise the first letter of “archived at”. Of course, one could use “Archived at” in `en.i18n.json` – but this is not as re-usable.
The new field `archivedAt` is necessary because `modifiedAt` of an archived object may change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3518)

Sorted archives

---

client/components/users/userHeader.js

When the `TAPi18n` initialization code was removed from an `autorun()`
it no longer is rerun when a user's profile language is changed.
Fixes bug introduced by pull request #3519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3525)

Set the language on `TAPi18n` when user selects language

---

models/boards.js

`uniqueTitle` was returning a numbered title even when not necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3526)

Fix bug in `uniqueTitle`

---

client/components/settings/peopleBody.js

New `importUsernames` was not being parsed into an array before
calling `setCreateUser()`
Issue #3539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3544)

Fix bug in adding new users #3539

---

client/components/cards/checklists.js
models/checklists.js

The number before the checkbox is the internal sorting number, it's not included in the commit
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3551)

Checklistitems are now inserted always at the end of the checklist

---

models/boards.js
public/api/wekan.html
public/api/wekan.yml

As discussed in #3535, this is a proposition to add an `/api/boards_count`  API endpoint that can return the number of private and public boards on the server, for statistics purpose.
This is my first contribution to Wekan so please let me now if something is missing or wrong and I'll correct :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3556)

Add /api/boards_count endpoint for statistics

---

models/activities.js

Previously, all changes to due dates notified all board members.  Now, you have
to set the environment variable BIGEVENTS_PATTERN explicitly to "due" to
restore this behaviour.  By default, no activity is considered a "big event".
Fixes <https://github.com/wekan/wekan/issues/3133>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3561)

Changed default behaviour for BIGEVENTS that no activity matches it.

---

client/components/lists/list.styl

It's now the same behaviour as at desktop view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3563)

Mobile View, list header is now always at top and only lists/cards view have a scroll area

---

client/components/cards/checklists.styl

- most people scroll with their right thumb, so it happens sometimes
that they move whole checklists by accident.
- this fixes the problem, and also it looks more clean than a drag
handle in the middle of the screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3571)

Checklist drag handle now at the left side (same place as for the checklist items)

---

docker-compose.yml
models/activities.js
models/cards.js
server/notifications/outgoing.js

Fixed bug with the reference to the customFieldValue in the cards.js
Activity Insert was not being passed the listId, swimlaneId which was required when building the webhook text string.
Added customField and customFieldValue as default values for the webhook msgs. There is no good reason to exclude these (they will only be included when changing a customField anyway). Updated the docker-compose comment to reflect this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3584)

Fix bugs with customFields identified in Issue #3574

---

server/publications/cards.js

Fix issue described in #3587 where searching on label names generated a server error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3634)

Fix search on labels server error

---

client/components/activities/activities.jade
client/components/activities/activities.js
client/components/cards/cardDetails.jade
client/components/cards/resultCard.jade
client/components/lists/listBody.jade
client/components/main/myCards.jade
client/components/sidebar/sidebarSearches.jade
models/boards.js
models/cards.js
models/lists.js

Some pages use relative links such as boards link at the home page.
Others use absolute url such as cards in boards' lists.
This commits goal is to allow for consistent use of relative
urls.
Origin relative URLs also helps decoupling Wekan from the infrastructure
it's deployed on. i.e if it's being served, it should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3635)

Fixed Bug: inconsistent use of relative/absolute URLs

---

packages/markdown/src/template-integration.js

autolinking is not working for abasurl as it contains not url conform characters so you would still have to link it manually but it is not sanitized anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3641)

change url scheme recognition for allowing abasurl to link

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js

This will use the current URL to copy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3661)

Fixed Bug: copy to clipboard uses pathname

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js

- Fixed Sort Cards Feature #3647 
- Added a button to clear/reset sort
- Sorting is reset to default when switching to other boards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3662)

Fixed sort cards feature

---

i18n/en.i18n.json
models/trelloCreator.js

This patch adds links attached to Trello cards to the Wekan card's description during import.
Previously, I explored adding the link as an attachment in Wekan.  But there is no file data to store with a link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3669)

Add Trello attached links to the card description

---

Dockerfile.arm64v8

The previous arm Dockerfile used an outdated version number of wekan that was causing the building of the docker image to fail.  This PR updates to a version of wekan that is actually hosted here:
https://releases.wekan.team/raspi3
3.96 is a broken link, 5.17 exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3692)

Updating ARM Dockerfile

---

client/components/cards/cardCustomFields.jade
client/components/cards/cardCustomFields.js
client/components/cards/minicard.jade
client/components/cards/minicard.js
client/components/sidebar/sidebarCustomFields.jade
client/components/sidebar/sidebarCustomFields.js
i18n/en.i18n.json
models/cards.js
models/customFields.js

This PR implements a new custom field of type "stringtemplate".
It allows the user to add a string template containing a placeholder "%{value}" which will then be replaced by the card's field value.
I want to use this in combination with abas ERP, where you can directly open windows from the browser by using the custom URL scheme abasurl. For showing the data of the part with the part number 123456 the url would be `abasurl:<(Part)>123456<(View)>?DDE=001`. As the command is rather complex, it is quite tedious to write this link and I cannot imagine, that my users are able to write such a link by hand. So I will change the current custom field of type text to a new custom field of type stringtemplate, where the format is `[%{value}](abasurl:<(Part)>%{value}<(View)>?DDE=001)`, so that the …

Add custom field "stringtemplate"

---

client/components/activities/comments.js
client/components/cards/cardDescription.js

This popover appears in the Description and the comment section.
I am still concerned that this change is required... But I do not understand what is happening as I am not a javascript/web developer
`noClickEscapeOn: ['.js-new-comment','.js-new-comment-form']`
as currently the line is 
`noClickEscapeOn: '.js-new-comment',`
edit: This is the linked issue https://github.com/wekan/wekan/issues/3399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3712)

popover needs to be destroyed anytime the details panel is closed.

---

openapi/generate_openapi.py
public/api/wekan.yml

Previously I was assuming all variables were declared in the same file.
Turns out that imports exists too, and we need to recurse one more time
in those imports./
Also "clean" up a bit the function to do the parsing in 2 steps:
- first find out the actual matching node in js
- then convert it based on its type
rinse wash repeat.
Fixes #3713
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3715)

openapi: rework the allowedValues to allow for imported variables

---

client/components/cards/cardDate.js

One minute earlier than the current time is almost-due? This should be a faulty logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3749)

Fix: The bg color of start at button is almost-due

---

openapi/generate_openapi.py
public/api/wekan.yml

While working on #3757, I realized that the generated openapi was not correct:
There is a 2 levels schemas in profile.notifications.
The code previously assumed we could only have one level, and so was not producing the correct UsersProfileNotifications.
Fix that by being more generic in the way we retrieve the nested subschemas.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3762)

openapi: better handle nested schemas

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/minicard.jade
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
i18n/en.i18n.json
models/boards.js

- The card sort number is now shown at the Minicard and the card itself.
- Also the sort number is changeable at the card
- By default the sort number is not shown to be backward compatible. It have to be enabled at the card settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3857)

View and change card sort number

---

.babelrc
.github/workflows/test_suite.yml
.gitignore
.meteor/packages
.meteor/versions
client/lib/tests/Utils.tests.js
client/lib/tests/index.js
client/lib/utils.js
package-lock.json
package.json
server/lib/utils.tests.js
test-wekan.sh
tests/main.js

This PR adds a complete functional testsuite, consiting of the following:
- mocha as test runner (via `meteortesting:mocha`)
- chai as asserter
- sinon for stubbing
- puppeteer as headless browser to run client tests in terminal and ci
- nyc/istanbul for coverage (via `lmieulet:meteor-coverage`)
- CI tests via GithubActions
- script `test-wekan.sh` to run test with some flags (`-c` = coverage, `-v` = verbode, `-w` = watch mode)
There are some example tests added.
To run the tests use the `test-wekan.sh` script. Note, that in the github actions you need to increase the minimal required coverage to a value that reflects a "good" test coverage (I think >= 85 is pretty good). For now there is only a low coverage, because we have not added many tests yet.
Adding tests is quite easy - just …

Add testsuite

---

openapi/generate_openapi.py

39f8a138d7ba added a try/except around esprima to catch any hard error from the parsing, but the returned value was not checked.
We now have the file models/exportExcel.js which gives us an unexpected symbol on line 3 (not sure why it is not happy), but that fails the generation of the doc entirely.
Fixes #3884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3889)

openapi: actually catch the error when esprima fails at parsing the file

---

client/components/cards/cardDetails.js
client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl
i18n/en.i18n.json

This PR resolves #2565 introduces "Convert checklist item to card" feature.
Unlike Trello, in this feature is possible to select Board, Swimlane and List to create a card.
It is also not possible to delete checklist item automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3910)

Add Convert checklist item to card feature

---

client/components/boards/boardsList.js
server/publications/boards.js
server/publications/users.js

Organizations and teams are taken into account when displaying board in « All boards page », it means that If the current user is one of the board members or if one of the teams or organizations to which he belongs has been configured to have access to this board, then this board will be displayed in « all boards page ».
The point 2 of this comment « https://github.com/wekan/wekan/issues/802#issuecomment-870738124 » is not done yet, i’m working on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3912)

Organizations and teams are taken into account when displaying board in « All boards page »

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.styl
client/components/cards/minicard.jade
client/components/cards/minicard.styl
client/components/lists/listBody.js
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
models/boards.js
models/cards.js
server/migrations.js

Hey @xet7,
first of all thanks for maintaining wekan!
We have been using wekan some time now in our company as a Trello alternative and we came across this [feature-request](https://github.com/wekan/wekan/issues/1473) as we also need to keep track of the cards.
This Pull Request adds this feature to wekan in the following way:
- it assigns a boardwise consecutive `cardNumber` to each card via a migration-script to ensure backward-compatibility
- it further assigns the nextCardNumber whenever a new card is created either through the rest-endpoint or websocket
- Through the card-settings it is possible to enable or disable the appearance of the cardNumber per board. The migration script sets this config to `false` initially
- If enabled the card-number is shown on the mini-card as well as …

Feature: Consecutive boardwise card numbering

---

models/boards.js
models/cards.js

Hey @xet7 and @mfilser ,
because of @mfilser very good remarks on my previous [PR](https://github.com/wekan/wekan/pull/3935) regarding the consecutive boardwise card numbering i submit another PR that includes the following fixes:
- If a card is moved to **another** board it, the card will receive the next card number from the target board. 
- If a card is copied to the same or another board, it will always receive the next card number from the target board
This PR also includes enhancements for `Boards.getNextCardNumber()`. It basically works now the following way:
1. return `1`, If no card is assigned to the board, 
2. return `1`, If the board has cards where **none** of the cards have the attribute `cardNumber` (this should never happen due to the migration-script …

Fix: Consecutive Card numbering when a card is moved to another board or copied

---

client/components/main/layouts.styl

Hey,
this PR fixes issue [#3866](https://github.com/wekan/wekan/issues/3866) which states that the user mentioning does not work when used in maximized card layout.
this is due to the z-index of `.card-details-maximized` in `cardDetails.styl` that is set to `1000` which overrules the default z-index of `.textcomplete-dropdown` that is set to `100`.
This PR sets the z-index to `2000` to have the autocomplete component always on top.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3939)

Fix: Show missing user mentions popover when posting comments in maximized card layout

---

client/components/settings/peopleBody.js

Hey @xet7,
this PR fixes Issue https://github.com/wekan/wekan/issues/3911
Seems this comes from the org and team arrays that include partial objects for newly created users and the arrays do not pass user schema validation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3946)

Fix: Save user initials and fullname when a new user is created

---

models/users.js

When setting up a new deploy and registering the first user via OIDC no profile information would be populated. This also prevented updating profile information as the client would error when encountering a null email value. I manually tested this change against the OIDC use case, but, not others. This fix should address #2444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3994)

Fix first user creation for via OIDC

---

server/rulesHelper.js

e.g. card title filter 'Foo' will now match both cards named 'Foo', 'Foo bar' and "Foo: bar"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4025)

Feature: allow word match for rules -> title filter

---

Dockerfile

This drastically reduces docker image size from ~280 MB to ~180 MB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4026)

Fix: clean up /tmp after Docker build

---

helm/wekan/templates/deployment.yaml
helm/wekan/values.yaml

This adds two helm values to the helm chart, for setting custom kubernetes labels on the `Deployment` object, and on the `Pod`s created by the deployment.
We need this when using the backup system velero, to specify which components need to be restored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4031)

Allow setting custom kubernetes labels when using the helm chart

---

client/components/cards/minicard.jade
client/components/cards/minicard.styl

Fixes: https://github.com/wekan/wekan/pull/4073#pullrequestreview-793677680
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4109)

Card labels on minicard withouth text are now at the same line again

---

client/components/cards/cardDetails.jade

Add missing hr line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4117)

Card Details, add missing hr line (before Activity title)

---

client/components/cards/cardDetails.styl
client/components/cards/checklists.js
client/components/cards/checklists.styl

- old checklist and checklist-items form closes if new checklist/checklist-items are added
- checklist and checklist-items drag/drop scrolls now the view at mobile view
- checklist and checklist-items plus button has now a bigger "area" to click
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4140)

Checklist and items drag drop scrollable mobile view

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.styl
i18n/en.i18n.json

Form layout "Adding organisations to a board"  improvement, to match layout of [Adding team to the board] form.
(commit f840d26)
Was:
Proposed:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4143)

[Adding organisations to the board] Layout improvement

---

client/lib/inlinedform.js

- before whitespaces were only trimmed if 2 or more whitespaces were at
the end of the line
- now every whitespace is trimmed at the end of each line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4146)

Fixed trim whitespace at multiline editor fields

---

client/components/main/header.jade
client/components/main/header.js
i18n/en.i18n.json

Especially on mobile devices after "display on" it takes sometimes a long time to reconnect or in the worst case the app doesn't reconnect, so the user has the chance to manually try to reconnect the wekan app so unsaved edits are tranfered to the server without data lost.
See this screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4147)

App reconnect is now possible if the connection was interrupted

---

client/components/lists/list.styl

Before
:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4148)

Fixed placeholder was not visible at list view (mobile view)

---

client/components/swimlanes/swimlanes.js
models/boards.js

- adding a list at mobile view had always the sort number 1
- use Utils.calculateIndexData for getting the sort number to ensure sorting is always right
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4152)

Fix list adding to bottom

---

client/lib/multiSelection.js

this patch changes the open/close behavior of the sidebar when
activating and deactiviting the multi selection.
in the past activating the multi selection on a mini screen will hide
the cards and show the multi selection sidebar on the whole screen. a
user would need to hide the sidebar in order to select multiple
cards. this patch changes this behavior. the sidebar will no longer be
opened if the user is on a mini screen while activating the multi
selection.
in the past deactivating the multi selection would show the default
sidebar instead of the multi selection sidebar. after this patch the
default sidebar will only be shown if the sidebar was visible before
activating the multi selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

improve multi selection sidebar opening and closing

---

client/components/cards/labels.styl

Happens at Firefox zoom level 90%, probably on Windows...
Fixes: https://github.com/wekan/wekan/pull/4073#issuecomment-971563178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4157)

Fix label width oversize bug

---

client/components/cards/minicard.jade
client/components/cards/minicard.js

On minicard "Assignee" and/or "Members" could be displayed or hidden like "Creator".
See #4177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4179)

Show or hide members and assignee(s) on minicard

---

client/components/lists/list.styl
client/components/swimlanes/swimlanes.js

- listBody.js:755 doesn't trigger an event when scrolling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4187)

Fix: On mobile infinite scrolling didn't work

---

client/components/cards/cardCustomFields.js

happend when adding a value and clicking the save button without to hit "Enter" before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4188)

Custom Field StringTemplates didn't save the last input value on touch devices

---

client/components/cards/cardDetails.js

The problem is, if a filter is set and the card should be moved to e.g. the top though the "hambuger menu" in the card details, the card isn't at the top after removing the filter. Now the card is at top, regardless of a filter or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4192)

Move cards to top/bottom ignores the current filter if active

---

client/components/boards/boardColors.styl
client/components/lists/list.styl
client/components/lists/listHeader.jade
client/components/lists/listHeader.js

adding a button to add cards at the bottom of the list.
Here is a screenshot (see green marker)
I haven't found a better icon on https://fontawesome.com/icons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4195)

List header contains now a button to add the card to the bottom of the list

---

client/components/main/layouts.jade
client/components/main/layouts.js

Fix legal notice traduction bug : 
When refreshing sign in page legal notice line was always in english even if a given language isn't english (see image below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4217)

Fix legal notice traduction bug when refreshing sign in page

---

client/components/boards/boardsList.js
client/components/settings/peopleBody.js
client/components/sidebar/sidebar.js
models/org.js
models/team.js
models/users.js

See  #4231
At Admin Panel: 
- sort Organizations by orgDisplayName
- sort Teams by teamDisplayName
- sort People (users) by username
All boards view:
- sort Organizations by orgDisplayName
- sort Teams by teamDisplayName
Board view:
- At addBoardOrgPopup: sort Organizations by orgDisplayName
- At addBoardTeamPopup sort Teams by teamDisplayName
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4232)

Sort Organizations, Teams and People

---

client/components/lists/listBody.js

Fix getLabels exception in template helper when board has no labels
Fix getLabels error when boards.labels.name doesn't exists
(refers to https://github.com/wekan/wekan/pull/342 and https://github.com/wekan/wekan/commit/5d77ad4f6ba70038486d734e97844c547e664e88)

Fix getLabels exception in template helper

---

client/components/cards/cardDetails.js

Global search: Card Details popup opens now in normal view even if maximized card is configured

---

client/components/main/header.js

Problem: System wide announcements are not shown to regular users (also mentioned in #4355). They are only shown when an admin has opened the admin panel beforehand. In that case `Meteor.subscribe('announcements');` is executed in "client/components/settings/settingBody.js". So the problem seems to be that the announcements collection is not being subscribed otherwise.

add subscription to announcements collection

---

packages/wekan-oidc/loginHandler.js
packages/wekan-oidc/oidc_server.js
packages/wekan-oidc/package.js

If some OIDC provider (e.g.authentik) is used, user data changed in oidc provider is propagated to wekan and mongodb updated accordingly.
E.g. in authentik it is possible to assign users to "groups". On next login these groups (as far as they exist in wekan) will be added as teams relation to the user object.
____________________________________________
Changes include:
**Email** changes via oidc have not been reflected before. --> Now supported
**Fullname** changes via oidc have not been reflected. --> Now supported
**(first) Email** changes via oidc have not been reflected. --> Now supported
**Group assignment** in oidc assigns to **Teams** in wekan on next login. Key is Team Name. Be careful not to use the same Team Name (mongo: teamDisplayName) twice.
You have to set:
export …

Feature/propagate OIDC data

---

client/components/activities/activities.jade
client/components/activities/activities.js
models/boards.js
server/publications/activities.js
server/publications/boards.js

For people who use "Big Board", 
This feature allows to display the Activities of linkedBoards in sideBar.

Add linkedBoard Activities to sidebar

---

models/boards.js

fix Boards.uniqueTitle not working as expected #4400

---

client/components/cards/attachments.jade
client/components/cards/minicard.jade
models/attachments.js
server/migrations.js
server/publications/cards.js

Attachments fixes after migration to meteor files (image preview, global search)
- global search was broken
- image preview is back again
- wrong mongo index was created
- attachment count on minicard was missing
should also fix: #4395

Attachments fixes after migration to meteor files (image preview, global search)

---

server/migrations.js

- should fix: https://github.com/wekan/wekan/issues/4407#issuecomment-1065782781

Attachment migration, try to ignore error on Cloudron on removing old index cardId

---

packages/wekan-oidc/oidc_server.js

Currently wekan produces an internal server on oidc logins when no group list is present in the response. This fix checks that `serviceData.groups` is actually an array with a non-zero length before accessing the first element.

Fix oidc login when no group data is present

---

client/components/boards/boardsList.jade
client/components/boards/boardsList.js
client/components/boards/boardsList.styl
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
i18n/en.i18n.json
models/boards.js
server/migrations.js

Hi @xet7 
This PR implements on My Boards:
- Card count per list
- Members list
For each board it's possible enable/disable show these info on My Boards
On sidebar:
-> "Board Settings" -> "Board info on My Boards" 
I did not find a way to change popup header:
Do you know how to fix it?
Thanks!

Added members list and board card count per list on My Boards

---

.github/workflows/codeql-analysis.yml
.github/workflows/dockerimage.yml
.github/workflows/release.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

client/components/cards/cardDetails.js
models/cards.js

Moving and copy cards to lists didn't set the sorting, therefore the card was anywhere in the new list.
Now, set the card sorting to the lowest number, therefore the card is always visible

Move and copy card set sorting

---

client/components/swimlanes/swimlanes.js

As i mentioned in this comment "https://github.com/wekan/wekan/issues/4572#issuecomment-1198373626",
I fixed the bug that displayed a card popup to all swimlanes for public board (when a user is not logged)

Fix the bug that displayed a card popup to all swimlanes for public board (when a user is not logged)

---

client/components/boards/boardBody.css
client/components/lists/list.css
client/components/swimlanes/swimlanes.css
client/lib/utils.js

changed miniscreen width to 250px, on Android Firefox works like a charm, still many templates to fix, like header - where "All boards" shortcut must hide it's text (css are working with max-width = 800px).
From boardBody.css removed the line where the Plus sign is deleted from all lists on card dragging, it was shrinking lists to 0 making them unable to receive the moved card (the glitch when the card cannot be dropped on another swimlane), either this or we should add a minimum height to the list.

set miniscreen to 250px

---

Dockerfile
docker-compose.yml

Removed hardcoding port 8080 in image, allowing more flexibility for complex docker deployments.
Forcing use of port 8080 invalidates various pieces of documentation claiming you can connect to Wekan on other ports like 3001 (see [here](https://github.com/wekan/wekan/wiki/Settings#webserver-config)and [here](https://github.com/wekan/wekan/wiki/Caddy-Webserver-Config#caddy-2)), but it also creates unnecessary rigidity in more complex Docker deployments.
For example in my environment (and the reason for this PR), I don't want to expose containers directly to the underlying host network stack, so I run Caddy as my single host-connected container. I want my Wekan container to connect directly to the Caddy bridge network I've created, but when I set `ports: 8081/tcp` in my wekan …

Remove hard-coded port 8080 binding in Dockerfile

---

Dockerfile

The process 1 in the container does not shut down gracefully after having
received a TERM signal.  Therefore, we send a SIGKILL immediately.  This is a
kludge as long as node/meteor has no proper SIGTERM handler enabled.  See
<https://github.com/wekan/wekan/issues/4668>.

Avoid non-terminating containers

---

client/components/cards/cardCustomFields.js
client/components/cards/minicard.js
client/lib/customFields.js

Idea from PR:
https://github.com/wekan/wekan/issues/3701#issuecomment-815864735
---
the regexp syntax is e.g.:
${regex:".(.*).", replace:"$1", flags:"i"}
removes the first and last character and uses case-insensitive search.
See also:
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/RegExp

RegExp possible at "Custom Field String Templates"

---

client/lib/dialogWithBoardSwimlaneListCard.js

- a Exception was thrown the return value was an object because #each only accepts arrays and cursors
See also:
https://github.com/wekan/wekan/issues/4655#issuecomment-1250106151

Checklist copy/move dialog was sometimes empty

---

releases/rebuild-docs.sh

Sigh, python-esprima is really not well maintained:
- the maintainer merged https://github.com/Kronuz/esprima-python/pull/19
- this breaks entirely his project
- the submitter of PR 19 submitted a fix one week later
- 10 months later, the fix is still not merged :(
Pull it locally so we get our docs building again.
Fixes: #4731

Fix Python-Esprima upstream failing

---

packages/wekan-ldap/server/ldap.js

Since this is not exported by the upstream module, a copy was made.

Provide a copy of escapedToHex() from ldapjs

---

client/components/rules/actions/boardActions.jade
client/components/rules/actions/boardActions.js
imports/i18n/data/en.i18n.json
server/rulesHelper.js

I have added a new feature to the board rules: linking of cards to another board
There is a new action that will allow you to create a linked card on baord as part of a rule. You can specify the target board, swimlane and list.
Remarks:
- if given list is empty or not existing, the rule will fail (similar behaviour to createCard rule)
- I could also provide code that would add the link to the first list of the target board
Let me know if I missed out something. This is my first pull request to a public project.

Add link card feature to rules

---

packages/wekan-accounts-lockout/src/knownUser.js
packages/wekan-oidc/oidc_server.js

Fixes Group Assignment on OIDC Login. 
wekan-accounts-lockout did not start group routine since "onLogin" hook was not called.
Logic moved to wekan-oidc package
Refer to Readme.md in packages/wekan-accounts-oidc/README.md for detailed description on how to use this feature.

4786 fix group routine

---

docker-compose.yml

Hi,
I just saw this minor indentation problem in the docker-compose.yml
FYI: the README on docker hub seems to be outdated. It still notes that you should not use "latest" tag for docker images:
> Docker: Please only use Docker release tags
> Note: With Docker, please don't use latest tag. Only use release tags. See https://github.com/wekan/wekan/issues/3874
https://hub.docker.com/r/wekanteam/wekan
Cheers :-)

fix indentation for image  size and compression

---

server/migrations.js

- fixes #4925 broken migration `migrate-attachments-collectionFS-to-ostrioFiles`

Fixed broken migration migrate-attachments-collectionFS-to-ostrioFiles

---

client/components/boards/boardColors.css

Layout fixes for modern-dark after shuffling labels and date field on minicard

Layout fixes for modern-dark after shuffling labels and date field on minicard

---

client/lib/i18n.js

Fixes #4967 - Language preference is not persisted
Appears to work fine when loading while logged in.
Note that I do not have experience with Meteor this may not be idiomatic meteor code.

Wait until user has logged in before fetching language preference

---

client/components/main/layouts.jade

This fixes the issue of missing favicons when a board view itself is refreshed in the browser

Always fetch favicons from / path

---

client/lib/utils.js

If the minicard was "reordered", the next sorting number was always the middle between sorting number of 2 cards.
E.g. card below was at 10, card above at 20, the new sorting number was 15.
Now, the new sorting number is 11.
There was an issue about this in the past, but i can't remember it.

Rounding sort number to next integer

---

models/lib/fileStoreStrategy.js
server/migrations.js

- fixing admin attachment view, copied card attachments were wrong if copied to another board / list / swimlane

attachment copy changes now the boardId, listId and swimlaneId in the collection data

---

client/components/boards/boardColors.css
client/components/cards/attachments.css
client/components/cards/attachments.jade
client/components/cards/attachments.js
client/components/cards/cardDetails.jade

Fixes #1318 and maybe some related issues.
I added support for previewing pdfs in the browser (and also fixed some typos).
PDF viewer works by using the native HTML5 `<object>` tag, which can display pdfs without adding a new dependency.
This works fine in desktop Firefox and Chrome and in Firefox on Android.
It does **not** work in Chrome on Android.
To support that we'd probably need to use a 3rd party library.
The most popular one seems to be [PDF.js](https://mozilla.github.io/pdf.js/) but it uses Apache licence, which is [not ok](https://github.com/wekan/wekan/issues/1318#issuecomment-696023110).

Add support for viewing pdfs

---

models/boards.js

Previously requests to  `/api/boards/{boardId}/attachments` would fail:
```txt
W20230705-09:42:56.283(2)? (STDERR) TypeError: Cannot read property 'find' of undefined
W20230705-09:42:56.283(2)? (STDERR)     at models/boards.js:2279:10
W20230705-09:42:56.283(2)? (STDERR)     at packages/simple_json-routes.js:100:9
```
As far as I can tell this is because at some point `Attachments` model was changed and this was not updated.

Fix /api/boards/{boardId}/attachments endpoint

---

client/components/cards/attachments.css
client/components/cards/attachments.jade
client/components/cards/attachments.js
client/components/cards/cardDetails.jade

This PR adds a nicer attachment gallery with bigger previews and easier access (less clicks) to most common actions (download, rename, delete)
and an improved attachment viewer with support for:
- images/gifs (transparent images and SVGs are displayed with a checkerboard background)
- videos
- text files
- pdfs
- audio files
The viewer also works on mobile:
This viewer no longer uses swipebox so we can remove it (I haven't done that yet)
This PR closes #3888 and #4524

Improved attachment gallery and attachment viewer

---

client/components/cards/minicard.jade
client/components/lists/list.css

bold minicard title makes it easier to distinguish from other fields that are shown on the card
Before:
After:
[A recent commit](https://github.com/wekan/wekan/commit/467835192fbcd9d4016674fa2ee406258cc106e7) made the first list narrower than the rest.
Before:
After:
I am not sure why exactly do we need `min-width: 20px`, but if I broke something important feel free to revert that commit.

Small UI improvements

---

client/components/cards/attachments.css
client/components/cards/attachments.jade

A fix for attachment viewer not being hidden after removing some dependencies.
It looks like one of those defined a `.hidden` css class which I used for the attachment viewer and I forgot to define it separately.

Fix attachment viewer not being hidden

---

server/migrations.js

- every card must have a boardId, listId and swimlaneId, if not, the database data is corrupt, but the migration should also not break wekan from startup
- fixes #4998

fix for migration "attachment-cardCopy-fix-boardId-etc"

---

client/components/cards/attachments.jade
client/components/cards/attachments.js

This is a fix for setting background image from card attachments (closes #5003)
I need to figure out a better way to pass data between HTML and JS as these `data-xxx` attributes all over the place really aren't that nice.
If anyone knows a better way do let me know.

Fix setting background image

---

packages/wekan-oidc/oidc_server.js

This may happen if no group information is shared via OAuth2/OIDC but synchronization of user data is intended by WeKan administration. Without the patch the following exception is raised: `Error in OAuth Server: groups is not iterable`

Fix "PROPAGATE_OIDC_DATA" mechanism if "info.groups" is undefined

---

client/components/main/layouts.js
client/components/settings/invitationCode.js
client/components/settings/settingBody.js
client/components/users/userHeader.js
client/config/blazeHelpers.js
client/lib/spinner.js
client/lib/utils.js
models/users.js

removing Utils.getCurrentSetting() and use ReactiveCache directly

---

client/components/cards/attachments.jade

Attachment rename and delete works now again for non board admins

---

client/components/main/layouts.css
client/components/main/layouts.js
config/accounts.js
models/settings.js

The password login form is always created by meteor so we have to resort to overwriting the default css selector first.
This also reverses the password enabled/disabled flag to be more in-sync with other login methods.
Fixes #5029

Only selectively show login elements once settings is loaded

---

client/components/boards/boardBody.css
client/components/boards/boardBody.jade
client/components/cards/cardDetails.css
client/components/cards/cardDetails.js
client/components/main/popup.css

try to fix https://github.com/wekan/wekan/issues/4972 
- open card opens beside the minicard (as in earlier versions)
- re-enabled the autoscrolling feature to get the opened card in perfect view
- maximized opened card opens with position:fixed 
- new class "overlayed" added to board element when a card is opened to set `overflow:hidden` for the moment to prevent user from accidently scrolling in a point of death where you cant get back into a nice view
- scrolling on maximizing is commented out cause there is no need to scroll in any way

Fixing positioning of opened cards

---

client/components/cards/cardDetails.js

fixes https://github.com/wekan/wekan/issues/5070
The lists become sorted by fullname.
I did not found, how to set the members list popup of the board members to another sorting so it may stay sorted by username but i think fullname is more practically in daily business.

Alphabetic ordered member lists on assigne and member lists

---

models/cards.js

Ability to change the card's board and swimlane and list.
- **Card Field Updates**: The API endpoint now supports changing the board of a card. When provided, the `newBoardId` and `newSwimlaneId` and `newListId` parameters can be used to move a card to a new board.

Move card to other boards API

---

client/components/boards/boardBody.js

Fix for https://github.com/wekan/wekan/issues/5086
Changing `defaultView` from `'agendaDay'` to `'month'` fixes the problem that we had to refresh in order to show card when it's created with the calendar view.

Fix for CalendarView, Create Card without Refresh

---

openshift/wekan.yml

This would help, but not fix #5120. It's now supports the running of multiple pods for scaling, without the issue that the session will not known on the backend pod.

Make sessinAffinity stickable to clientIP

---

client/components/lists/listBody.js

You still have to click on "Template" twice to trigger the popup but IMHO it's better than the feature being completely broken.

Fixes issue #5131 (at least partly)

---

models/lists.js

Webhooks where not availiable for restore list action and changing list title. This is fixed in the commit. Note: list title is only included in outgoing webhooks if list is added to the WEBHOOKS_ATTRIBUTES environmental variable.

Added restore list and changing list title to outgoing webhooks

---

packages/wekan-oidc/oidc_server.js

This is an addition to [the previous PR](https://github.com/wekan/wekan/pull/5098). It now allows to specify the users permission on the default board. To make new users admin on the default board add it to the ENV:
`DEFAULT_BOARD_ID=someboardId:isAdmin`

Permissions for default board

---

client/lib/exportHTML.js

So this is a fix and a feature
I contributed HTML export so that folks wouldn't have to host a public mongoDB to share boards in non-interactive format with stakeholders that just want visibility.
Several frontend changes have happened since then, and I've not really had time to revisit the feature (feel free to tag me in issues relating to HTML export)
One change led to the following glitch (note the board is an empty board deliberately)
It's probably not the end of the world, but I wanted to fix it.
The feature added, is exporting webfonts and including them in the zip file.
This was tested on OSx (Apple Silicon) running armv8 wekan in Docker

Fix: export html popup

---

models/cards.js

This adds the a new boolean param option `archive` to edit_card of the Wekan API. 
Note: the API docs also need an update which is not included in this commit.

Added archive option to  of Wekan API

---

client/components/cards/minicard.css

Before this change, increasing the width of the list does not give much of a benefit, because the contents of the list are wrapped to 230px, anyway: 
After this change, the full width of the card is taken advantage of:

Make the contents of the cards grow to the list width

---

imports/i18n/tap.js
packages/wekan-oidc/oidc_server.js
server/authentication.js

In JS, the values of environment variables are [converted to string](https://nodejs.org/api/process.html#process_process_env) when checked, so the check for the `false` in value was incorrect.
Fix #5379

Fix DEBUG environment variable check

---

client/config/blazeHelpers.js

because ISO 8601 is not easy to the eye (at least for non-tech people).
We are currently adopting Wekan (moving away from trello) and the date format on the comment activity was found to be hard to read by many. If existing users love the previous ISO format, it might make sense to make the format customizable. Though, I would expect the locale selection to allow to take care of that already.

By default, use localized long date-time format

---

client/components/swimlanes/swimlanes.css

If there are more than 20 cards on one swimlane, we see infinite loading of the next cards. The bug appeared in version 7.10 with commit 7f9aa7509314a85a550dd16615429c5e030b5f2b.

fixed loading of cards if there are more than 20 of them on one swimlane

---

models/boards.js

1. It takes too long while server stops after 2 minutes (#5371).
2. It is useless, because when you copy a board, most of the time your users don't want to be notified of every copied cards.
This closes #5371: copy board is back to 8 sec. But, this doesn't explain why those notifications take so long and why server stops after 2 minutes.

Remove notification while copying board

---

client/components/users/userAvatar.jade

This fixes #5352.
If an organization or team was marked as inactive then their name did *not* not have a line across their name in the sidebar for Boards, where as if an organization or team was marked as active then their name had a strikethrough as shown in this screen shot below.

Bugfix: Strikethrough inactive Teams and orginizations logic was inverted

---

client/components/settings/adminReports.jade
client/components/settings/adminReports.js

Teams and Orgs are missing from Admin Reports. This adds them back in.
Note: Inactive Teams and orgs are not styles with a strike-though. which may or may not be relevant there. Honestly I couldn't get Jade/Pug to comply with what I wanted to do and you do not appear to place HTML in the javascript files.

Fill out Org and Team in adminReports

---

client/components/cards/attachments.jade

- this was for debugging, now not necessary anymore

remove attachment storage name from attachment list

---

models/cards.js

- if the parentId is undefined or empty, the code run in a infinite loop and the browser "hangs"

fix empty parentId in cards

---

docs/Platforms/FOSS/Snap/Candidate-WeKan-Snap-Manual-Upgrade.md

"sudo snap get wekan" outputs key value pairs but not sh code to set those values in snap wekan environment.

Update Candidate-WeKan-Snap-Manual-Upgrade.md in order to create a proper sh file snap-settings.sh

---

client/components/activities/activities.jade
imports/i18n/data/en.i18n.json

There was a bug when renaming the list it would only show the username in the activities list and not a description of what happened. Added the changedListTitle from list.js into activities.jade so that it will correctly show the list in the activities.

renaming list shows in activities

---

client/components/cards/cardDetails.css
client/components/lists/list.css

* Hide scrollbars from card details view
* Hide scrollbars from card lists, which are annoying because they are in the middle of the screen

Hide scrollbars where they interrupt

---

client/lib/keyboard.js

This commit enables using keyboard shortcuts when a different keyboard layout is used, by triggering the Mousetrap actions based on the keycode pressed.

Patch to allow shortcuts to work when another keyboard layout is used

---

client/lib/keyboard.js

Ctrl + C from card text would cause the card to be archived :(

Change move-to-archive keyboard shortcut to '-', because of Ctrl + C shortcut

---

client/lib/keyboard.js
imports/i18n/data/en.i18n.json

The current `[SPACE]` shortcut toggles the current user as a member of the card, but the translation suggests it should assign.
This PR does not fix that - it retains the original behaviour, but updates the translation.
In addition, a new `[m]` shortcut is defined to actually toggle the current user as an assignee.
This is a potential bug, which could also be fixed by the following patch instead:
```
diff --git a/client/lib/keyboard.js b/client/lib/keyboard.js
index 79f90456c..6d315b984 100644
--- a/client/lib/keyboard.js
+++ b/client/lib/keyboard.js
@@ -152,7 +152,7 @@ Mousetrap.bind('space', evt => {
if (ReactiveCache.getCurrentUser().isBoardMember()) {
const card = ReactiveCache.getCard(cardId);
-    card.toggleMember(currentUserId);
+    card.toggleAssignee(currentUserId);
// We …
```

Potential bug(fix?) - Add assign-self keyboard shortcut (old shortcut actually adds)

---

client/lib/keyboard.js

This might cause compatibility errors in older browsers

Add missing semicolon in keyboard.js

---

client/components/lists/list.css
client/components/lists/list.jade
client/components/swimlanes/swimlanes.css

Before:
After:
With large values in list width:
This looks nicer and more even when large widths are set on all lists, but retains current behaviour.

Make lists fill up space evenly, change listWidth to max-width

---

client/components/cards/cardDetails.css
client/components/lists/list.css
client/components/sidebar/sidebar.css
client/components/swimlanes/swimlanes.css

The old way of disabling scrollbars does not work in newer versions of Chrome.

Change way of disabling scrollbars, disable swimlane scrollbars

---

client/lib/keyboard.js

This was requested [here](https://github.com/wekan/wekan/pull/5576) by @mohammadZahedian.
This improves the ergonomics by allowing single left-handed handling of shortcuts.
IMO, this shortcut is a bit too close to the `ESC` button, which might cause misclicks.
@xet7 - What do you think?

Opinion - Change archive-card shortcut to backtick for better ergonomics

---

client/components/boards/boardBody.js
client/components/boards/boardHeader.js
client/components/swimlanes/swimlanes.jade

I have added dragscroll resets in functions that switch the view to allow for dragscrolling immediately after view switching (currently you have to refresh the page after switching the view mode)
I have also enabled dragscrolling in Lists mode (was previously only enabled in Swimlanes mode).
Fixes https://github.com/wekan/wekan/issues/5613.

Fix buggy behaviours in board dragscrolling

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
client/lib/keyboard.js
imports/i18n/data/en.i18n.json
models/users.js

This PR reverts recent keyboard shortcut disabling commits:
https://github.com/wekan/wekan/commit/5606414f8975fa0f75642d2e3a6b48c7559186f9
https://github.com/wekan/wekan/commit/94391d4cde7aed6e37efc6a9127b23ef0c2bd323
https://github.com/wekan/wekan/commit/8b73c702c39a1fd546e591a096d703a53577ffec
It also introduces a new button in the board header, which allows toggling keyboard shortcuts, per user:
This is when shortcuts are disabled:
This is when shortcuts are enabled:
This PR also fixes the `Ctrl + [char]` bugs by checking that there is no selected text before triggering the keyboard shortcut.
This is done using the `stopCallback` of the `mousetrap` library.

Restore keyboard shortcuts, enable per-user toggle, fix `Ctrl + C` bug by checking the text selection range

---

models/users.js

I got complaints about keyboard shortcuts suddenly being disabled (by default).
This PR only makes the default state "enabled" as it was before keyboard shortcuts were optional.

Enable keyboard shortcuts by default

---

client/components/boards/boardColors.css
client/components/cards/checklists.css

Fix the following bug:
Before:
After:

Fix weird add checklist buttons in card details

---

client/components/boards/boardBody.jade
client/components/boards/boardBody.js
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/lists/listBody.jade
client/components/lists/listBody.js
client/components/main/layouts.css
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
imports/i18n/data/en.i18n.json
models/users.js

Allow users to enable or disable vertical scrollbars:
Default (with scrollbars):
Optional (disabled scrollbars):
The default behaviour keeps WeKan as it was.
This feature was requested by some colleagues of mine.

Allow vertical scrollbars to be disabled (new preference)

---

client/components/boards/boardColors.css

Fix list header too wide in cleanlight and cleandark themes

---

client/lib/keyboard.js
imports/i18n/data/en.i18n.json

This feature was requested by a colleague of mine.
The feature assigns members to cards by board joining order, using `Ctrl+Alt+[1-9]`.

Feature - Assign members using keyboard shortcut `Ctrl+Alt+[1-9]`

---

client/lib/keyboard.js

When using ReactiveCache.getCard, a buggy instance of Card is returned. The bug experienced is that .assignees and .members are not always up-to-date.
This can be reproduced by trying to hover over cards and triggering a keyboard shortcut that interacts with a card.
@xet7 & @mfilser - WDYT?

Fix card updating issues with ReactiveCache when using keyboard shortcuts

---

client/lib/keyboard.js

Before this fix, toggling card assignees using `Ctrl + Alt + 1-9` would also work for members that were already removed from the board.

Fix assignee toggling keyboard shortcut to only toggle current board members

---

README.md

The added section adds more information for developers on how to contribute to the code base.
The current readme focuses on wekan users.  The information on the rebuild -wekan script is hidden on the wiki.
Sure, there is one link  "dev_docs", but that is easily overlooked. I feel that contributing to a project should be simple. 
This extra section gives the developer a bit more context and shifts the focus of the readme from using a little bit more towards contributing. Please feel free to adapt the wording to match your expectations.

Adding Development information to readme

---

client/components/boards/boardColors.css

- Fixed contrasting issue with tick check on custom fields, also fixed the green tick coming up on the checklists in cards by utilisation of the !important tag to override it with the checkbox colour for custom fields also.
See Issue #5674

Fix contrast issue checkbox

---

client/components/swimlanes/swimlanes.js

Description
This PR continues to address issue #5732.
🛠️ Fixes
Corrects the behavior of the "Add After" feature, which previously inserted new lists at the end instead of after the selected list.
Resolves a runtime error caused by a missing or undefined .list-position-input.
Ensures that ReactiveCache.getList is properly used and not replaced by non-reactive selection logic.
🧪 Manual Testing
Verified that adding a list "after" another correctly places it in the expected position.
Confirmed no JavaScript errors appear in the browser console.

Fix list insertion order and prevent runtime error in "Add After" feature

---

models/settings.js
models/users.js
server/lib/emailLocalization.js
server/lib/importer.js
server/notifications/email.js
server/rulesHelper.js

Add support for sending notification emails in the user's selected language. Previously, emails were always sent in English regardless of user preference. This PR ensures that notification emails respect the user's language setting.
Issue: [#5730]

Add email notifications language localization feature

---

client/components/forms/forms.css
client/components/main/layouts.css

this fix updates the CSS to improve cross-browser compatibility by:
Adding -webkit-user-select before user-select to support Safari and iOS browsers.
Adding both -webkit-text-size-adjust and text-size-adjust to ensure consistent text sizing across browsers.
Ordering vendor-prefixed properties before standard properties as per best practices.

Fix: Add vendor prefixes for user-select and text-size-adjust for better browser compatibility

---

client/components/main/layouts.css

Fixes open issue around webkit/user-select attributes. Modifies values to allow "text" values to be selected in cards and on the board.
Should fix changes around PR #5771

Allow selection of card text via webkit/user-select attributes

---

models/cards.js
public/api/wekan.yml

This pull request adds a REST API endpoint to retrieve a card by the card ID only, without list ID and board ID.
This endpoint is neccesary to get the details of a card's parent card, because currently there is no way to get the parent card's list ID and board ID.
See https://wekan.fi/api/v7.92/#tocscards . There is a `parentId` property, but neither `parentListId` nor `parentBoardID` exists.

Add a REST API endpoint to retrieve a card by ID
