client/views/boards/events.js
client/views/boards/helpers.js
client/views/boards/templates.html
collections/users.js

I disabled the trailing white spaces cleaning so this PR should be easier to review.
Still to do:

Allow a user to “star” a board

---

client/components/sidebar/sidebarFilters.jade

The `add-label` and `remove-label` strings already contain the "Add" and "Remove" parts.

Remove redundant words

---

client/components/sidebar/sidebarFilters.js

If every element already has the label/member, we do not need to add it
but it should be removed and if every element does not have the element,
we should add it.

Fix multiselect toggle logic

---

client/components/boards/boardHeader.js
client/components/cards/attachments.js
client/components/cards/cardDetails.js
client/components/lists/listHeader.js

`this` changes during `Popup.afterConfirm` and so we need to save it in a
local variable.

Fix card deletion

---

.editorconfig

Just added .editorconfig (http://editorconfig.org/) to help with style across different code editors.

Add editorconfig support

---

client/components/boards/boardBody.jade
client/components/boards/boardBody.js
client/components/boards/boardColors.styl
client/components/boards/boardHeader.jade
client/components/boards/boardsList.jade
client/components/boards/boardsList.styl
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/cards/minicard.styl
client/components/forms/forms.styl
client/components/lists/listHeader.jade
client/components/main/header.jade
client/components/main/header.styl
client/components/main/layouts.styl
client/components/main/popup.styl
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
client/components/sidebar/sidebar.styl
client/components/users/userForm.styl
client/components/users/userHeader.jade
client/lib/popup.js
client/lib/utils.js

PR for feature mobile web.
See discussion and screenshots: #437

add: support mobile web, adapt to small browser window

---

client/components/main/layouts.jade
client/components/users/userForm.styl

add a div with box-shadow as container dialog of at-form and language select.
when in compact mode:
1. change dialog to full window.
2. change language select from absolute position to relative.
3. change logo to half size and float on top right.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/455)

optimize login form layout & css

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/main/layouts.styl
client/components/users/userHeader.jade

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/477)

Bugfix, and optimize icon for notification

---

README.md

I'm wondering, should it be in a different category than PaaS offer?
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/512)

Adds IndieHosters SaaS offer

---

client/lib/popup.js

Remove extra `the`
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/515)

Fix a typo

---

client/components/import/import.jade
client/components/sidebar/sidebar.jade
models/users.js

The name of the profile field was changed log ago. This fixes the
remaining wrong references.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/615)

profile.name is called profile.fullname

---

README.md

Similar to the other deployment options already in the readme, Cloudron offers a server platform to install and maintain wekan and other apps. Thanks for all the effort already gone into wekan, very good app :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/639)

Add Cloudron install button

---

models/boards.js

This was introduced in #616 and is a leftover from a local change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/651)

models: Remove wrong line (fix #650)

---

models/cardComments.js

Link to this issue : https://github.com/wekan/wekan/issues/702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/736)

[ENH] Add index on CardId into Comments collection

---

Dockerfile
README.md
docker-compose.yml

- update docker-compose.yml to allow pulling directly from the dockerhub.
- fixes for the ARG [issue](https://github.com/wefork/wekan/issues/90), [bug fix](https://github.com/wefork/wekan/issues/90)
- update readme for docker-compose commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/775)

update docker compose

---

README.md

- minor change to readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/777)

fix & to &&

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/779)

tweaked .gitignore to exclude .build/*

---

client/components/main/layouts.styl

- Add YuGothic and Meiryo. because display of non english letter dirty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/707)

UI: fix font

---

client/components/sidebar/sidebar.js

Pass the board id to fulfill the check condition in **quitBoard** method so that board admin users can leave a board as long as they are not the last remaining board admin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/719)

bugfix: Leave board

---

client/components/main/layouts.styl

- apply underline to list text
- change text color on hover
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/706)

UI: fix description link style.

---

Dockerfile

Forgotten instruction, can create issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/835)

Dockerfile: Add EXPOSE

---

client/components/boards/boardHeader.jade
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
i18n/en.i18n.json

* Closes #843 
* Closes #844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/845)

B menu tool tip

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/main/header.js
i18n/en.i18n.json

Closes #847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/866)

Only header-bar new-boards are auto-starred

---

models/users.js
server/notifications/email.js

To avoid to register user with Uppercase in email (invite user to create account directly on the board)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/891)

[ENH] Invite user with lower case email

---

models/import.js

Add support for importing checklists and items when importing a board from Trello
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/894)

Close #873 by importing checklists from Trello

---

client/components/settings/settingBody.js
models/settings.js

Set mail-from to environment immediately after changed, allow user set a blank username&password pair in SMTP setting.
For #895 #896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/901)

Set mail-from to environment immediately after changed,

---

client/config/blazeHelpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/915)

No need for Array.prototype if using rest operator

---

client/components/settings/invitationCode.js
config/accounts.js
models/settings.js
models/users.js

Remove invitation code if email sending failed.
Show customized error msg while invitaion code is wrong during registration.
Fix "internal error" while registration is done.
Fix "cannot access disableRegistration of undefined" error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/939)

Bug fix with Invitation & registration

---

config/accounts.js
models/settings.js
models/users.js
server/notifications/email.js

Don't try to send emails if no smtp server configured.
Fixes #923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/943)

Don't send emails if missing smtp host

---

models/boards.js

resolves issue #950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/952)

hotfix to user add isCommentOnly

---

config/accounts.js
models/settings.js
models/users.js
server/notifications/email.js

MAIL_URL was overriden with database info all the time.
Now if MAIL_URL exists is not overwritten and if neither MAIL_URL nor
exists valid admin panel data MAIL_URL is not set.
MAIL_FROM was ignored. Same behaviour, env variable has bigger priority
than database configuration.
On both cases, althrought environment variable is set, updating admin-panel
mail settings will load new info and ignore the environment variable.
Remove some code that is not needed anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/968)

Fix email settings loading

---

models/users.js

The code for making first user an Admin was there, but missing isAdmin field on userSchema.
Fixes #924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/970)

Add isAdmin to user Schema

---

models/import.js

addresses issues: #996 and #950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1008)

isCommentOnly false fix for Trello import

---

.eslintrc.json
.meteor/packages
.meteor/versions
models/boards.js
models/cardComments.js
models/cards.js
models/checklists.js
models/lists.js
models/users.js
server/authentication.js
server/logger.js

Hi there,
I have added checklist and card comment for restapi.
And delete console.log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1033)

Meteor 1.4 restapi

---

.gitignore
models/boards.js
models/cards.js
models/lists.js
models/users.js
server/authentication.js

This pull requests extends the REST API and changes the authorization system for some of the endpoints.
It implements some of the features listed in #1037. All changed or added endpoints are read-only.
The following changes were made:
- Add additional functions to `authentication.js`. It is now possible to check if a user should get access to a given board.
- Added the endpoint `GET /api/user` which allows to get basic information about the API user.
- Added the endpoint `GET /api/user/boards`. This endpoint can be used to get all boards this user is part of.
- Changed the reading access methods created by @huneau to be usable by any logged in user. I used a new authorization function which grants access to every board for admins, but restricts access for normal users. This change …

REST API features

---

client/components/lists/listHeader.js

How you do you feel about it?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1054)

Add delete the card belonging to when deleting the list

---

client/components/boards/boardHeader.js
models/export.js

Fixes #1055
Still does not fit nicely into the new REST API but at least allows the export to work again for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1059)

Reenable the export feature

---

client/components/boards/boardHeader.js

This PR fixes #1061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1067)

Fix export path

---

client/lib/keyboard.js

This PR fixes #1064
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1066)

Fix "W" shortcut binding

---

client/components/main/layouts.js
client/components/users/userHeader.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1070)

Sort available languages by their translated names

---

config/router.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1074)

Fix filter reset on moving between starred boards.

---

client/components/settings/settingBody.jade
i18n/en.i18n.json

Closes #1048
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1076)

Fix Admin Panel link available to all users, only link to it is hidden

---

models/import.js

Attribute correct members to their comments.
Fixes #903
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1080)

Fix importing Trello board

---

models/import.js

Add importing the due date of a card
Fixes #1081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1082)

Update import from Trello feature

---

client/components/users/userHeader.jade

Related: https://github.com/wekan/wekan/issues/973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1084)

Fix admin panel in subfolder environment

---

.eslintrc.json
client/lib/i18n.js

Related: #973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1085)

Fix i18n in subfolder environment

---

client/components/activities/activities.js
client/components/cards/attachments.jade
client/components/cards/minicard.jade

Closes #1015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1086)

Fix: incorrect attachment link with subfolder in the url

---

client/components/cards/cardDetails.jade

Closes #975 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1087)

Fix: link to card

---

models/checklists.js

Fix: duplicate id generation 
Closes #1090
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1093)

Fix: id generation

---

models/cards.js

I add a method at the model/Cards.js. This method permit to modify an existing card, through a request PUT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1095)

Adding a put method to update a card

---

models/cards.js

Hello, 
After using my method is better to use "hasOwnProperty" instead of checking "undefined". #1095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1097)

Fixing error of my put method

---

client/components/cards/checklists.jade
client/components/cards/checklists.js

Add check to see if input is empty.
Closes #1103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1107)

Fix: possible to add empty checklist items on a card

---

client/components/cards/checklists.styl

Like a trello.
1. Change background color on mouseover and remove it after mouseout
1. Increase the clickable area of title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1108)

Improve UI Design (checklists item)

---

client/components/import/import.js
models/export.js
models/wekanCreator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1134)

Export and import attachments as base64 encoded files

---

models/cardComments.js
models/cards.js

Hi, 
That is the fixe for the issue  #1045.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1116)

Checking the authorId when adding card

---

models/export.js
models/wekanCreator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1140)

Export and import checklists

---

client/components/activities/activities.jade
i18n/en.i18n.json
models/activities.js
models/checklists.js

This PR fixes #1025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1148)

Add checklist items to activity log

---

client/components/main/layouts.styl

Fixed incomplete fix for  https://github.com/wekan/wekan/pull/646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1152)

Fix showing card activity history in IE11

---

models/attachments.js

This PR fixes #1105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1153)

Fix files access bug

---

client/components/settings/informationBody.jade
client/components/settings/informationBody.js
client/components/settings/settingHeader.jade
config/router.js
i18n/en.i18n.json
package.json
server/statistics.js

Closes #963 #356 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1156)

Add display wekan version number and runtime environment

---

.eslintrc.json
client/components/settings/settingBody.jade
client/components/settings/settingBody.js
client/components/users/userHeader.jade
client/components/users/userHeader.js
i18n/en.i18n.json
models/accountSettings.js
models/users.js
server/publications/accountSettings.js

Closes #848 
Usage
1. Set allow email change in admin panel.
2. Edit profile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1161)

Add Feature: change email address

---

client/components/cards/checklists.styl

Closes #1163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1171)

Fix: Squeezed tickbox in Card

---

models/checklists.js

This PR fixes #1198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1200)

Fix errors caused by checklist items activities

---

client/components/cards/attachments.js
models/attachments.js
models/trelloCreator.js
models/wekanCreator.js

This PR finishes work started in #1187 and fixes #1157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1202)

Import attachments' related activities from Wekan and Trello

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
i18n/de.i18n.json
i18n/en-GB.i18n.json
i18n/en.i18n.json

With this code change it is possible to copy cards from one list to the same or another list on the same board. The copied card is added to the bottom of the specified list. You also have to provide a title for the copied card.
The code copies the card itself, the checklists and the card comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1204)

Add feature: Copy cards within one board

---

models/trelloCreator.js
models/wekanCreator.js

Now that a sort attribute is added to checklists and checklists items thanks to #1215
Import/Export feature need to take into consideration this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1226)

Import checklists and its items sort attribute

---

i18n/de.i18n.json
i18n/en.i18n.json
models/activities.js

These are the missing notifications and english and german translation.
#1225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1238)

add translation for email notifications regarding checklists and checklist items

---

server/migrations.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1240)

Add migration script to add sort field to checklists and their items

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
models/checklists.js
server/migrations.js

This PR is related to #876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1242)

Keep state of checklist items when moved cross checklists

---

client/components/lists/list.styl
client/components/lists/listHeader.jade
client/components/lists/listHeader.js

#1233  PR for the plus button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1244)

#1233 Added plus button to add card on top of the list

---

models/trelloCreator.js

This PR fixes #1243 and #1245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1259)

Fix errors encountered when importing from Trello

---

client/components/activities/activities.jade
client/components/activities/activities.styl
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/forms/forms.styl
client/components/lists/listBody.js

#1182 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1247)

Add Feature: comments only in activity feed

---

models/users.js

I just did set optional to false instead of true ...
Sorry ... :-D
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1251)

Fix: Add Feature: REST API: Create user despite disabling registration https://github.com/wekan/wekan/issues/1249

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
i18n/en-GB.i18n.json
i18n/en.i18n.json
i18n/pt-BR.i18n.json

I've added the ability for the user to self remove from the board.
This feature was highly requested and seems to be a logical feature to add.
This ability can also me made into a configurable option from the Admin panel, for example. 
Please post critics and comments!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1283)

Add Feature: User is now able to leave a board

---

.meteor/packages
.meteor/versions
client/components/cards/attachments.jade
client/components/cards/attachments.js
client/components/cards/attachments.styl

*  Added media queries to resize attachments on smaller screen sizes
*  Added [swipebox](https://atmospherejs.com/horka/swipebox) to attachments for previewing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1315)

Attachments improvements (#201)

---

models/wekanCreator.js

fixed multiple errors where constants were mistakenly overridden.(or
trying to get a property of an object after making sure it doesn't
exits)
renamed wekanBoard Parameter from createBoardAndLabels for clarity
reworked adding admin for importer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1316)

fixed Members do not get included on board import from WeKan #1255

---

.gitignore
client/components/settings/peopleBody.jade
client/components/settings/peopleBody.js
client/components/settings/peopleBody.styl
client/components/settings/settingHeader.jade
client/components/users/userHeader.js
config/router.js
models/users.js
server/publications/people.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1325)

Added people list in admin panel

---

models/boards.js
models/cardComments.js
models/checklists.js
models/integrations.js
models/lists.js
models/users.js

https://github.com/wekan/wekan/issues/1037#issuecomment-301271356 
> Better error output. Currently HTML gets returned if some parameter was wrong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1323)

Add REST API better error output

---

client/components/boards/boardsList.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1346)

Fixed issue on board list with long-desc boards

---

server/logger.js

I noticed that I didn't have logs any more, and my instance keeps failing.
This would  fix it, and revert to the previsous logic - logs by default to stdout/stderr!
12factor.net FTW! :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1350)

Fix logger

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1358)

fix some typos

---

client/components/users/userAvatar.jade

Fix permissions
Closes #1349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1360)

Fix: User with comment only permissions can remove another user from a card

---

client/components/boards/boardBody.jade
client/components/boards/boardBody.styl
client/components/boards/boardColors.styl
client/components/boards/boardHeader.js
client/components/lists/list.jade
client/components/lists/list.js
client/components/lists/list.styl
client/components/lists/listHeader.jade
client/components/lists/listHeader.js
client/components/main/header.jade
client/components/main/header.js
client/components/main/header.styl
client/components/users/userHeader.jade
client/config/blazeHelpers.js
config/router.js

This PR was previously in #458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1365)

Conflict Resolution #458

---

client/components/settings/peopleBody.jade
client/components/settings/peopleBody.js
models/users.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1372)

Allow admin to change user password in admin panel

---

client/components/boards/boardsList.js
client/components/main/header.js
client/components/users/userHeader.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1371)

Fixed - bug on not able to see ADMIN PANEL if not access Board List

---

client/components/activities/activities.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1380)

Fixed - bug on not able to see member avatar on sidebar activity

---

client/components/activities/activities.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1388)

Fixed - bug on long url of attachment in card activity log

---

client/components/cards/cardDetails.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1391)

Always display attachment section for uploading file quickly

---

client/components/lists/list.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1392)

Fixed - make it easier to see the Adding Card btn at top of list

---

client/components/cards/attachments.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1401)

Update - auto update card cover with new image uploaded via drag&drop

---

Dockerfile

* fix missing backslash
* ignore socket file during deletion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1439)

Fix Dockerfile for Debian

---

models/lists.js

Fixes some of the symptoms of Issue #1461.
Move to top and bottom are not fixed yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1465)

Fixing cards query to apply sort

---

snapcraft.yaml

Fixing snap store review rejection
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1469)

Fixing snap store rejection

---

models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1490)

add swimlaneId to POST /api/boards/:boardId/lists/:listId/cards route

---

snap-src/bin/caddy-control
snap-src/bin/config
snap-src/bin/mongodb-control
snap-src/bin/wekan-help
snap/hooks/configure

- service life cycle improvements
- wekan help text changes and tweaks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1500)

service life cycle improvements

---

.eslintrc.json
client/components/main/layouts.js
client/components/users/userHeader.js
models/trelloCreator.js
sandstorm.js

This PR fixes lint errors
@xet7 
I made some changes to sandstorm.js, so this PR needs testing in that area.
Can I fix lint warnings too? so that CI report becomes lighter.
If yes, I'll add more commits to this PR before it gets merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1508)

Fix lint errors

---

client/components/sidebar/sidebar.js
models/boards.js
models/cardComments.js
models/cards.js
models/checklists.js
models/integrations.js
models/lists.js
models/swimlanes.js
models/users.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1510)

Fix lint warnings

---

snap/hooks/configure
snap/hooks/install
snapcraft.yaml

Fixing problem when mongodb was not started at install/refresh
Adding network hooks for configure hook to fix security denials
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1514)

Fixing problem when mongodb was not started at install/refresh

---

models/wekanCreator.js

This PR fixes #1516 and #1428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1517)

Import missing card fields : isOvertime, startAt and spentTime

---

models/boards.js

This PR fixes #1507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1518)

Lists view is the default view when creating boards

---

.eslintrc.json
client/components/cards/cardDetails.js
client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl
client/lib/utils.js
models/activities.js
models/cards.js
models/checklistItems.js
models/checklists.js
server/migrations.js
server/publications/boards.js

Based on #876 and #1483, I changed the model of checklist items to have their own collection. This way sorting can be implemented almost the same way as with cards/lists/swimlanes.
I also added checklist reorder capability within the cardDetails view.
Works in my local setup, please try it out!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1543)

Checklist items sort fix, and checklist sort capabiliity

---

client/components/boards/boardBody.js
client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/lists/listBody.js
client/components/swimlanes/swimlanes.js
models/boards.js
models/users.js
server/migrations.js

This PR fixes #1567.
The board view logic is moved to the user profile so many users can view the board differently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1588)

Move boardView logic to user profile

---

models/trelloCreator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1611)

Fix Trello importation for ChecklistItems

---

models/trelloCreator.js
models/users.js
models/wekanCreator.js

Hi,
Related to this [issue](https://github.com/wekan/wekan/issues/1602)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1617)

Define sort property on swimlanes and lists

---

client/components/cards/checklists.styl

See #1619 for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1620)

Change checklist-item line-height to 18px. Fixes #1619

---

models/cards.js

Add the possibility to modify card's labels with the API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1626)

API Edit Card Labels

---

server/migrations.js

Confirmed to fix [#1636](https://github.com/wekan/wekan/issues/1636) thanks @xet7 @Badpat for advice!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1641)

ensure checklistItem titles are correct when migrating

---

server/migrations.js

Just putting an empty array in Cards.customFields seems to be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1644)

Migration for custom Fields

---

.eslintrc.json
client/components/cards/minicard.jade
client/components/cards/minicard.styl
client/components/sidebar/sidebarFilters.jade
client/components/sidebar/sidebarFilters.js
client/lib/filter.js
i18n/en.i18n.json

Advanced Filter for Custom fields. 
Known Issues / Todos:
- No good error handling. It can happen that malformed strings throw errors in console. It doesent affekt the user, there are just no cards displayed.
- No advanced filters for Labels and Members
- The description doesn't look that good, (and may contain a lot of language errors) 
- Make advanced filters saveable
- Resseting the filters doesent remove the string from the input field.
- Through the description the "Reset Filter" Buttons are outside the screen by default. You can scroll down, but you can miss it
- Markdown support for text fields would be nice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1646)

Feature advanced filter

---

client/lib/filter.js
models/cards.js

This commit should fix a lot of issues regarding not opening boards after import / REST API:
#1652 
#1651 (Not sure, but could be, would nice if the issue author could test this after release) 
#807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1653)

Custom Fields Correction of Loading Board Issues

---

client/components/cards/cardDate.js

This pull request fixes #1654.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1661)

Fix Received Date and End Date on Cards

---

server/migrations.js

Adjust 'add-profile-view' in server/migrations.js in attempt to resolve #1675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1681)

Adjust 'add-profile-view' in migrations.js in attempt to resolve #1675

---

client/components/cards/cardDate.js
client/components/cards/minicard.jade

Modify card covers/mini-cards so that:
- received date is shown unless there is a start date
- due date is shown, unless there is an end date
This begins to address #1668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1685)

Modify what dates are shown on card covers

---

client/components/boards/boardBody.js
client/components/cards/minicard.jade
client/components/sidebar/sidebarCustomFields.jade
client/lib/filter.js
models/cards.js

Fix for #1659 
Hotfix for: #1623 (Not fixing the whole problem, but you can at least view cards in public again, list view only) 
and fixes to Advanced Filter, Your now able to filter for Dropdown and Numbers, Also Dropdown are now correctly displayed on minicard.
(All of this in #807 )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1699)

Feature custom fields

---

client/components/users/userAvatar.jade

see #1690
before / after
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1714)

Fix vertical align of user avatar initials

---

client/components/cards/minicard.styl

see #1690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1713)

Less margin-bottom after minicard

---

client/lib/inlinedform.js

make sense?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1717)

Submit inline form on click outside

---

client/components/settings/invitationCode.js

99be745f0299b32a8a7b30204b43bff7fd5ba638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1732)

Restore invitation code logic

---

client/components/cards/minicard.styl

old shadow was in the end totally fine, sorry for that
6a58729
#1690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1726)

Revert minicard shadow

---

client/components/boards/boardBody.js
client/components/cards/cardDetails.js
client/components/cards/checklists.js
client/components/lists/list.js
client/components/main/header.styl
client/components/mixins/perfectScrollbar.js
client/components/swimlanes/swimlanes.js
client/lib/utils.js

Mobile hotfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1757)

Mobile hotfix

---

wekan-openshift/README.md
wekan-openshift/wekan.yml

Added OpenShift template to run WeCan in OpenShift.
Tested on OpensShift 3.7 Dedicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1765)

Wekan integration with OpenShift

---

client/components/settings/invitationCode.js

The code used to patch the bug of the invitation code.
The issue was [https://github.com/wekan/wekan/issues/1749](url)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1777)

Patch Invitation Code

---

client/components/settings/settingBody.js
models/settings.js
models/users.js

- Fixed the bug that prevented resending an invitation code to someone who has already received it.
- Added the feature which able to resends an invitation code with a new list of boards.
- Added a database check to see if the user already exists before sending a code.
- Added deletion of the invitation from the database after the user was created correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1785)

Bugfix : Resending invitation code.

---

client/lib/utils.js
config/router.js
models/settings.js
server/policy.js
snap-src/bin/config

Integration of Matomo with environment variables handled by snap.
Nothing for docker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1806)

Integration of matomo with env vars

---

client/components/cards/cardDate.js
client/components/cards/cardDate.styl
client/components/cards/cardDetails.jade

Fix the flagging of dates (i.e. due date only flagged when it is before end date, or if it after now and there isn't an end date)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1814)

Fix date CSS

---

.meteor/packages
models/users.js
server/authentication.js

Hi, 
I wrote an oauth2 authentification patch for my organisation. It's not perfect : attributes may need to be adjust manually (username, fullname) to create a complete user profile with the right name, fullname, initials, etc. 
And to take off the secret configuration from file authentification.js... 
but it works ! :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1578)

authentification oauth2

---

SECURITY.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1857)

Security documentation typos

---

client/components/cards/cardDetails.jade

Only allow ifCanModify users to add dates (received, start, end, and due) on cards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1867)

Only allow ifCanModify users to add dates on cards

---

models/activities.js
models/boards.js
models/cards.js
server/notifications/outgoing.js

This is to support (in a very basic way) swimlanes in wekan-gogs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1876)

Add swimlaneId in activity. Create default swimlaneId in API

---

client/components/lists/list.js
client/components/lists/listBody.js

This fixes #1887 for me !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1891)

Fix #1887. Fix #1885.

---

client/components/boards/boardHeader.jade
client/components/rules/actions/cardActions.js
client/components/rules/rules.styl
client/components/rules/triggers/boardTriggers.jade
client/components/rules/triggers/boardTriggers.js
client/components/rules/triggers/cardTriggers.js
client/components/rules/triggers/checklistTriggers.js
i18n/en.i18n.json
models/cards.js
models/checklistItems.js
models/lists.js
server/rulesHelper.js
server/triggersDef.js

Fixed some bugs related to rules.
Fixed broken board filter.
Fixed rules dropdown layout to adapt to text.
Added new "card moved" trigger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1909)

Feature rules fixed

---

snap-src/bin/wekan-read-settings

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1910)

Fix Cannot setup mail server via snap variables. Closes #1906

---

.meteor/packages
.meteor/versions
Dockerfile

This will fix : https://github.com/wekan/wekan/issues/1760
See documentation here : https://github.com/ppoulard/meteor-accounts-cas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1913)

Add CAS with attributes

---

openshift/wekan.yml

Would resolve (by default) issue https://github.com/wekan/wekan/issues/1923
Also drop the duplicated parameter variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1930)

Drop default namespace value and duplicate WEKAN_SERVICE_NAME parameter

---

client/components/rules/ruleDetails.jade
client/components/rules/ruleDetails.js
client/components/rules/rules.styl
client/components/rules/rulesActions.jade
client/components/rules/rulesActions.js
client/components/rules/rulesMain.js
client/components/rules/rulesTriggers.jade
client/components/rules/rulesTriggers.js
i18n/en.i18n.json
models/checklistItems.js
models/wekanCreator.js
server/rulesHelper.js

This pull request fixes various problems and addresses some enhancements.
Quoting the issues #1912 : 
> Other Points as overview
> 
> Another points:
> 
> in the rule dialog a function to go back to the "main menu" ✅ [Added]
> maybe to make rules editable? (see point three in the other lists, if an mistake in the lists name, need to delete the completly rule) ❌ (Still in progress)
> Enhancement: Not overwrite first checklist value ✅ [Fixed]
> Rules
> 
> when add a checklist, also be possible to add checklist items to the checklist ❌ (Still in progress)
> not allow to add an empty rule (i think related to (1) and (2))✅ [Fixed]
> make an drop down for the existing lists in a board ❌ (Still in progress)
> Different Rules with same result give exception✅ [Fixed]
> (1) Part 1: Rule "Add …

Feature rules: fixes and enhancements

---

models/cards.js

Resolves #1934 
Adds rest API path the retrieve card by swimlane Id and return list Id in response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1944)

Add route to get cards by swimlaneid

---

client/components/cards/minicard.jade
client/components/lists/listBody.js
client/components/sidebar/sidebarCustomFields.jade
client/components/sidebar/sidebarCustomFields.js
i18n/en.i18n.json
models/customFields.js

Hi,
I'm quite new to meteor, so don't hesitate to correct/review my code.
For my needs, i upgrade custom fields 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/1987)

custom fields upgrade

---

rebuild-wekan.sh
start-wekan.sh
status-wekan.sh
stop-wekan.sh

See the commit messages for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2002)

Revised shell scripts to work better

---

.meteor/packages
.meteor/versions
CHANGELOG.md
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl

Resolved #1404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2050)

Clicking the scrollbar closes the card on Chrome #1404

---

Stackerfile.yml
stacksmith/user-scripts/boot.sh
stacksmith/user-scripts/build.sh
stacksmith/user-scripts/run.sh

Add Bitnami Stacksmith
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2064)

Add Bitnami Stacksmith

---

.meteor/packages
.meteor/versions
client/components/cards/minicard.jade
client/components/cards/minicard.styl
client/components/lists/list.js

Resolved #1772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2067)

 Issue : UI feature suggestion: drag handles and long press #1772

---

.meteor/versions
client/components/cards/cardDetails.jade
client/components/main/header.styl
client/components/main/layouts.styl

Resolved #953
Fixed points
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2084)

Issue: Hard  to use Wekan on mobile because of UI/UX issues #953

---

LICENSE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2112)

update license to year 2019

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
i18n/en.i18n.json

When triggered from the hamburger.
After a lot of tries and errors, I finally got the color picker working.
I figured out it would be better than setting the per-dropdown item background as in the end, we don't really want the end user to exactly know which color is which.
There is still the issue of the color with the IFTTT, but I don't know if we can have a color picker there as well.
Note: Apache: I-CLA signed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2117)

Set the card color with the color picker

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/rules/actions/cardActions.jade
client/components/rules/actions/cardActions.js
client/components/rules/rules.styl
i18n/en.i18n.json
models/cards.js

As requested in #2117, this implements the color picker in the IFTTT as well.
The background color of the button is updated with the selected color, and so is its label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2121)

Color picker in IFTTT

---

models/boards.js

If the data is passed as a boolean (through json), data.toLowerCase() raises an error.
Also define `query` which we are returning in case of success.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2127)

api: fix set_board_member_permission

---

client/components/rules/actions/cardActions.jade
client/components/rules/actions/cardActions.js
client/components/swimlanes/swimlanes.styl

I managed to get the following bug fixed with a one liner:
And after a lot of thoughts, I made the color button in the IFTTT more Jade-ish
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2132)

Fix for v2.03

---

client/components/lists/list.styl
client/components/lists/listBody.jade
client/components/lists/listBody.js

This allows to reduce the loading time of a big board
Based on http://www.meteorpedia.com/read/Infinite_Scrolling
Related to #2104 
Any tests before merge would be appreciated :)
Note: Apache I-CLA signed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2144)

Use infinite-scrolling on lists

---

models/users.js

@xet7  Removed trailing spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2164)

Fix trailing spaces for OIDC fix

---

.meteor/versions
Dockerfile

New debug parameter added to wekan to enable use of debugging logic within salleman OIDC code.  This new debugging argument should also be a useful tool for runtime debugging elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2181)

Added debug flag and bumped salleman package version

---

models/import.js
models/wekanCreator.js

imports are currently broken and return an error 500.
This is fixable and we can also import the colors of the cards and swimlanes while we are at it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2245)

Fix imports

---

models/activities.js

Fixes: https://github.com/wekan/wekan/issues/2252
Caused by: https://github.com/wekan/wekan/commit/3bfc6ea8d7ee72d3507f64c369e1478fffeaf337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2253)

Fix watchers undefined #2252

---

server/rulesHelper.js

Fixes #2246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2272)

Don't swallow email errors

---

models/boards.js
server/publications/boards.js

I think this should fix #2256 
I couldn't reproduce the duplicated list issue, @sfahrenholz could you test ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2265)

Fix dissapearing subtasks

---

server/rulesHelper.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2279)

Fix IFTTT email sending

---

models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2291)

Add proper variables for join card Fixes #2285

---

client/components/lists/listBody.js

Switch back to a custom spinner detection, as the IntersectionObserver is eating a lot of CPU resources on idle.
This should also take care of #2250 properly: the previous `onDestroyed()` was removing the resize and scroll callbacks, but they were not unique enough, and they were shared across swimlanes. So if a list had 2 swimlanes with spinners, when one was removed, the other was not triggering its callbacks anymore.
Related: #2294
On Firefox, with the IntersectionObserver I can observe in the task manager a "medium" usage, while with this patch, it drops to "low". I am not entirely sure this fixes everything, as in Chrome, I do not see a significant difference with or without the patch.
The downside effect however is that we are loading cards that do not appear in the view, if the …

list: do not use IntersectionObserver to reduce CPU usage

---

models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2313)

Add proper variables for unjoin card

---

.meteor/packages
.meteor/versions
client/components/cards/cardDetails.styl

Resolved #2188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2314)

Issue: Center reduce left margin in card view on mobile browser #2188

---

models/attachments.js
models/cardComments.js
models/cards.js
models/checklistItems.js
models/checklists.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2320)

Add variables for activity notifications Fixes #2285

---

docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2332)

Removed quotes

---

.meteor/versions
server/publications/fast-render.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2347)

Additional Meteor 1.8.1 changes

---

client/components/lists/list.styl

Resolved #2371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2374)

Issue : Mobile UI Center cards in list view #2371

---

client/components/sidebar/sidebarArchives.jade
client/components/sidebar/sidebarArchives.js
client/components/swimlanes/swimlaneHeader.jade
i18n/en.i18n.json
i18n/fr.i18n.json
models/boards.js
models/cards.js
models/checklists.js
models/lists.js
models/swimlanes.js

Patch remove feature (boards, cards) which didn't remove dependencies in other collections (checklist, checklistItems for cards by example).
Add remove for lists and swimlanes archived.
Add remove all and restore all for cards, lists and swimlanes archived.
English and French support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2376)

remove feature

---

client/components/main/layouts.jade
client/components/main/layouts.js
client/components/main/layouts.styl
i18n/en.i18n.json
i18n/fr.i18n.json

Now a loading animation is displayed when the authentication is performed. This allows users to know that it's in progress.
English and french support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2379)

Improve authentication page

---

client/components/boards/boardHeader.jade
client/components/cards/cardDetails.jade
client/components/cards/checklists.jade
client/components/cards/subtasks.jade
client/components/lists/listBody.jade
client/components/main/editor.jade
client/components/sidebar/sidebarSearches.jade

There are still a few places where applying RTL proved difficult.
Will open a new issue regarding them once this change is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2395)

Fixed RTL issue #884

---

client/components/boards/boardBody.jade
client/components/boards/boardBody.js
client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/lists/list.js
client/components/lists/listBody.js
client/components/lists/listHeader.js
client/components/swimlanes/swimlanes.js
models/export.js
models/swimlanes.js
models/users.js
server/publications/boards.js

Adds check for missing profile on a user. This is common in other parts of the code, but these parts of the code missed it. This can happen if the user is created external to Wekan but shares the same MongoDB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2396)

Fix missing profile checks

---

models/cards.js

This closes #2330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2400)

Add partentId support on card web API

---

client/components/lists/listBody.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2401)

Added BIDI support to "Add Card" #884

---

client/components/lists/list.styl
client/components/lists/listHeader.jade
models/export.js
openapi/generate_openapi.py

2 quick fixes for 2 bugs: #2403 and #2328
As usual: Apache I-CLA signed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2406)

card count placement and export API functionality back

---

Dockerfile

Note: Apache I-CLA signed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2407)

Few fixes for Dockerfile

---

client/components/boards/boardHeader.jade

Changed the check for `currentUser.isAdmin` to `currentUser.isBoardAdmin`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2433)

 Bugfix: Allow BoardAdmin to create board rules. Fixes #2431

---

docker-compose.yml
server/cors.js

Adds support for CORS headers "Access-control-allow-headers" and "Access-control-expose-headers".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2429)

Add support for more CORS headers

---

client/components/rules/rulesList.jade

Buttons for adding rules to a board where missing for isBoardAdmin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2500)

Show buttons for isBoardAdmin #2431

---

server/rulesHelper.js

card.move needs boardId as first parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2502)

Fixed bug (rule doesn't move card to top/bottom) #2501

---

client/components/cards/cardDetails.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2508)

Inferface: Can move cardToTop/Bottom. Fixes #2289

---

models/users.js

Simple Workaround when you have more one value in Ldap mail attribut or SSO fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2519)

Add test if email attribute is an Array

---

client/components/cards/attachments.js

By default it will do nothing different.
However, if server owner started wekan by passing METEOR_SETTINGS variable as the following value
{"public":{"MAX_IMAGE_PIXEL":1024}} in production mode, or using --setings settings.json (containing above value) in development mode.
Then whenever a picture being uploaded (via computer or paste, or drag) would be checked and shrunken if its width or height, whichever is larger than 1024, and therefore, the uploaded base64 code would be smaller and save some storage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2544)

Add Feature: allow to shrink attached/pasted image

---

snapcraft.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2552)

Fix snap build-pacakges

---

snapcraft.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2553)

More snap fixes

---

client/components/settings/peopleBody.js
client/components/settings/settingBody.jade
client/components/settings/settingBody.js
client/components/users/userHeader.jade
client/components/users/userHeader.js
i18n/en.i18n.json
models/accountSettings.js

Adding one popup to confirm account deletion
Adding admin setting to prevent users to self deleting their account
English support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2573)

Additions for the account deletion feature

---

server/publications/boards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2587)

Fix board query

---

models/users.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2588)

Fix checking if API is enabled

---

client/components/boards/boardsList.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2602)

Fix null access with board body

---

models/customFields.js

Fix for issue #2586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2610)

Updated insert action for CustomFields API

---

client/components/main/editor.js
models/activities.js
server/notifications/email.js

- Enabling email can send out html content instead of plain text
- fixed a few issues related summernote enabled:
1. @ user couldn't send out email sometime, due to html format
2. @ user link wasn't able to show user info by clicking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2611)

Addfeature: Enable HTML email content for richer comment

---

client/components/cards/cardDetails.js
server/statistics.js

Send webhook when cardDetails is rendered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2620)

Webhook cardDetails onRendered

---

server/publications/boards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2628)

Fix mismatched queries

---

client/components/import/import.js
client/lib/popup.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2645)

Fixes #2638 importing trello

---

client/components/activities/activities.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2657)

Fix last label undefined

---

.devcontainer/Dockerfile
.devcontainer/build.sh
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.gitattributes

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2659)

Adds .devcontainer feature to debug and compile with vscode

---

.devcontainer/Dockerfile
.devcontainer/build.sh
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.vscode/launch.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2660)

Fixed endless compilation devcontainer and added debugging launch.conf

---

models/accountSettings.js
models/actions.js
models/activities.js
models/announcements.js
models/boards.js
models/cardComments.js
models/cards.js
models/checklistItems.js
models/checklists.js
models/customFields.js
models/integrations.js
models/invitationCodes.js
models/lists.js
models/org.js
models/orgUser.js
models/rules.js
models/settings.js
models/swimlanes.js
models/triggers.js
models/unsavedEdits.js
models/users.js
server/migrations.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2679)

Fixes #2596 incorrect date types for created & updated

---

client/components/cards/cardDetails.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2690)

Fix #2451 unable to drag select text without closing card details

---

server/publications/boards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2697)

Fix #2688 subcard selector

---

models/checklists.js

This PR fixes the handling of the items parameter in the Checklist item creation endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2747)

REST API: fix creation of Checklists (closes wekan/wekan#2746)

---

client/components/cards/cardDate.js

if no due-date timestamp is set => Gray
if end-date timestamp is younger than due-date timestamp => Green
if end-date timestamp is older than due-date timestamp => Red
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2779)

Card date received-date fix and end-date coloring change (simplify)

---

openapi/generate_openapi.py

Primary for fixing #2781 
I really should have put more debug output from the start, but the lazy me didn't.
Hopefully over time we'll get all corner cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2783)

Openapi gen fixes

---

client/components/cards/cardDetails.js

https://github.com/wekan/wekan/issues/2780
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2782)

fixed #2780

---

models/cards.js
models/checklists.js
server/authentication.js

Use Utils function to check user membership to board and his role.
Fix checkBoardAccess authentication check. (User is board member check was broken)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2854)

Allow card & checklist API creation for authorized board members

---

models/export.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2898)

fixed board export with attchment

---

client/components/rules/actions/boardActions.jade
client/components/rules/actions/boardActions.js
server/rulesHelper.js

Fixes #1996. Please review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2899)

Add rule action to move cards to other boards

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2937)

Fix docker-compose link

---

server/publications/boards.js
server/publications/users.js

See #1498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2948)

Make profile.initials available in publications

---

client/components/cards/subtasks.js

Referencing [1953](https://github.com/wekan/wekan/issues/1953)
Implements the changes suggested in [1953#issuecomment-604310679](https://github.com/wekan/wekan/issues/1953#issuecomment-604310679)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2976)

Create new subtasks in parent swimlane

---

client/components/main/layouts.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2988)

Update layouts.js for zh-TW language name

---

client/components/main/layouts.js
client/components/users/userHeader.js

related to https://github.com/wekan/wekan/pull/2988
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2990)

Correct zh-TW language name (the right way)

---

client/components/notifications/notificationsDrawer.jade
client/components/notifications/notificationsDrawer.js
client/components/notifications/notificationsDrawer.styl
i18n/en.i18n.json
models/activities.js
models/users.js

@xet7 
here is the PR with the scheduler to clean up read notifications.
I also added a button to manually remove all read notifications, and a fix to prevent users form getting notifications for their own actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/2998)

Notifications Refinements

---

models/users.js

@xet7 
Sorry I let this slip through.  Basically the same issue that we had in my first PR. This should fix it though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3010)

fix error in notifications cleanup cron

---

client/components/cards/labels.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3015)

Fix <p> margin in card labels

---

client/components/cards/cardDetails.styl

Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3024)

Improve card layout on mobile devices

---

client/components/boards/boardArchive.js
client/components/boards/boardsList.jade
client/components/boards/boardsList.js
client/components/boards/boardsList.styl
client/components/cards/cardDetails.js
client/components/lists/listBody.js
client/components/rules/actions/boardActions.js
client/components/settings/settingBody.js
client/components/sidebar/sidebar.js
models/boards.js
models/users.js
server/migrations.js
server/publications/boards.js

Preview: https://youtu.be/Wxl94l7s2Kg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3027)

Sortable boards

---

client/components/cards/checklists.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3030)

Pre-fill the title of checklists (Trello-style)

---

client/components/boards/boardsList.js
client/components/cards/cardDetails.js
models/cards.js

Found by using the command `meteor npm run lint:eslint:fix`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3031)

Multiple lint issue fixes

---

client/components/main/popup.styl
client/components/users/userHeader.jade
client/components/users/userHeader.js
client/lib/datepicker.js
i18n/en.i18n.json
models/users.js
public/api/wekan.yml

Implements https://github.com/wekan/wekan/issues/2535.
Screenshots:
It is a first version and hopefully it makes sense what I have done :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3032)

Implement option to change the first day of the week in user settings

---

.babelrc
.eslintrc.json
package-lock.json
package.json

Enables fancy Javascript language features like optional chaining,
for developer happiness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3034)

Add babel to build chain and linter

---

client/components/users/userHeader.jade
client/components/users/userHeader.js

Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3039)

Use only one 'Apply' button for applying the user settings

---

docker-compose.yml

webbroser -> web browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3044)

Fix comment typo in docker-compose.yml

---

client/components/boards/boardBody.js
client/components/boards/boardsList.js
client/components/cards/cardDetails.js
client/components/cards/checklists.js
client/components/lists/list.js
client/components/swimlanes/swimlanes.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3045)

Follow-up for https://github.com/wekan/wekan/pull/3040

---

client/components/boards/boardsList.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3046)

Partially fixes https://github.com/wekan/wekan/issues/3041

---

client/components/cards/cardDetails.js
client/components/lists/listBody.js
client/components/lists/listHeader.js
models/cards.js

@xet7 Can you please write the code for the popups (see `TODO popup` comments), because I don't know the code well enough. Another point I'm not sure about is whether the check for the linker cards should take place on the server or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3068)

[WIP] Some fixes

---

client/components/boards/boardColors.styl
models/boards.js
server/migrations.js

This PR resolves #2592 issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3098)

Added natural theme

---

client/components/activities/activities.js
client/components/cards/cardDetails.js
models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3111)

Minor fixes

---

client/components/boards/boardBody.js
client/components/cards/cardDetails.js
client/components/rules/actions/cardActions.js
client/components/sidebar/sidebar.js
client/lib/dropImage.js
client/lib/pasteImage.js
models/checklists.js
models/settings.js
server/rulesHelper.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3112)

Some fixes suggested by deepcode.ai

---

client/components/sidebar/sidebarFilters.js
client/components/swimlanes/swimlanes.jade
models/cards.js

This fixes https://github.com/wekan/wekan/issues/3119.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3120)

Fix move selection

---

models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3121)

Fix Python API generation

---

client/components/cards/cardCustomFields.jade
client/components/cards/cardCustomFields.js
client/components/cards/minicard.jade
client/components/cards/minicard.js
client/components/sidebar/sidebarCustomFields.jade
client/components/sidebar/sidebarCustomFields.js
i18n/en-GB.i18n.json
i18n/en.i18n.json
models/customFields.js

This PR implements #3082.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3123)

Add the 'Currency' Custom Field type

---

models/csvCreator.js
models/export.js
models/exporter.js

Resolves: https://github.com/wekan/wekan/issues/395
Fixes issue with exporting Votes to CSV/TSV and adds export functionality supporting exporting/importing the new currency custom field to CSV
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3128)

Fix vote export & export/import currency custom field to CSV/TSV

---

client/lib/exportHTML.js
models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3131)

Added an API to get the cards for a specific custom field value

---

models/settings.js

Fixes: 6e088af3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3135)

Fix email verification in `sendSMTPTestEmail`

---

models/users.js
package-lock.json
package.json

Try to Fix Registration broken "Templates board id is required" with ugly hack. If it works, ugly becomes beautiful.
Thanks to marc1006 !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3140)

Fix Registration broken "Templates board id is required"

---

.meteor/versions
packages/markdown/marked/docs/USING_ADVANCED.md
packages/markdown/marked/docs/USING_PRO.md
packages/markdown/marked/docs/demo/demo.js
packages/markdown/marked/docs/demo/worker.js
packages/markdown/marked/docs/index.html
packages/markdown/marked/lib/marked.esm.js
packages/markdown/marked/lib/marked.js
packages/markdown/marked/package-lock.json
packages/markdown/marked/package.json
packages/markdown/package.js

Update `markedjs` to commit
https://github.com/markedjs/marked/commit/7b3036f8c0440cfd003ce47dd6e1a92af0f5e822.
This fixes the issue https://github.com/wekan/wekan/issues/3148.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3149)

Update `markedjs` package

---

models/cards.js

This fixes the issues https://github.com/wekan/wekan/issues/2404 and
https://github.com/wekan/wekan/issues/2970 but only if the target board doesn't differ
from the source board.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3154)

Copy the labels only if the target board is different

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl
i18n/en.i18n.json
models/users.js
public/api/wekan.yml

+ add user option to hide finished checklist items
+ strikethrough checked items
+ it's a global user option to hide finished checklist items - is this okay?
As far as I can see, in https://github.com/wekan/wekan/issues/1848 this option is per checklist and not global
Partially implements https://github.com/wekan/wekan/issues/1848.
Option not checked:
Option checked:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3167)

WIP: Checklists

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/minicard.jade
client/components/cards/minicard.styl
models/cards.js

A added the possibility to start a vote via API edit_card.
And added some better visibility to see what was voted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3170)

added start vote via API edit_card

---

client/components/rules/ruleDetails.jade
i18n/en.i18n.json

This PR includes 2 new strings to translate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3244)

Add Trigger and Action headers in Rule Details

---

docker-compose.yml

Hi, I just followed the instructions on setting up OAUTH2 with nextcloud but struggled until I found the missing information. 
I think this should be added in the documentation. Also, the nextcloud URL seems outdated, so I've added `index.php`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3248)

Improving documentation for nextcloud integration

---

client/components/cards/cardDetails.styl

Fix for: https://github.com/wekan/wekan/issues/3241#issuecomment-689990808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3264)

fix(card): fix card scrollbar on windows

---

package-lock.json
package.json

```console
$ docker build -t wekanteam/wekan .
[...]
$ docker-compose up
[...]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3270)

Use forked & updated version of gridfs-stream

---

client/components/cards/cardCustomFields.jade
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.styl
client/components/cards/checklists.jade
client/components/cards/subtasks.jade
client/components/lists/listBody.jade
i18n/en.i18n.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3271)

Design improvements in templates, card details and custom fields

---

client/components/boards/boardColors.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3312)

Fix Modern theme board canvas background

---

client/components/boards/boardColors.styl
models/boards.js
server/migrations.js

This PR try resolves #3333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3335)

Add 'Modern Dark' theme

---

client/components/activities/activities.jade

Allow Board Admins to edit and delete user comments
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3340)

board admin can edit and delete comments as well #3201

---

client/components/cards/cardDetails.js
client/components/cards/checklists.jade
client/components/cards/checklists.styl
client/config/blazeHelpers.js
client/lib/utils.js

Add drag handles for checklists on mobile view or if Desktop drag handles are enabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3341)

Drag handles for checklist #3240

---

client/components/boards/boardColors.styl

Improvements Modern Dark Theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3344)

Improvements Modern Dark Theme

---

client/components/boards/boardColors.styl

Some more small improvements to Modern Dark theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3346)

Some more small improvements to Modern Dark theme

---

client/components/boards/boardColors.styl

Minor improvements to Modern Dark theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3348)

Minor improvements to Modern Dark theme

---

client/lib/keyboard.js
i18n/en.i18n.json

This PR resolves #2883
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3354)

Add keyboard shortcut for search

---

i18n/en-GB.i18n.json
i18n/en.i18n.json
models/avatars.js

72KB is too small, even if you compress the image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3360)

Increase avatar size

---

client/components/boards/boardColors.styl

Modern Dark: card details as lightbox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3359)

Modern Dark: card details as lightbox

---

client/components/notifications/notificationIcon.jade

This PR resolves partially #3363
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3366)

Added date notification icons

---

client/components/activities/activities.js

This PR fixed PR #3372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3373)

Fixed end date return

---

client/components/activities/activities.jade
client/components/activities/activities.styl

This PR implements bold in member names, padding in activity and enlarges activity avatars
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3374)

Improvements in activities design

---

client/components/cards/checklists.js

- also using for autoresize now:
verron:autosize
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3411)

New Checklistitems are now autoresized too

---

client/components/main/myCards.jade
client/components/main/myCards.js
client/components/main/myCards.styl
client/lib/utils.js
i18n/en.i18n.json

* Added ability to sort cards by due date
* Was unable to get Popup.open() to open a selection popup, so resorted to a simple toggle between the screens.  If it could be debugged, the popup is probably better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3419)

My Cards add Due Date sort

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3421)

fixed badges

---

client/components/main/globalSearch.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3440)

Global Search: translate color names

---

models/cards.js

This should fix #3367
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3442)

Cards, custom fields are displayed in alphabetic order

---

client/components/cards/cardCustomFields.jade
client/components/cards/cardCustomFields.js
client/components/cards/cardDate.jade
client/components/cards/minicard.jade
client/components/forms/forms.styl
models/customFields.js
models/trelloCreator.js
trello/trello-project100.json

Import custom fields from Trello (#3097)
Adds a new custom field type of checkbox to make importing Trello checkbox fields easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3444)

Trello import custom fields #3097

---

models/cards.js

Check the *to* board to see if it has a custom field of the same name
and type. If it does use that custom field definition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3449)

Issue #3445 Custom field definitions duplicated on copy and move

---

client/components/lists/listHeader.jade
client/components/lists/listHeader.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3468)

Limited number of cards highlighting to true overbooking.

---

client/components/main/globalSearch.js

Issue #2074 
Search operators with capital letters are reported as invalid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3470)

Fix for search operators with uppercase letters

---

client/components/sidebar/sidebarCustomFields.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3472)

Add checkbox as an option to custom field create dialog

---

models/boards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3473)

Boards.copyTitle - escape string used in regex

---

client/components/main/myCards.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3474)

Display My Cards lists using inline-grid

---

client/components/main/myCards.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3475)

Use simple border at My Cards

---

models/boards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3476)

Bug fix: import regex escape function

---

packages/wekan-ldap/server/ldap.js

See also: https://github.com/wekan/wekan/issues/3482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3483)

Reject by default LDAP connections not authorized via CA trust store

---

client/components/main/editor.js
packages/markdown/src/template-integration.js

Please add custom URL schemes for SolidWorks PDM (conisio:) and abas ERP (abasurl:) to wekan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3487)

additional URL schemes #3218

---

models/users.js

In Japanese name, current method cause an error, "undefined.join()".
I copied initial creation method from User's method.  This worked on my env for English and Japanese.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3489)

changed method to create initials same as others for new user of oidc

---

client/components/main/header.jade
client/components/main/header.styl

**Improvements mobile view:**
- Quick Access scrollable
- Notification and Avatar doesn't overlap anymore
- Show all boards at Quick Access
**Improvements desktop view**
- Quick Access scrollable if necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3491)

Mobile and Desktop have now the same Quick Access view + scrollable

---

client/components/boards/boardsList.js
models/boards.js
models/trelloCreator.js
models/wekanCreator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3499)

Create unique board names when importing

---

client/components/import/import.jade
client/components/import/import.js
models/customFields.js
models/wekanCreator.js
server/publications/users.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3500)

Fix some bugs when importing Wekan JSON

---

client/components/main/globalSearch.js
models/boards.js

Snap was not building with regexs defined using slashes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3505)

Use `new RegExp(...)` to define a regex

---

client/components/import/import.jade
client/components/import/import.js
client/components/import/import.styl
client/components/settings/peopleBody.jade
client/components/settings/peopleBody.js
i18n/en.i18n.json
models/users.js
server/publications/people.js
server/publications/users.js

Add an array field to `Users` to hold usernames from imported data.  It provides a text field for input with import usernames separated by commas or semicolons.
The data is stored in the `Users` collection in a new field `importUsernames`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3510)

Import user mapping

---

client/lib/utils.js

Fix for #3507
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3509)

Don't reload page when returning default sort

---

client/components/cards/minicard.styl
client/components/notifications/notification.styl
client/components/notifications/notificationsDrawer.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3516)

Avatar overlaped notifications

---

client/components/main/globalSearch.js
client/lib/i18n.js
models/boards.js
server/publications/cards.js

* Remove the i18n initialization code from an `autorun()` block
* Add some console statements to help with debugging production.
* Add functions to `Boards` for label colors and color mapping
Issue #2074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3519)

Hopeful fix for i18n not working in `onRendered()`

---

client/components/notifications/notification.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3523)

Notifications avatar overlaped at mobile view

---

models/users.js

Get userId  from username with REST API. Now get_user operation supports userId or username as param.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3530)

Add the ability to call get_user operation with username

---

client/components/cards/minicard.jade
client/components/cards/minicard.styl
client/components/users/userAvatar.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3532)

Red line below the avatar now correctly on FireFox #3515

---

client/components/main/header.jade
client/components/main/header.styl
client/components/notifications/notification.styl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3533)

Notifications, enable line wrapping #3527

---

client/components/lists/listHeader.js
client/components/users/userHeader.jade
client/components/users/userHeader.js

The spinner was't displayed at mobile view, so there was no chance to change it at mobile view.
I already mentioned that at #3465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3545)

Settings, "Show cards count" now works at mobile view too

---

models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3547)

Deleting a linked card blocked the parent board to load #3540

---

client/components/cards/minicard.styl

- fixes comment at #3515
https://github.com/wekan/wekan/issues/3515#issuecomment-777312174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3560)

Minicard, remove red line below member avatar icon

---

client/components/cards/cardDate.js
client/lib/datepicker.js

Fixes #3422 
I additionally noticed that the error message always said the date was wrong, have adjusted that as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3557)

Added possibility to specify hours in single digits in 24 hour format

---

client/components/main/header.jade
client/components/main/header.styl

Fixes #3558 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3559)

added padding

---

client/components/cards/cardCustomFields.js

Fixes #3436
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3564)

added replacement from comma to dot

---

client/components/boards/boardColors.styl

This PR resolves #3565.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3569)

Modern theme: Remove font color when the card has a color

---

helm/wekan/Chart.yaml
helm/wekan/templates/_helpers.tpl
helm/wekan/templates/deployment.yaml
helm/wekan/templates/secret.yaml
helm/wekan/values.yaml

Added secrets to the initial work of #3382 and added a default db name like in the docker compose file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3570)

Helm: Made SecretEnv a secret and added default mongodb name as Wekan

---

client/components/lists/listHeader.js

Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3572)

Lists, show also 0 cards at column description

---

client/components/boards/boardHeader.jade
client/components/boards/boardHeader.js
client/components/lists/listBody.js

Added sort feature for cards
This is just for viewing, sorting is not saved and will be removed once the page refreshes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3586)

added sort feature for viewing of cards

---

models/activities.js

Seems like a typo snuck in here, I have corrected it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3610)

Fix syntax typo

---

models/cards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3618)

Add sort to rest API

---

client/components/settings/settingBody.jade
client/components/settings/settingBody.js
i18n/en.i18n.json
models/settings.js
packages/markdown/src/template-integration.js
server/publications/settings.js

Editing the values is working but the values are not recognized by markdown-it right now.
next step would be to link this setting and urlschemes in https://github.com/wekan/wekan/compare/master...chrisi51:autolink-settings?expand=1#diff-c2805b3b8cba01d7af4a9a8419bb3b605e08d5290495aa6e25eda39ee8344ee3R25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3633)

Added autolinking settings in admin backend - tbc

---

models/customFields.js

I'm not sure what else I need to add in order for the REST API docs to be updated correctly, etc.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3593)

Add custom field editing to the REST API

---

client/components/boards/boardBody.js
client/components/cards/cardDetails.js

I've missed a couple of UI URLs in  #3635 . This PR adds relative URLs to:
* Child's parent card URL
* Calendar URLs 
Thanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3648)

Fixed Bug: Calendar & parent cards URLs used absolute URLs

---

client/components/settings/peopleBody.jade

This PR only changes the `edit` icon by the `plus-square` one for the links that create new item.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3671)

Replace edit icon by `plus-square` on new links

---

openapi/generate_openapi.py
public/api/wekan.html
public/api/wekan.yml
releases/rebuild-docs-install-deps.sh

esprima-python is now safe to use (https://github.com/Kronuz/esprima-python/pull/12)
And there was a new ArrowFunctionExpression used in db666eec65f7d869 that broke the python script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3672)

Fix openapi docs generation

---

models/export.js
models/exporter.js

As the first step I created a new entry on export.js with /api/boards/:id/attachments/:attachmentId/export
After that I moved to the top the Attachments.find checking if there is an attachmentId as a parameter on Exporter class.
The original behavior of the class was keeped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3673)

Included a new route to export (json) an attachment from a board.

---

config/router.js

Fix issue with blank page being displayed in *My Cards* if the user is not logged in.
Ref: #3655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3677)

Require signed-in user for My Cards, Due Cards, and global search #3655

---

models/cards.js
server/rulesHelper.js

Issue: #3703 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3706)

Bug fix: Rules for moving from list/swimlane

---

client/components/main/myCards.jade
client/components/main/myCards.js
client/lib/cardSearch.js
config/query-classes.js
server/publications/cards.js

* Rewrite routine for building the My Cards hierarchical list
* Use a separate publication for retrieving My Cards
* Fix bug with limit and skip projectsion
Ref: #3698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3708)

Bug fix for issue #3698

---

client/components/main/editor.js

All features apply to Rich Text Editor fields
- Add new button to insert a URL link
- Add new popover allowing you to edit existing URL links
- enable spell check
- allow client side grammerly extension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3720)

utilize summernote featureset

---

client/components/cards/cardCustomFields.js
client/components/cards/cardDate.js
client/lib/datepicker.js

- Fixes #3718
- intoduced by commit 4aee129cdc3cc9896e8dc0fdae248b3f83ab3977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3723)

Bugfix, date format not changed to local format

---

models/cards.js

Fix bug introduced in #3705
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3724)

Remove allowedValues from Cards.type schema

---

models/trelloCreator.js

Fix for issue #1569 Trello data without labels definition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3733)

Fix: Trello data without labels definition

---

client/components/main/dueCards.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3741)

Bug fix for Due Cards

---

models/exportExcel.js

swimlanes are added to a new column inside the excel file.
this address one concern brought up by 
https://github.com/wekan/wekan/issues/3754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3764)

cherry pick the excel export feature to add swimlanes to the output

---

client/components/cards/cardDate.js

For more details please check: https://github.com/wekan/wekan/issues/3766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3793)

Fix: BG color of StartDate

---

client/components/cards/cardCustomFields.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3849)

custom fields stringtemplate, autofocus the last input box

---

client/components/cards/cardDescription.styl

Same color at view and editing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3851)

Card Description has now the same color on editing

---

.devcontainer/Dockerfile
.devcontainer/docker-compose.yml
.dockerignore

Development in Docker Container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3852)

Development in docker container

---

client/components/lists/listBody.js

- When adding 1 card the custom fields are created. On all next cards the custom fields were not created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3856)

CustomFields were not created after adding 1 card

---

client/components/cards/cardDetails.js

Fixes: #3859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3861)

Manuel sort number 0 accepted

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/forms/forms.styl

See also here:
https://github.com/wekan/wekan/commit/8c572502436a2eb22bd1eb1e4069c1c9145e2070#commitcomment-52068781
For animation: I haven't used it yet, no idea at the moment how to do it right.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3863)

Card details maximize fixes

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
client/components/sidebar/sidebar.styl
client/components/users/userAvatar.jade
client/components/users/userAvatar.js
models/boards.js
models/users.js
server/publications/boards.js

As you can see it in the gif image below, I have finished working on points 1 and 3 of this comment (https://github.com/wekan/wekan/issues/802#issuecomment-859507286), i'm going to work on point 2.
Adding or removing organization and team from board:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3895)

Add or remove an organization and team from a board

---

client/components/boards/boardColors.styl

Small fixes for ModernDark theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3902)

Small fixes for ModernDark theme

---

.gitignore
helm/wekan/Chart.lock
helm/wekan/Chart.yaml
helm/wekan/requirements.yaml
helm/wekan/values.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3933)

Update helmchart, pin image version

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js

Hey @xet7,
this PR adds a search field to the member and assignee card popups in order to filter the members list to find a user more easily.
Please see the attached file for preview
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3942)

Feature: Searchfields for members and assignees card popups

---

server/publications/cards.js

Hey @xet7,
this fixes the global search and removes the unnecessary CardCommentReactions Document Class from it.
This should solve Issue https://github.com/wekan/wekan/issues/3947
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3949)

Fix: global search

---

client/components/boards/boardBody.jade
client/components/boards/boardBody.js
client/components/boards/boardsList.js

Fix bugs #3978 and #3979 (see gif image below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3981)

Fix bugs #3978 and #3979

---

CHANGELOG.md
README.md
SECURITY.md
meta/t9n-changelog/fi.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3993)

Links to devel branch are broken; use master instead

---

client/components/settings/peopleBody.jade
client/components/settings/peopleBody.js
client/components/settings/peopleBody.styl
package-lock.json
package-lock.json.orig
releases/delete-phantomjs.sh

Admin user has a possibility of adding a team to all selected Users in Admin panel page (see gif image below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3996)

[Admin panel / People] possibility of adding a team to all selected Users

---

client/components/lists/listHeader.jade
client/components/lists/listHeader.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/3999)

When list has just one card, to show 'card' instead of 'cards'

---

client/components/cards/cardDetails.js
client/components/sidebar/sidebar.js
models/boards.js
package-lock.json

Add or remove team members as board members when adding or removing team from board (see gif image below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4000)

Add / remove team members as board members when adding / removing team from board

---

models/boards.js
models/cards.js

Fix linkedCard and linkedBoard date setting [#2930](https://github.com/wekan/wekan/issues/2930)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4002)

Fix : Linked card cannot change date #2930

---

client/components/main/layouts.js
client/components/settings/settingBody.jade
client/components/settings/settingBody.js
i18n/en.i18n.json
i18n/fr.i18n.json
models/settings.js
server/publications/settings.js

I added a setting in admin panel page (Settings / Layout), so that an admin user can customize OIDC button text (see gif image below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4011)

[Admin panel / Settings / Layout] Customize OIDC button text

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
models/export.js
models/exportExcel.js
models/exporter.js
models/server/ExporterExcel.js

Fix : export CSV, TSV and XLS translation
Feature : add export CSV with semicolon separator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4028)

Export CSV, TSV and XLS

---

client/components/sidebar/sidebarFilters.jade
client/components/swimlanes/swimlanes.jade
client/components/swimlanes/swimlanes.js
client/lib/filter.js
models/swimlanes.js

- Filter List by Title : prevent showing only the list title
- Hiding empty lists in Swimlane view (#3159)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4108)

Try to fix : Filter List by Title - Hide empty lists in Swimlane view

---

client/components/settings/informationBody.jade
i18n/en.i18n.json
server/statistics.js

- Add NodeJS heap statistics (`v8.getHeapStatistics()`)
- Add NodeJS memory usage (`process.memoryUsage()`)
See #3585 (comments)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4118)

Add NodeJS Statistics

---

client/components/activities/activities.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4128)

Card detail popup loads now comments if opened from board search

---

models/server/ExporterExcel.js

Fix #3589
See [#4119](https://github.com/wekan/wekan/pull/4119) comments
Minor layout improvement (_cell alignment, empty date case_)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4135)

Fix: Impossible to export board to excel where title exceeding 31 chars

---

.devcontainer/Dockerfile
.devcontainer/docker-compose.yml
Dockerfile
docker-compose.yml
torodb-postgresql/docker-compose.yml

- Fix failed export, #4089 
- /etc/timezone isn't available on all Linux systems, #4131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4137)

Docker fix failed export and timezone

---

client/components/cards/cardDetails.js

Close card details popup:
- on card color remove
- on card move to bottom
- after card delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4138)

Card popup close color remove move bottom delete

---

client/components/activities/activities.jade

add cancel button to comment edit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4139)

Comment edit has now a cancel button

---

client/components/cards/cardDetails.js
client/components/cards/resultCard.js
client/components/lists/listBody.js
client/components/sidebar/sidebarSearches.js
client/config/blazeHelpers.js
client/lib/utils.js
config/router.js
models/users.js
server/publications/cards.js

At global search:
- load description symbol on minicard
- load all data of the card on popup open (fix #4129)
- card details popup fields are modifiable if the user has the permission
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4142)

Global search load card details

---

client/components/boards/boardsList.jade
client/components/boards/boardsList.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4149)

Boards view has now drag handles at desktop view if drag handles are enabled

---

client/components/cards/labels.js
models/cards.js

Fixes: #4156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4170)

Fixed label popup at desktop view (add and remove labels)

---

client/components/cards/labels.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4176)

Show helper at label drag/drop if label popup opened from card details popup

---

client/components/main/header.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4180)

App reconnect link wasn't clickable

---

.meteor/packages
.meteor/versions
client/components/boards/boardsList.js
client/components/cards/labels.js
client/components/lists/list.js
client/lib/jquery-ui.js
client/lib/tests/Utils.tests.js
client/lib/utils.js
package-lock.json
package.json

- Updated jquery-ui to latest version
- The core jquery-ui update should also fix other related issues to drag/drop (maybe e.g. #3415, #476)
- The list scrolls now on minicard dragging
- The screen scrolls now on minicard dragging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4181)

Drag drop jquery-ui update + screen and list scroll

---

client/components/swimlanes/swimlanes.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4183)

List adding has now a cancel button

---

client/components/cards/cardDetails.js
client/lib/utils.js

Fixes: #4155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4184)

Copy card url works now again

---

client/components/activities/comments.styl
client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/main/editor.jade
client/components/main/editor.js
client/components/main/editor.styl
client/lib/utils.js
i18n/en.i18n.json

adding a copy button to most textarea fields, here in the example the description field on the mincard (green highlighted)
This will copy the content of the textarea to the clipboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4185)

Add copy text button to most textarea fields

---

client/components/settings/settingBody.styl

- Fixes: #4159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4186)

Settings, add some space between radio buttons

---

client/components/cards/cardCustomFields.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4189)

CustomFields Currency, autofocus on edit

---

i18n/en.i18n.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4190)

Sidebar Member Settings Popup has now a Popup title

---

client/components/cards/attachments.jade
client/components/cards/attachments.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4191)

Attachments, show file size in KB in card details

---

client/components/lists/list.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4193)

Moving many cards with multi selection drag/drop to another list keeps the card order

---

client/components/sidebar/sidebarFilters.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4194)

Sidebar multi selection actions keep now the card sorting (cards moving, cards to archive etc.)

---

client/components/lists/list.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4201)

Dragging minicards scrolls now vertically at the end of the screen

---

client/components/lists/list.styl
client/components/lists/listHeader.jade

Fixes: https://github.com/wekan/wekan/pull/4195#issuecomment-981878664
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4203)

List title doesn't overlap with hamburger menu anymore

---

client/components/sidebar/sidebarArchives.js
client/components/swimlanes/swimlanes.js

Fix #4216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4221)

Fix : Clicking to view Lists or Swimlanes Archive adds temporarily many empty Lists to board

---

client/components/boards/boardColors.styl

Fix mobile card details for Modern Dark theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4240)

Fix mobile card details for Modern Dark theme

---

models/users.js

Fix issue #4222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wekan/wekan/4245)

fix issue #4222

---

models/cardComments.js

Fix: boardAdmin can't edit or delete others comments on cards #4237

---

models/org.js
models/team.js
models/users.js

At Admin Panel (People view), edit team/org DisplayName now update users.teams.teamDisplayName / users.orgs.orgDisplayName

Edit team/org now update users.teams.teamDisplayName / users.orgs.orgDisplayName

---

client/components/lists/listBody.js
client/components/main/editor.js
models/activities.js

Fix user mentions (see #4057):
- mention regex: add hypen `-`
- user mentions now return `@username (full name)`
New feature
- auto-complete username when creating new cards (addCardForm) now returns fullname if exists

Fix user mentions

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
models/users.js

Card Details > Actions Menu > Move Card > The selected field values are remembered on clicking save and selected the next time the dialog open's again

Move copy card remembers the last confirmed field values

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl
client/components/forms/forms.styl
i18n/en.i18n.json

Add checklist item - each line becomes new item

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/checklists.styl
models/checklists.js

Add progress bar to checklist

---

client/components/cards/cardDetails.js
client/components/cards/checklists.js

Move Checklist and copy/move card popup restores now the values too if it was moved onto another board

Move checklist and card popup restore last selected board value

---

client/components/boards/boardColors.styl

Fix Layout "Modern Dark", Card Color, List Header and mouse hover

---

models/cards.js
server/publications/boards.js

Fix comments not loading on cardType-linkedBoard

---

client/components/cards/checklists.js

fix can't add Checklist on cardType-linkedBoard

---

client/components/activities/comments.js

Fix comments for cards that link to a board are not shown

---

client/components/lists/list.styl
client/components/swimlanes/swimlanes.js
client/components/swimlanes/swimlanes.styl

Lists now moveable when swimlane requires scrolling

---

client/components/cards/checklists.jade
client/components/cards/checklists.js
i18n/en.i18n.json
models/users.js

Copy checklist

---

client/components/boards/boardColors.styl

Not everybody loves rounded corners ... :-) 
This PR reverts the rounded corners on moderndark theme and fine tunes some colors on lists and minicard.

Revert rounded corners minicard on moderndark theme

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
i18n/en.i18n.json
models/boards.js
server/migrations.js

- This is especially useful for mobile view, but also allow's a quick list change at desktop view
- This option is also configureable at the board settings menu

Adding list select at card details

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.js
client/components/cards/cardDetails.styl
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js

Fix copy move card

---

client/components/cards/cardDetails.styl

Fixing the header while scrolling to have always all actions in the header available...

Card details, fix header while scrolling

---

models/boards.js

Fix had an unnecessary "[1]" when import a board
See #4401

 fix Boards.uniqueTitle not working as expected - part 2

---

client/components/import/import.js

fix Import Done Button do not redirect

---

client/components/boards/boardsList.js
client/components/lists/listBody.js

"Duplicate Board" and "Create board from template" now open board

Fix Duplicate board and create board from template doesn't open board

---

server/00checkStartup.js

Better error message layout if Wekan can not start

---

client/components/cards/cardDetails.jade
client/components/cards/cardDetails.styl
client/components/cards/subtasks.jade
client/components/cards/subtasks.js
client/components/cards/subtasks.styl
i18n/en.i18n.json

Changed maximized card header to use width 100%. Added border to split left and right sides.

UI improvements on maximized card header

---

client/components/cards/minicard.jade
client/components/cards/minicard.styl
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
i18n/en.i18n.json
models/boards.js
public/api/wekan.yml
server/migrations.js

Show description text on minicard

---

client/components/cards/minicard.jade

Added HTML tags escape to description on minicard.

---

client/components/boards/boardColors.styl

this should fix [this issue](https://github.com/wekan/wekan/issues/4465)

deployed a stylefix for #4465 (this time)

---

client/components/boards/boardColors.styl

improved:
- description colors & background on minicards for exodark and moderndark theme
- attachment colors & background on attachments in the carddetails for exodark and moderncark theme
- activity colors in the carddetails for the exodark and moderndark theme
- checklist colors, background & hoverstyles for the exodark theme

this should fix everything talked about in #4472

---

client/components/cards/attachments.jade
client/components/cards/attachments.js
imports/i18n/data/en.i18n.json
models/attachments.js
models/cards.js
models/lib/fileStoreStrategy.js

partially resolves: #2099
mentioned here too: #4463

Attachment rename

---

server/00checkStartup.js

00checkStartup, on error give more details on current user which run's wekan

---

.meteor/packages
.meteor/versions
client/components/cards/cardDetails.js
client/components/import/import.jade
client/components/import/import.js
client/components/settings/peopleBody.js
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
client/components/users/userAvatar.js
client/lib/popup.js
models/users.js

This PR updates matteodem:easy-search from [version 1](https://github.com/matteodem/meteor-easy-search/tree/gh-pages/_v1docs) to the newer [version 2 api](https://matteodem.github.io/meteor-easy-search/), which should fix the issues mentioned in https://github.com/wekan/wekan/issues/4530.

Fix and update easysearch

---

client/components/boards/boardBody.js
client/components/boards/boardsList.jade
client/components/boards/boardsList.js
client/components/cards/cardDetails.js
client/components/cards/checklists.jade
client/components/cards/checklists.js
client/components/cards/labels.jade
client/components/cards/labels.js
client/components/cards/minicard.jade
client/components/lists/list.js
client/components/lists/listHeader.jade
client/components/swimlanes/swimlaneHeader.jade
client/components/swimlanes/swimlanes.js
client/config/blazeHelpers.js
client/lib/tests/Utils.tests.js
client/lib/utils.js

Changed calls to isMiniScreen to isTouchScreen where drag handles are initialized, should fix the issues with large screen tablets like in [ #4569](https://github.com/wekan/wekan/issues/4569)

Set drag handle on touch screen not miniscreen

---

client/components/boards/boardsList.js

fixed list sorting on all boards page

fixing issue #4634

---

.meteor/packages
.meteor/versions
client/components/boards/boardsList.css
client/components/cards/attachments.jade
client/components/main/layouts.css
models/attachments.js
package-lock.json
package.json
public/css/reset.css

Meteor files 2.2.1 fixes + attachment view

---

.meteor/packages
models/attachments.js
models/avatars.js

Thanks to @dr-dimitru
https://github.com/wekan/wekan/pull/4638#issuecomment-1217883870
https://github.com/veliovgroup/Meteor-Files/commit/00ab6f723b84eb596b366c5d26e6981a00377809

Attachment using new feature of Meteor Files 2.3.0

---

client/components/cards/cardDetails.jade

Move/Copy Card dialog didn't set the last selected board right

---

server/00checkStartup.js

fixes: https://github.com/wekan/wekan/issues/4566#issuecomment-1231906040

00checkStartup, userInfo was missing

---

Dockerfile
docker-compose.yml

per conversation in https://github.com/wekan/wekan/pull/4663#issuecomment-1233520117, proposing we revert the change made in PR-4663

Willman42 revert pr 4663

---

client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js

Added tab view to board members (people, orgs and teams)

---

client/components/cards/checklists.jade

Now screen reader read if a checklist item is checked or not.

Add ARIA in checklist items

---

models/server/metrics.js
models/users.js
server/publications/users.js

Route "/metrics" will be used to get those datas and "WEKAN_METRICS_ACCEPTED_IP_ADRESS" environment variable must be settled with a comma separated list of trusted ip address

Added a possibiliy of getting some wekan metrics datas

---

models/server/metrics.js

Metric key names are now prefixed with "wekan_"
I added a metric to have the top 10 boards with more activities

feat(wekan metrics): rename metrics key and add a new one

---

models/users.js

If someone lost token, then admin user should be can delete a user token.

Add delete token api

---

client/components/lists/listHeader.js

Hi, @xet7!
I am trying to fix this: https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-r-open-source-kanban-board-with-mit-license/aTYCef9diZA7fo5ps

Fix: changing list color reloads webpage

---

client/components/main/layouts.jade

add "use-credentials" directive to site.webmanifest request

---

client/components/boards/boardColors.css

* Smaller column header on desktop viewport
* Better alignment column header on mobile viewport
* Improvements to padding on pop-up card on mobile viewport
* Less margin on header icons on mobile viewport so it fit's in one line on commom mobile viewports
* Better align drag handle options on desktop viewport

Small improvements modern-dark theme

---

imports/i18n/data/de.i18n.json
imports/i18n/data/en.i18n.json
models/avatars.js

Avatar upload was broken if no size is configured

---

models/users.js

**Fix for API calls add_board_member which was not working correctly.**
- isWorker added to list of parameters (Note: API docs also needs to be updated)
- board.setMemberPermission: required the param: isWorker
- Previous error in try clause JsonRoutes.sendResult updated to: JsonRoutes.sendResult(res, { code: 200, data }); in order to return expected results.
Note: API doc needs to be updated description column action row should read: the action (needs to be set to "add")
**Fix for API call remove_board_member which was returning an empty object.**
- JsonRoutes.sendResult updated to: JsonRoutes.sendResult(res, { code: 200, data })

Fixes broken add_board_member API and return value for remove_board_member

---

client/components/lists/list.css

fixes this issues:
- #4033
- #4032
- #3415
- #1887
related to this discussion:
- #4868

get card drag/drop working for empty swimlanes

---

client/components/sidebar/sidebarFilters.jade
client/components/sidebar/sidebarFilters.js
client/lib/filter.js
imports/i18n/data/en.i18n.json

This PR solves one demand on #4881

Added 'next week' due date filter

---

models/cards.js
models/checklists.js

https://github.com/wekan/wekan/issues/4562
also, edit values for specific customfields on the card.

Add @operation new_checklist_item

---

client/components/boards/boardBody.css
client/components/boards/boardBody.js

Feature from: https://github.com/wekan/wekan/issues/2687 , create card on calendar view on first swimlane and first list with duedate the date of the clicked date.

Create Card on Calendar View

---

client/components/boards/boardBody.js
models/cards.js

Fix for the Create Card at Calendar

---

client/components/boards/boardBody.css
client/components/boards/boardBody.js

https://github.com/wekan/wekan/issues/2687#issuecomment-1545836231
https://github.com/wekan/wekan/issues/2687#issuecomment-1545850281
Added X button to close
Added translations for create card at calendar

Fixes for Create Card at Calendar

---

client/components/swimlanes/swimlanes.jade
client/components/swimlanes/swimlanes.js
imports/i18n/data/en.i18n.json

Hi @xet7! 
Maybe help to create new lists on boards in desired position.
#4909

Added list position when create a new list on board

---

client/components/cards/minicard.jade
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
imports/i18n/data/en.i18n.json
models/boards.js
public/api/wekan.yml

Added option to show/hide cover attachment on minicard

---

client/components/swimlanes/swimlaneHeader.jade

dded icons to swimlane action popup

Added icons to swimlane action popup 

---

client/lib/filter.js

Fix due date filter for next and this week.

---

Dockerfile

- curl is already installed at the top of Dockerfile

docker build was broken because of wrong curl install

---

client/components/lists/list.js

especially on mobile view the drag/drop list scroll speed is too fast

reduce list scroll speed while drag/drop the minicard

---

models/csvCreator.js

Fix card creation. Now date fields are checked if they are empty.

---

client/components/cards/minicard.js

Minicard didn't show the assignee

---

models/cards.js

Commit to issue https://github.com/wekan/wekan/issues/5038

Fix get_board_cards_count

---

client/components/main/layouts.css
client/components/main/layouts.jade
client/components/main/layouts.js
client/components/settings/connectionMethod.js

This contains a few code cleanups for the login methods and fixes the dangling OR issue.
It is not entirely clear to me why some bits are in the `layout.js` and some others seemingly related in the `connectionMethod.js`

Login layout code cleanup

---

models/cards.js

Fix assignees description

---

models/customFields.js

Fix return value of edit_custom_field_dropdown_item

---

client/components/main/layouts.js
client/components/settings/connectionMethod.js

The connectionMethod component only deals with the authentication method select input.
Fixes #5048

Move authentication UI handling in correct place

---

models/swimlanes.js

Fix edit_swimlane

---

client/components/main/layouts.js
client/components/settings/connectionMethod.js

Login layout fixes 2

---

client/components/cards/attachments.js

Previously when clicking on attachments that cannot be previewed, such as eml files, a blank preview still opened.
This PR fixes this by not opening the preview if support for that file type is not implemented.

Do not open preview for attachments that cannot be previewed

---

client/components/swimlanes/swimlaneHeader.js
client/components/swimlanes/swimlanes.jade
client/components/swimlanes/swimlanes.js
models/users.js

Fix #5057
I haven't tested this yet, but I think this could be a simple solution...

Make default swimlane auto-height

---

client/components/cards/labels.js

label drag/drop (reorder labels) works now again

---

client/components/cards/attachments.js

Added ability to left/right swipe attachments and close the attachment viewer by swiping up, closes #5074

Add attachment swiping

---

client/components/settings/settingHeader.jade
client/components/settings/translationBody.css
client/components/settings/translationBody.jade
client/components/settings/translationBody.js
config/router.js
imports/i18n/data/en.i18n.json
imports/i18n/tap.js
imports/reactiveCache.js
models/translation.js
server/publications/translation.js

Hello @xet7, I've added the new function to add custom translation strings as you recommended in issue #5065.
Please check it and merge it.
Regards,
Yevhenii

Added new function to add cumstom translation strings on Admin panel

---

imports/i18n/tap.js

I replace the source code using Translation model directly with reactiveCache. #5000

Corrected source code so that it works correctly with reactiveCache

---

client/components/cards/attachments.js
client/components/cards/cardDetails.jade

This PR fixes broken attachment preview in safari.
Closes #5042

Fix broken attachment preview in safari

---

imports/reactiveCache.js

- it's not related to any known bug (as far as I know)
- it's only a good coding style to have default parameters

ReactiveCache, use default parameters

---

client/components/cards/attachments.css

Preview should now properly display very tall images.
closes #5089

Correctly display preview for very tall images

---

packages/wekan-oidc/oidc_server.js

Automatically add a user to a default board after oidc login.
We have this usecase where we'd like our users to automatically be added to a board after login through an oidc provider. This approach tries to add the user to the given board after each login. 
Thanks for considering it.

Proposal: default board for users

---

models/translation.js

This pull request is the soulution for issue #5102.

make available translation text to set empty string

---

server/notifications/outgoing.js

This condition is needed for addressing issue #4388.

Added a condition to filter unwanted webhooks

---

models/boards.js

Active members list now is ordered

---

packages/wekan-fontawesome/package.js

Add all characters

---

packages/wekan-ldap/server/ldap.js

Fully replace bunyan with meteor/logging for the LDAP logger (fixes issue #5156)

Fix LDAP login (#issue 5156)

---

client/components/boards/boardBody.css
client/components/boards/boardBody.jade
client/components/cards/cardDetails.css
client/components/cards/cardDetails.js

Open card details always in the middle of the screen

---

client/components/notifications/notificationsDrawer.jade
imports/reactiveCache.js
models/users.js

Notifications are now displayed correctly again

---

imports/reactiveCache.js

ReactiveMiniMongoIndex for Server-Side

---

Dockerfile

Add label org.opencontainers.image.source

---

docker-compose.yml
models/boards.js
models/swimlanes.js

Updated swimlane webhook added restore and change title webhook. Updated board webhook with changed title.

Updated swimlane (restore and changed title) and board (changed title) webhooks 

---

api.py

Update api.py Add createlabel

---

api.py

Will delete all cards from Swimlanes automatically, will retrieve automatically all list id and delete everything.

Update api.py Deleteallcards

---

client/lib/keyboard.js
imports/i18n/data/en.i18n.json

Filter assignees with shortcut 'a'.
Feature Request by me: #5316

Add shortcut to filter by assignees

---

api.py
models/boards.js

Test for me through api.py => OK
Did not regenerate ```public/api/wekan.(html|yml)```.

Add API to copy board

---

docs/wekan.wiki/New-card-with-Python3-and-REST-API.md

Clarify role and usage of api.py. Informations I would have liked to find.

Clarify usage of api.py

---

client/components/boards/boardColors.css

Small tweaks to moderndark theme

Small tweaks to moderndark theme

---

Dockerfile
docker-compose.yml

"version" is obsolete, and using a heredoc for long RUN commands both looks and writes much better.
Additionally some compose comments are wrong - https://github.com/wekan/wekan/blob/3f28c0dd227fee70d3a1aae0513cb736178a634b/docker-compose.yml#L12 - but am unsure what should actually be there.

Improve Docker files

---

client/components/lists/list.css
client/components/swimlanes/swimlanes.css

Fixes one of the issues raised in #5382 and partially fixes another one.

Fix white List color and define Silver in CSS instead of leaving it unset

---

models/lists.js
models/swimlanes.js

Fixes one of the issues raised in https://github.com/wekan/wekan/issues/5382

Allow `silver` color to be set in List and Swimlane

---

docs/wekan.wiki/Install-latest-Wekan-release-on-Uberspace.md
find-replace.sh

also remove some extra whitespace in MD doc
https://www.shellcheck.net/wiki/SC2196

Swap deprecated `egrep` for `grep -E`

---

.devcontainer/Dockerfile
Dockerfile

Over the years both Dockerfile's changed many times. In the end they nearly have the same goal, but were build differently.
Now, both Dockerfile's are mostly the same build, except the places which needs to be different.

Dockerfile production and dev same build

---

client/components/boards/boardColors.css
config/const.js
server/migrations.js

Hello!
I added two new themes which are more clean and modern looking.

Added "Clean dark" and "Clean light" themes

---

client/components/boards/boardColors.css

Hello! Here are some fixes to Clean light and Clean dark themes based on usage statistics

Clean theme fixes

---

client/components/activities/activities.jade

Activities, adding back "created at" field

---

.devcontainer/Dockerfile
client/components/boards/boardBody.jade
client/components/boards/boardBody.js
client/components/cards/cardDetails.jade
client/components/cards/checklists.jade
client/components/cards/minicard.jade
client/components/lists/listHeader.jade
client/components/swimlanes/swimlanes.jade
package-lock.json
package.json

click on an empty space in the board, hold the left mouse and move left and right to scroll the board easily

adding Dragscroll to scroll the board

---

models/cards.js
server/migrations.js

reducing:
- cards collection size
- database size
- size to transfer from server to client (publish / subscribe)

reducing card size in database if no planning poker was started

---

client/lib/utils.js

the background image must only be set at 1 div, not at many div's

don't set background image in .board-canvas too

---

client/lib/utils.js

- background-color is maybe wrong too, but better than throwing an exception

Bugfix, variable "color" didn't exist

---

client/components/lists/listHeader.jade

introduced by:
a601ba542aebefdfa8b5d683d22405ab3d5f8569

Bugfix, Cards Count on mobile view was missing

---

client/components/cards/cardDetails.jade

- introduced by commit: 0cc63b810c5a9e23a8a3939a11176f25c1fa8dc7

Bugfix, edit description didn't work if it was clicked

---

client/components/boards/boardColors.css

See issue #5502 
Modified List Header/Text values to unset default line height, and center text when viewed on mobile devices.

Fix ModernDark Mobile View List Titles

---

client/components/boards/boardColors.css

- Added a wide range of updates/tweaks to various board themes
- Better defined theme start/endpoints in code
- Added modern scrollbars matching each theme
- Added styling to scrollbars in pop-over and horizontally across screen
- Tweaks to opacity/themes to work better with board backgrounds.

Large updates to UI

---

.vscode/launch.json

This change fixes and improves debugging DX in VSCode.

Update VSCode debugging configuration

---

docs/Login/LDAP.md

Commit 057ac4031eaa912b849c637e163f4dffa79a9329 moved the location of `ldap-sync.py`. This PR adjusts sources to changes.

Update `ldap-sync.py` reference

---

client/lib/keyboard.js

Introduced a new keyboard shortcut for adding a new card in the current list.

Added 'n' shortcut for adding new minicards to current list

---

client/components/boards/boardColors.css

I'm using Hebrew, this PR fixes some RTL text alignment issues.

Fix some text alignment issues when using RTL languages

---

docker-compose.yml

The keycloak integration doesn't worked for me out of the box.
I added some options that need to be set for keycloak.
It is tested with keycloak v25.0.1

Update docker-compose.yml keycloak part

---

models/users.js

Changed the default maximum list width

---

client/lib/keyboard.js

Fixes https://github.com/wekan/wekan/issues/5631.

Always handle the escape key when shortcuts are enabled

---

client/components/boards/boardColors.css

Fixes https://github.com/wekan/wekan/issues/5625.

Fix comment backgrounds in cleandark theme

---

client/lib/keyboard.js

This PR fixes the "SPACE" shortcut which stopped working due to recent changes.

Fix "SPACE" shortcut not working after recent fixes

---

client/components/cards/cardCustomFields.jade
client/components/cards/cardCustomFields.js
client/components/cards/cardDate.jade
client/components/cards/cardDate.js
client/components/sidebar/sidebar.jade
client/components/sidebar/sidebar.js
imports/i18n/data/en.i18n.json
models/users.js

Default (same as before):
New optional "Disabled" state:

Feature - Add toggle for week-of-year in date displays (ISO 8601)

---

client/components/cards/cardDate.js

i fixed the display demanded in #3802

Time on minicard for start/end/due date

---

models/activities.js

This PR fixes a bug in the Activities.after.insert hook where the .subtasks() helper method was being incorrectly used to retrieve subtask information. The method returns a single card (not a list of subtasks), which led to runtime errors when trying to access properties like title on an undefined or unexpected structure.
Changes Made:
Replaced .subtasks() with .card() in the subtaskId handling block.
Updated variable naming for clarity (subtask instead of subtasks) to reflect that a single card is retrieved.
Verified that the correct card title and ID are now being set in params.

Fixing adding attachments to cards semi fails 

---

docs/Admin/Impersonate-user.md

Improved grammar, clarity, and formatting of the impersonate user instructions.
Related to feature added in wekan#3280.

Improve impersonate user documentation in docs/Admin/Impersonate-user.md

---

client/components/boards/boardsList.js
client/components/cards/minicard.jade
client/components/cards/minicard.js

i fixed the bug on issue #2648 by adding a watch icon that can be toggled to watch a card or unwatch a card

Add toggle watch icon on card

---

client/components/boards/boardColors.css

- Fix contrast issue with CleanDark & CleanLight buttons on theme selection menu.

Fix more contrasting issues

---

models/lists.js
public/api/wekan.yml

I have tested it locally and it works for me.

Add REST API endpoint to edit a list with various properties
